### ISSUE TITLE
System-dependent doctest failures

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1048]
I originally reported these on the [mailing list](https://groups.google.com/forum/#!topic/scikit-image/v8xjq7_2xq4), adding them here for tracking. The solution will in part depend on explicitly setting the print precision in numpy for doctests.

Running `skimage.doctest()` on my system (OSX 10.9, Anaconda) results in failures, apparently due to precision issues (see below).

```
........................................F.F...................................F./Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py:4: skimage_deprecation: Call to deprecated function ``label``. Use ``skimage.measure.label`` instead.
  return _label(input, neighbors, background, return_num)
..F.......................................................
======================================================================
FAIL: Doctest: skimage.feature.texture.greycoprops
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for skimage.feature.texture.greycoprops
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/feature/texture.py", line 125, in greycoprops

----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/feature/texture.py", line 176, in skimage.feature.texture.greycoprops
Failed example:
    contrast
Expected:
    array([[ 0.58333333,  1.        ],
           [ 1.25      ,  2.75      ]])
Got:
    array([[ 0.5833333333,  1.          ],
           [ 1.25        ,  2.75        ]])


======================================================================
FAIL: Doctest: skimage.filter._gaussian.gaussian_filter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for skimage.filter._gaussian.gaussian_filter
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/filter/_gaussian.py", line 13, in gaussian_filter

----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/filter/_gaussian.py", line 73, in skimage.filter._gaussian.gaussian_filter
Failed example:
    gaussian_filter(a, sigma=0.4)  # mild smoothing
Expected:
    array([[ 0.00163116,  0.03712502,  0.00163116],
           [ 0.03712502,  0.84496158,  0.03712502],
           [ 0.00163116,  0.03712502,  0.00163116]])
Got:
    array([[ 0.0016311596,  0.0371250207,  0.0016311596],
           [ 0.0371250207,  0.8449615765,  0.0371250207],
           [ 0.0016311596,  0.0371250207,  0.0016311596]])
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/filter/_gaussian.py", line 77, in skimage.filter._gaussian.gaussian_filter
Failed example:
    gaussian_filter(a, sigma=1)  # more smooting
Expected:
    array([[ 0.05855018,  0.09653293,  0.05855018],
           [ 0.09653293,  0.15915589,  0.09653293],
           [ 0.05855018,  0.09653293,  0.05855018]])
Got:
    array([[ 0.0585501805,  0.096532928 ,  0.0585501805],
           [ 0.096532928 ,  0.1591558917,  0.096532928 ],
           [ 0.0585501805,  0.096532928 ,  0.0585501805]])
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/filter/_gaussian.py", line 82, in skimage.filter._gaussian.gaussian_filter
Failed example:
    gaussian_filter(a, sigma=1, mode='reflect')
Expected:
    array([[ 0.08767308,  0.12075024,  0.08767308],
           [ 0.12075024,  0.16630671,  0.12075024],
           [ 0.08767308,  0.12075024,  0.08767308]])
Got:
    array([[ 0.0876730803,  0.1207502431,  0.0876730803],
           [ 0.1207502431,  0.1663067063,  0.1207502431],
           [ 0.0876730803,  0.1207502431,  0.0876730803]])


======================================================================
FAIL: Doctest: skimage.measure._label.label
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for skimage.measure._label.label
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line unknown line number, in label

----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    x = np.eye(3).astype(int)
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[0]>", line 1, in <module>
        x = np.eye(3).astype(int)
    NameError: name 'np' is not defined
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    print(x)
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[1]>", line 1, in <module>
        print(x)
    NameError: name 'x' is not defined
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    print(m.label(x, neighbors=4))
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[2]>", line 1, in <module>
        print(m.label(x, neighbors=4))
    NameError: name 'm' is not defined
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    print(m.label(x, neighbors=8))
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[3]>", line 1, in <module>
        print(m.label(x, neighbors=8))
    NameError: name 'm' is not defined
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    x = np.array([[1, 0, 0],
                  [1, 1, 5],
                  [0, 0, 0]])
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[4]>", line 1, in <module>
        x = np.array([[1, 0, 0],
    NameError: name 'np' is not defined
----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/_label.py", line ?, in skimage.measure._label.label
Failed example:
    print(m.label(x, background=0))
Exception raised:
    Traceback (most recent call last):
      File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest skimage.measure._label.label[5]>", line 1, in <module>
        print(m.label(x, background=0))
    NameError: name 'm' is not defined


======================================================================
FAIL: Doctest: skimage.measure.fit.ransac
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for skimage.measure.fit.ransac
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/fit.py", line 470, in ransac

----------------------------------------------------------------------
File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/skimage/measure/fit.py", line 576, in skimage.measure.fit.ransac
Failed example:
    ransac_model.params
Expected:
    array([ 20.12762373,  29.73563063,   4.81499637,  10.4743584 ,   0.05217117])
Got:
    array([ 20.1276237259,  29.7356306313,   4.8149963715,  10.474358404 ,
             0.0521711691])
```

**Comment by blink1073** [comment]
We could use `#  doctest: +ELLIPSIS` and add change it to:

```
array([[ 0.58333333...,  1.        ],
           [ 1.25      ,  2.75      ]])
````

**Comment by matthew-brett** [comment]
Ellipsis sounds like a good solution for the floating point mismatches.

**Comment by tonysyu** [comment]
Strange: I'm on OSX 10.10 and the doctests seem to pass on my system. Is this a numpy version issue (rather than an OSX issue)? I'm on numpy 1.8.1.

Regardless, these tests shouldn't be so strict. @JDWarner's suggestion of setting `numpy.set_printoptions` sounds better than setting `# doctest: +ELLIPSIS `, in my opinion, but the doctest directive wouldn't be that bad either.

**Comment by tonysyu** [comment]
BTW, I'm not sure this issue should be a blocker for the 0.11 release: doctests aren't run by default (although maybe they should be) so I'd be surprised if they passed on 0.10.

**Comment by matthew-brett** [comment]
`set_printoptions` needs an extra line of Python code in the doctest, as compared to a comment after the code for the ellipsis.

Also - the set_printoptions setting seem to last across functions when running doctests via ``python -m doctest thefile.py`` but not via nosetests, which is a little confusing.

**Comment by matthew-brett** [comment]
I don't get any failures on numpy standard wheel installs for numpy 1.8.1 or numpy 1.9.1 - maybe it's Anaconda MKL.  In any case @jni - you may need to choose a fix for these because we can't replicate the failures.

**Comment by JDWarner** [comment]
From latest master on OSX 10.6.8, using latest Anaconda w/MKL - all doctests pass.

@jni you wouldn't happen to have your global print options set in a custom config file somewhere, would you? ;)

**Comment by jni** [comment]
@JDWarner I wouldn't even know how to do that, so I doubt it. However, I'm going to agree with @matthew-brett and @tonysyu that this is peculiar to my specific machine and config, and not my OS/Python version more generally. So I'm going to remove the 0.11 tag. I'll play more when I have some time...

**Comment by soupault** [comment]
@jni Any updates on this?

**Comment by soupault** [comment]
@jni Any updates on this?

**Comment by jni** [comment]
LOL:

```python
>>> import skimage
>>> skimage.doctest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jni/conda/envs/ana3/lib/python3.5/site-packages/skimage/__init__.py", line 90, in _test
    with warnings.catch_warnings():
NameError: name 'warnings' is not defined
```

This appears to be due to `del warnings, ...` at the end of `skimage/__init__.py`. Perhaps the solution is to import within individual functions instead of globally?

**Comment by blink1073** [comment]
Yep, I can confirm that importing warnings from within that file works, and the test suite passes.

**Comment by blink1073** [comment]
On OSX 10.11.4, `Python 3.4.4 |Anaconda 2.4.1`

**Comment by jni** [comment]
Hmm, I'm getting quite a few doctest failures, some of which appear to be quite legitimate and not platform dependent. See gist [here](https://gist.github.com/jni/30c9ee96ecc3263f319b49e327cf1e00). Aren't we running doctests with Travis???

**Comment by blink1073** [comment]
Had you built skimage in that environment?

**Comment by jni** [comment]
@blink1073 yep, this is the location of one of the failed doctests:
```
/Users/jni/conda/envs/ana3/lib/python3.5/site-packages/scikit_image-0.13.dev0-py3.5-macosx-10.5-x86_64.egg/skimage/draw/_draw.cpython-35m-darwin.so
```

**Comment by blink1073** [comment]
Hmm, I couldn't replicate with Anaconda Python 3.5 and Numpy 1.10.1.

**Comment by jni** [comment]
@blink1073 really, you saw *none* of the failures??? I was sure some of them would crop up...! Oh well, I'm happy to keep this closed, as it looks like my computer simply hates doctests. =P

**Comment by blink1073** [comment]
No failures, not sure what kind of ghosts you have in your machine ;)

**Comment by stefanv** [comment]
![](https://cdn2.vox-cdn.com/uploads/chorus_asset/file/6107121/ghost-in-the-shell-typing.0.gif)
