### ISSUE TITLE
Problem with data files path when packaging with py2exe

### ISSUE THREAD

**Issue by varnivey** [scikit-image/scikit-image#1157]
Hi, everyone!

I am trying to boundle my project which uses skimage.feature module with py2exe. I have the following configuration:

python version: 2.7.8
scikit-image version: 0.10.1

This is the output of my simple_gui.exe  binary generated with py2exe:

```
Traceback (most recent call last):
  File "simple_gui.py", line 22, in <module>
  File "pic_an.pyc", line 34, in <module>
  File "pic_an_calc.pyc", line 29, in <module>
  File "skimage\feature\__init__.pyc", line 14, in <module>
  File "skimage\feature\orb.pyc", line 11, in <module>
  File "skimage\feature\orb_cy.pyc", line 12, in <module>
  File "skimage\feature\orb_cy.pyc", line 10, in __load
  File "orb_cy.pyx", line 16, in init skimage.feature.orb_cy (skimage\feature\orb_cy.c:17408)
  File "numpy\lib\npyio.pyc", line 737, in loadtxt
IOError: [Errno 2] No such file or directory: 'F:\\Users\\Vanya\\Progs\\Python_win32\\darfi_py2exe\\simple_gui\\dist\\simple_gui.exe\\skimage\\data\\orb_descriptor_positions.txt'
```

The problem is that the path to the orb_descriptor_positions.txt file contains the name of the running *.exe, which should not happen normally. At the beginning of the orb_cy.pyx one will find:

```
#cython: cdivision=True
#cython: boundscheck=False
#cython: nonecheck=False
#cython: wraparound=False

import os
import numpy as np

from skimage import data_dir

cimport numpy as cnp
from libc.math cimport sin, cos

from skimage._shared.interpolation cimport round

POS = np.loadtxt(os.path.join(data_dir, "orb_descriptor_positions.txt"),
dtype=np.int8)
```

As I understood the problem is with the wrong skimage.datadir definition. Can it be fixed somehow on the scikit-image source level?

**Comment by soupault** [comment]
@varnivey Since a lot of things changed in py2exe since 2014, could you try to bundle your app again and confirm if bug is still presented?

**Comment by varnivey** [comment]
Hey @soupault!

I confirm that the problem persists with scikit-image 0.11.3, python 2.7.10 and py2exe 0.6.9. I still use the above solution to avoid that.

**Comment by kervel** [comment]
Hello, 

i'm having the same problem with cx_freeze (another python packaging script).
the above workaround does not work for me.

i think the proper fix would be one described here:
http://stackoverflow.com/questions/10935127/way-to-access-resource-files-in-python
(get_data our pkgutil)

Frank

**Comment by varnivey** [comment]
Thank you @kervel . The suggestion is useful, but still it may be easier to modify the package itself in the way, that does not require any additional workarounds.

**Comment by catabre** [comment]
Any workaround for this bug that can be incorporated till the issue is fixed in the package. 
I am trying to package the app with py2app and defining the configurations in setup.py. 
Anything that can be included in setup.py that can solve the problem to unblock

**Comment by stefanv** [comment]
@catabre Are you able to provide a patch that solves your problem?  None of the core team uses py2exe, so I don't think we'll be of much help.  If you can help us by providing the exact error messages you see, that would also be useful.

**Comment by catabre** [comment]
@stefanv  This is the error i am getting on running the packaged app. 

`Traceback (most recent call last):
  File "<frozen zipimport>", line 259, in load_module
  File "skimage/feature/orb_cy.pyc", line 14, in <module>
  File "skimage/feature/orb_cy.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1181, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "skimage/feature/orb_cy.pyx", line 13, in init skimage.feature.orb_cy
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "skimage/feature/_orb_descriptor_positions.pyc", line 8, in <module>
  File "/Users/300002291/Documents/dtcropflow/dist/dtpixelflow.app/Contents/Resources/lib/python3.9/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/300002291/Documents/dtcropflow/dist/dtpixelflow.app/Contents/Resources/lib/python3.9/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/300002291/Documents/dtcropflow/dist/dtpixelflow.app/Contents/Resources/lib/python3.9/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: /Users/300002291/Documents/dtcropflow/dist/dtpixelflow.app/Contents/Resources/lib/python39.zip/skimage/feature/orb_descriptor_positions.txt not found.
`
