### ISSUE TITLE
Test suite without Qt

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#1395]
Right now the test suite cannot be run without Qt. This is not ideal. Is there a specific reason for that?

See `skimage._shared.testing.setup_test()`.

**Comment by blink1073** [comment]
What do you mean?  Our Travis build works just fine with and without Qt installed.  You'll get a warning that the viewer is not available, but that should be it.

**Comment by ahojnnes** [comment]
```
======================================================================
ERROR: test suite for <module 'skimage.feature.tests.test_corner' from '/scikit-image/skimage/feature/tests/test_corner.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/miniconda/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/miniconda/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/miniconda/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/scikit-image/skimage/feature/tests/__init__.py", line 5, in setup
    setup_test()
  File "/scikit-image/skimage/_shared/testing.py", line 191, in setup_test
    from skimage import viewer, filter
  File "/scikit-image/skimage/viewer/__init__.py", line 2, in <module>
    from .viewers import ImageViewer, CollectionViewer
  File "/scikit-image/skimage/viewer/viewers/__init__.py", line 1, in <module>
    from .core import ImageViewer, CollectionViewer
  File "/scikit-image/skimage/viewer/viewers/core.py", line 9, in <module>
    from ..qt import QtWidgets, Qt, Signal
ImportError: cannot import name QtWidgets

----------------------------------------------------------------------
Ran 0 tests in 0.037s

FAILED (errors=1)
```

**Comment by blink1073** [comment]
Hmm, it looks like we need to define the placeholders and then attempt to import the real stuff.

**Comment by blink1073** [comment]
I still don't get why you're seeing this error.  What version of matplotlib do you have?

**Comment by blink1073** [comment]
I think I've got it, accidentally ran into the same problem. Do you still have a `qt` directory in `skimage.viewer`?  If so, delete it and try again.

**Comment by ahojnnes** [comment]
That's it. Thanks.
