### ISSUE TITLE
test_rank test_all  failed test on 32bit

### ISSUE THREAD

**Issue by yarikoptic** [scikit-image/scikit-image#1407]
```
======================================================================
FAIL: skimage.filters.rank.tests.test_rank.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/skimage-0.11.0/debian/tmp/usr/lib/python2.7/dist-packages/skimage/filters/rank/tests/test_rank.py", line 15, in test_all
    check_all()
  File "/tmp/buildd/skimage-0.11.0/debian/tmp/usr/lib/python2.7/dist-packages/skimage/filters/rank/tests/test_rank.py", line 78, in check_all
    rank.entropy(image, selem))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 260, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 1.28%)
 x: array([[ 1.5849625 ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,...
 y: array([[ 1.5849625 ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
         2.        ,  2.        ,  2.        ,  2.        ,  2.        ,...

----------------------------------------------------------------------
Ran 1272 tests in 197.154s
```

on Debian jessie 32bit only... here is tiny details:

```
(Pdb) print np.max(np.abs(actual-desired))
2.22044604925e-16
(Pdb) print np.where(actual-desired!=0)
(array([ 0,  0, 11, 12, 12, 13, 24, 24]), array([ 0, 24,  9,  7,  8,  7,  0, 24]))
(Pdb) print actual[np.where(actual-desired!=0)]
[ 1.5849625   1.5849625   1.92192809  1.92192809  1.92192809  1.92192809
  1.5849625   1.5849625 ]
(Pdb) print desired[np.where(actual-desired!=0)]
[ 1.5849625   1.5849625   1.92192809  1.92192809  1.92192809  1.92192809
  1.5849625   1.5849625 ]
```

**Comment by soupault** [comment]
Hi, @yarikoptic . Could you confirm if bug is still presented?

**Comment by soupault** [comment]
@stefanv @blink1073 @JDWarner What is the story behind testing only on x86_64?

**Comment by blink1073** [comment]
@soupault, Travis CI only has 64 bit builds.  We are testing using 32 bits on Appveyor though:  https://github.com/scikit-image/scikit-image/blob/master/appveyor.yml#L12

**Comment by soupault** [comment]
Please, follow the discussion in #2528 . Closing this as duplicate (although, it is actually the original ;) ).
