### ISSUE TITLE
Python 2.7 travis flake8 problem.

### ISSUE THREAD

**Issue by warmspringwinds** [scikit-image/scikit-image#1458]
Every time the travis checks are ran after my commits, I have the follwing mistake and I saw a lot of pull requests having the same:

Flake8 test *

+flake8 --exit-zero '--exclude=test_*,six.py' skimage doc/examples viewer_examples

Traceback (most recent call last):

File "/home/travis/venv/bin/flake8", line 7, in

from flake8.main import main

File "/home/travis/venv/local/lib/python2.7/site-packages/flake8/main.py", line 5, in

import setuptools

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/init.py", line 11, in

from setuptools.extension import Extension

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/extension.py", line 8, in

from .dist import _get_unpatched

File "/home/travis/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 21, in

packaging = pkg_resources.packaging

AttributeError: 'module' object has no attribute 'packaging'`

Is there a way to avoid it?

Thank you

**Comment by blink1073** [comment]
Thanks @warmspringwinds, this is a known problem that I'm working on in #1457.
