### ISSUE TITLE
test_imsave_roundtrip failures for uint 8 and 16 on Debian sid

### ISSUE THREAD

**Issue by yarikoptic** [scikit-image/scikit-image#1463]
was trying to build package for 0.11.3
got

```
======================================================================
FAIL: skimage.io.tests.test_freeimage.TestSave.test_imsave_roundtrip(<type 'numpy.uint8'>, array([[139, 182, 153, 138, 108, 164, 111, 227, 245,  97],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/skimage-0.11.3/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/tests/test_freeimage.py", line 85, in roundtrip
    assert_array_equal(y, x)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 90.0%)
 x: array([[139,  43, 227, 241, 226,  56, 203, 116,  18, 108],
       [201, 189,  10,  92,  38,   4, 239, 207, 242,  23],
       [249, 210, 170,  82,  87, 133, 129, 204, 149, 228],...
 y: array([[139, 182, 153, 138, 108, 164, 111, 227, 245,  97],
       [201, 134, 144, 236,  18,  22,   5, 212, 198, 221],
       [249, 203, 117, 199,  30, 163,  36, 240, 133, 105],...


======================================================================
FAIL: skimage.io.tests.test_freeimage.TestSave.test_imsave_roundtrip(<type 'numpy.uint16'>, array([[ 79, 177,  96,  45,   6,  17, 173, 115, 136, 228],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/skimage-0.11.3/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/tests/test_freeimage.py", line 85, in roundtrip
    assert_array_equal(y, x)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 90.0%)
 x: array([[   79,    98, 65455, 65485, 65497,    11,   156, 65478,    21,
           92],
       [  252, 65339,   114, 65434, 65474,   188, 65424,    16,    53,...
 y: array([[ 79, 177,  96,  45,   6,  17, 173, 115, 136, 228],
       [252,  55, 169,  67,   5, 193,  81,  97, 150, 211],
       [160, 222,  69, 203,  47, 242, 175,  54, 241, 186],...

```

also got 1 more failure

```
======================================================================
FAIL: skimage.io.tests.test_freeimage.test_write_multipage
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/tmp/buildd/skimage-0.11.3/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/tests/test_freeimage.py", line 75, in test_write_multipage
    assert_array_equal(x, y)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 98.0579376221%)
 x: array([[[210, 190, 130, ..., 245, 199,  42],
        [140, 105,  38, ...,  89,  68,  15],
        [209,  96, 145, ...,  93, 100,  58],...
 y: array([[[210,  26, 216, ..., 240, 252, 145],
        [140,  81, 224, ...,  58, 107, 224],
        [209, 190, 162, ...,  66,  93, 207],...
```

which might be related...? 

```
~/skimage-0.11.3# apt-cache policy python-{pil,numpy}
python-pil:
  Installed: 2.6.1-2
  Candidate: 2.6.1-2
  Version table:
 *** 2.6.1-2 0
        500 http://debproxy:9999/debian/ sid/main amd64 Packages
        100 /var/lib/dpkg/status
python-numpy:
  Installed: 1:1.8.2-2
  Candidate: 1:1.8.2-2
  Version table:
 *** 1:1.8.2-2 0
        500 http://debproxy:9999/debian/ sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by blink1073** [comment]
Hi  @yarikoptic, what version of libfreeimage do you have?

**Comment by yarikoptic** [comment]
@blink1073 it is  3.15.4-4.1+b1

**Comment by blink1073** [comment]
Hmm, we are using Ubuntu 12.04 64bit on our Continuous Integration server, which has 3.15.1-1.   I'm not sure why you would see any differently.

**Comment by stefanv** [comment]
@blink1073 Perhaps freeimage is doing something strange specifically on 32-bit systems?  Do we have such a machine to test on?

**Comment by blink1073** [comment]
@stefanv, I noticed from @yarikoptic's output that he was using amd64.

**Comment by yarikoptic** [comment]
yes -- that was on amd64 and issue still persists. libfreeimage is 3.15.4-4.1+b2
Additionally experiencing
```
======================================================================
FAIL: skimage.io.tests.test_freeimage.test_write_multipage
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/tmp/buildd/skimage-0.11.3/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/tests/test_freeimage.py", line 75, in test_write_multipage
    assert_array_equal(x, y)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 98.0579376221%)
 x: array([[[210, 190, 130, ..., 245, 199,  42],
        [140, 105,  38, ...,  89,  68,  15],
        [209,  96, 145, ...,  93, 100,  58],...
 y: array([[[210,  26, 216, ..., 240, 252, 145],
        [140,  81, 224, ...,  58, 107, 224],
        [209, 190, 162, ...,  66,  93, 207],...
```

just in case you need debian sid, there are docker images, so `docker run -it --rm=true --entrypoint=/bin/bash debian:sid` and then inside `sed -ie 's,^deb \(.*\),deb \1\ndeb-src \1,g' /etc/apt/sources.list; apt-get update; apt-get build-dep -y python-skimage; apt-get install git; ` to get env ready to reproduce. from master also getting few more errors (why warning is an error?) in such environment (installed also python-tk pkg) 
```
======================================================================
ERROR: skimage.io.tests.test_freeimage.TestSave.test_imsave_roundtrip(<type 'numpy.uint16'>, array([[ 79, 177,  96,  45,   6,  17, 173, 115, 136, 228],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/scikit-image/skimage/io/tests/test_freeimage.py", line 83, in roundtrip
    sio.imsave(fname, x)
  File "/tmp/scikit-image/skimage/io/_io.py", line 121, in imsave
    warnings.warn('%s is a low contrast image' % fname)
UserWarning: /tmp/tmp4hegaD.tif is a low contrast image
```
but also those I have listed above. what should we do? ;)

**Comment by yarikoptic** [comment]
@stefanv knock knock

**Comment by stefanv** [comment]
I guess we have a few options here: a) remove freeimage plugin b) find out if there is a bug in the freeimage library on these debian systems c) build in a workaround in scikit-image (hard without much further investigation).  @blink1073, have you had a look at this one yet?

**Comment by blink1073** [comment]
I'm fine with removing the freeimage plugin, since we have an imageio plugin now that defaults to using freeimage.

**Comment by stefanv** [comment]
That sounds like a fine solution to me.  Any takers?

**Comment by blink1073** [comment]
Are you asking for concurrence or for someone to remove the plugin?

**Comment by soupault** [comment]
@scikit-image/core any further thoughts on the issue?

**Comment by blink1073** [comment]
We could deprecate the freeimage plugin for 0.12 and remove it in 0.13, sound good @stefanv?

**Comment by stefanv** [comment]
Let's go ahead and replace our freeimage plugin with that of imageio.  The last release was end of January, and the developers are on top of it.

**Comment by sciunto** [comment]
Closing this issue, freeimage has been removed.
