### ISSUE TITLE
Measure region properties ERROR

### ISSUE THREAD

**Issue by buratono** [scikit-image/scikit-image#1471]
I tried this example:
http://scikit-image.org/docs/dev/auto_examples/plot_regionprops.html

But I found error below
(Windows 7, 64-bit, Python 2.7)
Traceback (most recent call last):
  File "E:\DropboxT\Dropbox\Works\ectrack\tools\plot_regionprops.py", line 32, in <module>
    y0, x0 = props.centroid
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 129, in centroid
    row, col = self.local_centroid
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 209, in local_centroid
    m = self.moments
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 103, in __get__
    value = self.func(obj)
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 238, in moments
    return _moments.moments(self.image.astype(np.uint8), 3)
  File "_moments.pyx", line 8, in skimage.measure._moments.moments (skimage\measure\_moments.c:1470)
ValueError: Buffer dtype mismatch, expected 'double' but got 'unsigned char'

**Comment by JDWarner** [comment]
@buratono this sounds like a retread of #1465. Please try the solutions covered there, and let us know if that resolves the problem or not.

**Comment by buratono** [comment]
@JDWarner: it's not the same problem as #1465.
In my code, I don't have problem with area, it can be accessed using convex_area, but I couldn't get centroid or local_centroid.

**Comment by JDWarner** [comment]
@buratono If you can provide an example - ideally with a test image - so we can reproduce this, that would be ideal.

**Comment by soupault** [comment]
Can't replicate with neither Python 2.7 nor 3.5. Using latest stable `skimage`.

@buratono do you have any updates?

Unless we get some news, I'd suggest to close the issue.

**Comment by soupault** [comment]
Closing the issue. Reopen if neccessary.
