### ISSUE TITLE
Unable to import novice 

### ISSUE THREAD

**Issue by animanathome** [scikit-image/scikit-image#1482]
I've just installed scikit-image using "pip install -U scikit-image". When then trying to import the novice submodule through "from skimage import novice" my system hangs. When I escape I'm getting the following message:

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/novice/__init__.py", line 72, in <module>
    from ._novice import Picture, open, colors, color_dict
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/novice/_novice.py", line 7, in <module>
    from .. import io, img_as_ubyte
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/manage_plugins.py", line 89, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/manage_plugins.py", line 81, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/manage_plugins.py", line 251, in use_plugin
    _load(name)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/manage_plugins.py", line 295, in _load
    fromlist=[modname])
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-x86_64.egg/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 27, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/usr/local/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/usr/local/lib/python2.7/site-packages/matplotlib/textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1415, in <module>
    _rebuild()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1400, in _rebuild
    fontManager = FontManager()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1040, in __init__
    self.ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 323, in findSystemFonts
    for f in get_fontconfig_fonts(fontext):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 276, in get_fontconfig_fonts
    output = pipe.communicate()[0]
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1403, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1504, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt

**Comment by animanathome** [comment]
Hmmm, strange, everything seems to be working fine now. I guess it just takes a couple of minutes the first time you import that module?

**Comment by JDWarner** [comment]
Matplotlib was hanging while introspecting your system fonts. We require Matplotlib for the `skimage.io` package which allows reading of image data files. If you have a lot of fonts, this can take some time and may appear to hang.

Attempting to run `>>> import matplotlib.pyplot as plt` would have reproduced the error, and confirmed it wasn't within the purview of scikit-image.

EDIT: Sounds like this just needed more time, but for completeness I'm leaving my answer.
