### ISSUE TITLE
Unable to install scikit-image on windows

### ISSUE THREAD

**Issue by siddjain** [scikit-image/scikit-image#1490]
Hello, I am getting this error trying to install scikit-image on windows:
$ pip install scikit_image-0.11.3-cp34-none-win32.whl
scikit_image-0.11.3-cp34-none-win32.whl is not a supported wheel on this platform.

i have mingw32 and
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32

and if i try to install from source, I get another error:
$ pip install .
Unpacking c:\scikit-image\scikit-image
  Running setup.py (path:c:\users\user\appdata\local\temp\pip-3hazfl-build\s
etup.py) egg_info for package from file:///c:/scikit-image/scikit-image
    Unable to find pgen, not compiling formal grammar.
    Compiling module Cython.Plex.Scanners ...
    Compiling module Cython.Plex.Actions ...
    Compiling module Cython.Compiler.Lexicon ...
    Compiling module Cython.Compiler.Scanning ...
    Compiling module Cython.Compiler.Parsing ...
    Compiling module Cython.Compiler.Visitor ...
    Compiling module Cython.Compiler.FlowControl ...
    Compiling module Cython.Compiler.Code ...
    Compiling module Cython.Tempita._tempita ...
    No eggs found in c:\users\user\appdata\local\temp\easy_install-ebiglc\Cy
thon-0.22\egg-dist-tmp-xtizte (setup script problem?)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\user\appdata\local\temp\pip-3hazfl-build\setup.py", lin
e 119, in <module>
        cmdclass={'build_py': build_py},
      File "c:\Python27\lib\site-packages\numpy\distutils\core.py", line 126, in
 setup
        dist = setup(**new_attr)
      File "c:\Python27\lib\site-packages\numpy\distutils\core.py", line 169, in
 setup
        return old_setup(**new_attr)
      File "c:\Python27\lib\distutils\core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\Python27\lib\site-packages\numpy\distutils\numpy_distribution.py"
, line 16, in __init__
        Distribution.__init__(self, attrs)
      File "c:\Python27\lib\site-packages\setuptools\dist.py", line 260, in __in
it__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "c:\Python27\lib\site-packages\setuptools\dist.py", line 285, in fetc
h_build_eggs
        replace_conflicting=True
      File "c:\Python27\lib\site-packages\pkg_resources.py", line 639, in resolv
e
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

Compiling module Cython.Plex.Scanners ...

Compiling module Cython.Plex.Actions ...

Compiling module Cython.Compiler.Lexicon ...

Compiling module Cython.Compiler.Scanning ...

Compiling module Cython.Compiler.Parsing ...

Compiling module Cython.Compiler.Visitor ...

Compiling module Cython.Compiler.FlowControl ...

Compiling module Cython.Compiler.Code ...

Compiling module Cython.Tempita._tempita ...

No eggs found in c:\users\user\appdata\local\temp\easy_install-ebiglc\Cython
-0.22\egg-dist-tmp-xtizte (setup script problem?)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\user\appdata\local\temp\pip-3hazfl-build\setup.py", line 11
9, in <module>

    cmdclass={'build_py': build_py},

  File "c:\Python27\lib\site-packages\numpy\distutils\core.py", line 126, in set
up

    dist = setup(**new_attr)

  File "c:\Python27\lib\site-packages\numpy\distutils\core.py", line 169, in set
up

    return old_setup(**new_attr)

  File "c:\Python27\lib\distutils\core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "c:\Python27\lib\site-packages\numpy\distutils\numpy_distribution.py", li
ne 16, in __init__

    Distribution.__init__(self, attrs)

  File "c:\Python27\lib\site-packages\setuptools\dist.py", line 260, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "c:\Python27\lib\site-packages\setuptools\dist.py", line 285, in fetch_bu
ild_eggs

    replace_conflicting=True

  File "c:\Python27\lib\site-packages\pkg_resources.py", line 639, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: cython>=0.21

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in c:\users\user\a
ppdata\local\temp\pip-3hazfl-build
Storing debug log for failure in c:/Users/user\pip\pip.log

**Comment by siddjain** [comment]
i think i found the solution: http://stackoverflow.com/questions/28568070/filename-whl-is-not-supported-wheel-on-this-platform. this worked:
$ pip install scikit_image-0.11.3-cp27-none-win32.whl
