### ISSUE TITLE
Scikit stable install failing on Ubuntu 13.04

### ISSUE THREAD

**Issue by ThunderShiviah** [scikit-image/scikit-image#1509]
I'm trying to install scikit-image 0.11.3 in a virtual environment.

After typing in 
```sudo pip install -U scikit-image```

I receive the following error message:

```
Requirement already up-to-date: scikit-image in /usr/local/lib/python2.7/dist-packages
Collecting six>=1.3 (from scikit-image)
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.2.0
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed six-1.2.0
```

Attempting to import either `skimage` or `six` into a python shell gives an import error.

Additionally, trying to install scikit-image using
```sudo apt-get install python-skimage```

Produces the following output
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libfreeimage3 python-skimage-lib
Suggested packages:
  python-skimage-doc python-opencv
The following NEW packages will be installed:
  libfreeimage3 python-skimage python-skimage-lib
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 4,526 kB of archives.
After this operation, 8,526 kB of additional disk space will be used.
Do you want to continue [Y/n]? Y
Get:1 http://old-releases.ubuntu.com/ubuntu/ raring/universe python-skimage-lib amd64 0.7.2-1 [635 kB]
Get:2 http://old-releases.ubuntu.com/ubuntu/ raring/universe libfreeimage3 amd64 3.15.1-1 [812 kB]                                                                        
Get:3 http://old-releases.ubuntu.com/ubuntu/ raring/universe python-skimage all 0.7.2-1 [3,078 kB]                                                                        
Fetched 4,526 kB in 22s (200 kB/s)                                                                                                                                        
Selecting previously unselected package python-skimage-lib.
(Reading database ... 501642 files and directories currently installed.)
Unpacking python-skimage-lib (from .../python-skimage-lib_0.7.2-1_amd64.deb) ...
Selecting previously unselected package libfreeimage3.
Unpacking libfreeimage3 (from .../libfreeimage3_3.15.1-1_amd64.deb) ...
Selecting previously unselected package python-skimage.
Unpacking python-skimage (from .../python-skimage_0.7.2-1_all.deb) ...
Processing triggers for man-db ...
Setting up python-skimage-lib (0.7.2-1) ...
Setting up libfreeimage3 (3.15.1-1) ...
Setting up python-skimage (0.7.2-1) ...
Processing triggers for python-support ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
```

but fails to import.

**Comment by jni** [comment]
I'm not sure about all the errors you're seeing but I think it probably has to do with your virtualenv setup. In particular, you shouldn't need to sudo to install into a virtualenv, and that might have done interesting things to your permissions, resulting in the pip errors you're seeing.

Can you try creating a new virtualenv and installing everything without using sudo? And please report back all the commands and output here. Thanks!

(I don't know anything about the apt-get distribution, but it seems woefully out of date!)

**Comment by ThunderShiviah** [comment]
Issuing the command 
```pip install -U scikit-image```

produces the following output

```
  Downloading scikit-image-0.11.3.tar.gz (18.6MB)
    100% |████████████████████████████████| 18.6MB 23kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-XUQXHc/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XUQXHc/scikit-image

```

This new error looks similar to #1329.

Also, I tried the apt-get method since that's what's recommended on the scikit readme for ubuntu.

**Comment by jni** [comment]
Hmm, interesting, I'll let @stefanv and @blink1073 comment on the error, which, as discussed in #1329, really shouldn't be there anymore!

In the meantime, what happens if you try pip install -U numpy scikit-image?

**Comment by ThunderShiviah** [comment]
Same issue:

```
  Downloading numpy-1.9.2.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 119kB/s 
Collecting scikit-image
  Downloading scikit-image-0.11.3.tar.gz (18.6MB)
    100% |████████████████████████████████| 18.6MB 24kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-oyLD_a/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oyLD_a/scikit-image

```

**Comment by jni** [comment]
This is so weird. I guess pip doesn't care about the order of the arguments? What about `pip install numpy; pip install -U scikit-image`?

**Comment by ThunderShiviah** [comment]
```
ImportError: No module named scipy
```

What's really strange is that my scikit-image installation was working a few days ago and then the next time I tried running a file, scikit wouldn't work at all. I wonder if something broke on a recent update?

**Comment by blink1073** [comment]
@ThunderShiviah, is there any reason you cannot use Anaconda for your environment?  In my experience, trying to use numpy/scipy in a virtualenv on Ubuntu was nothing but a headache.

**Comment by jni** [comment]
@ThunderShiviah So it sounds like you got the scikit-image installation working, but you were missing scipy at runtime, right? That's expected. SciPy is a dependency, even though it's not needed for installation.

@blink1073 obviously I agree about Anaconda, but shouldn't this `distutils` error be gone in 0.11?

**Comment by blink1073** [comment]
@jni, I agree, assuming one can `numpy` and `scipy` installed in the virtualenv first.

**Comment by ThunderShiviah** [comment]
@jni  Actually I was still unable to import skimage after that.

@blink1073  Are you suggesting installing via the `conda` command? I'm working on a skimage based image registration project and am trying to keep all my dependencies together to create a requirements.txt file. 

Also, maybe this is off topic for this issue but my system wide version of skimage uses the Anaconda distro. My skimage was working about a week ago but when I tried to import skimage (outside of a virtualenv) I got the following result:

```
  File "registration.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 26, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 36, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 19, in <module>
    import matplotlib.dates as _ # <-registers a date unit converter
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 122, in <module>
    from dateutil.rrule import rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY, \
  File "/usr/local/lib/python2.7/dist-packages/dateutil/rrule.py", line 16, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

Furthermore, if I try to import skimage I get an import error (despite being able to import it fine a week ago and nothing changing system-wide on my side).

**Comment by ThunderShiviah** [comment]
It appears that matplotlib is causing at least part of the trouble in the install;

I installed the following packages independently in my virtualenv (the packages came from a list of the anaconda packages)
```
alabaster==0.7.4
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
certifi==2015.4.28
docutils==0.12
ipython==3.1.0
Jinja2==2.7.3
jsonschema==2.4.0
Logbook==0.9.1
MarkupSafe==0.23
mistune==0.5.1
nose==1.3.6
numpy==1.9.2
numpydoc==0.5
pandas==0.16.1
patsy==0.3.0
Pillow==2.8.1
ptyprocess==0.4
Pygments==2.0.2
python-dateutil==2.4.2
pytz==2015.2
pyzmq==14.6.0
Quandl==2.8.6
requests==2.7.0
scikit-learn==0.16.1
scipy==0.15.1
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
statsmodels==0.6.1
sympy==0.7.6
terminado==0.5
tornado==4.1
zipline==0.7.0
```

Next, I ran ` pip install -U scikit-image`

which yielded the following output

```
Downloading scikit-image-0.11.3.tar.gz (18.6MB)
    100% |████████████████████████████████| 18.6MB 4.6kB/s 
Collecting matplotlib>=1.1.0 (from scikit-image)
  Downloading matplotlib-1.4.3.tar.gz (50.4MB)
    100% |████████████████████████████████| 50.4MB 2.1kB/s 
    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.3]
                    python: yes [2.7.4 (default, Sep 26 2013, 03:20:26)  [GCC
                            4.7.3]]
                  platform: yes [linux2]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.9.2]
                       six: yes [using six version 1.9.0]
                  dateutil: yes [using dateutil version 2.4.2]
                      pytz: yes [using pytz version 2015.2]
                   tornado: yes [using tornado version 4.1]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                     pycxx: yes [Couldn't import.  Using local copy.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: yes [version 1.2.49]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [using nose version 1.3.6 / mock is required to
                            run the matplotlib test suite.  pip/easy_install may
                            attempt to install it after matplotlib.]
            toolkits_tests: yes [using nose version 1.3.6 / mock is required to
                            run the matplotlib test suite.  pip/easy_install may
                            attempt to install it after matplotlib.]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PyQt4 not found]
                    pyside: no  [PySide not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                            found.  You may need to install the development
                            package.]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: yes [version 1.14]
               ghostscript: yes [version 9.07]
                     latex: yes [version 3.1415926]
                   pdftops: yes [version 0.20.5]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7i2UFS/matplotlib

```

**Comment by blink1073** [comment]
@ThunderShiviah, can you try using `conda install matplotlib`, which will install `freetype` for you in your environment?

**Comment by blink1073** [comment]
By the way, the conda equivalent of using `requirements.txt` is as follows:

```bash
$ conda list -e > req.txt
$ conda create -n my_test_environment --file req.txt
```

**Comment by ThunderShiviah** [comment]
Here's a follow up:

After re-installing the anaconda distro I still had the above mentioned issue with the six package as well as not being able to import matplotlib.pyplot. My solution was to go through each package that I found in the traceback (including six, numpy, scipy, and PyQt4) and check whether python was sourcing the package from anaconda or python2.7/dist-tools. 

If the package was in dist-tools, I would navigate to the dist-tools dir and run 
```
sudo apt-get remove package-name
sudo rm -rf package-name
```

That got my scikit-image library completely working.

I'm still not sure what broke it in the first place, but it seemed to be more of a matplotlib dependency issue.

Also thanks @blink1073  for the suggestion to use conda for my virtual environments. That makes my life much easier.

`

**Comment by blink1073** [comment]
@ThunderShiviah, glad to be of service.  Can we close this one?

**Comment by jthi3rry** [comment]
Installing in a pristine virtual env raises the error for me on ubuntu 14.04:
```
   Downloading scikit-image-0.11.3.tar.gz (18.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Hjx6BZ/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
```

This is an extract of my requirements.txt file:
```
...
numpy==1.9.2
scipy==0.15.1
pillow==2.8.1
pandas==0.16.1
scikit-learn==0.16.1
scikit-image==0.11.3
...
```

All works well if I comment out scikit-image, install the requirements, then uncomment  and install the requirements again. But it's not ideal as deployments on new VMs can't be automated.

**Comment by blink1073** [comment]
@ThunderShiviah, see #1606 for an attempted fix.

**Comment by blink1073** [comment]
err, @jthi3rry, too.  :smile:
