### ISSUE TITLE
Adding nitpicky option for non-functional API links

### ISSUE THREAD

**Issue by bsipocz** [scikit-image/scikit-image#1662]
I wonder whether there is any check for the resolvability of API links? In astropy and affiliates we use "nitpicky = True" in the docs/conf.py that causes the sphinx build fail on travis if an interspinx link is unresolved.
(e.g. https://github.com/astropy/astropy/pull/2508)

I couldn't tested this at the euroscipy sprint as was unable to build the docs.

**Comment by emmanuelle** [comment]
@bsipocz thanks for the tip. I recently found out that you need sphinx >= 1.3 to build scikit-image documentation, that might have been the reason why you couldn't build the doc. I've started using "nitpicky=True" and it's indeed very useful for finding broken links, thanks.

**Comment by bsipocz** [comment]
It's still not building with 1.3.3 (also I'm almost sure I had a fresh version or even the dev one during the euroscipy sprint).
Anyway, this is where it fails atm.:
```
[1/1] Cythonizing /Users/bsipocz/munka/devel/scikit-image/skimage/segmentation/_slic.pyx
running build_sphinx
creating /Users/bsipocz/munka/devel/scikit-image/build
creating /Users/bsipocz/munka/devel/scikit-image/build/sphinx
creating /Users/bsipocz/munka/devel/scikit-image/build/sphinx/doctrees
creating /Users/bsipocz/munka/devel/scikit-image/build/sphinx/html
Running Sphinx v1.3.3
/Users/bsipocz/munka/devel/scikit-image/skimage/external/tifffile/tifffile.py:156: UserWarning: failed to import the optional _tifffile C extension module.
Loading of some compressed images will be slow.
Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "failed to import the optional _tifffile C extension module.\n"
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    **extra
  File "/sw/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/sw/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/sw/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/sw/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/sw/lib/python2.7/site-packages/sphinx/setup_command.py", line 161, in run
    freshenv=self.fresh_env)
  File "/sw/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/sw/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension plot2rst (exception: cannot import name img_as_float)
```

#1813 seems to be an easy one to fix, I can open a PR for that if you like.

**Comment by emmanuelle** [comment]
@bsipocz that'd be awesome for #1813, thanks a lot! 

Sorry to hear that sphinx build still does not work. Does the test suite run without fails for you?

**Comment by bsipocz** [comment]
Well, I get loads of failures (33 fails, 4 errors, 5 warnings) which makes me wonder that there is something I missed when setting up the dev version. Do you have a docs page describing how to run tests and build the docs? I run both ``py.test`` and ``python setup.py test``. The log for the former is here: https://gist.github.com/bsipocz/50d5545f43f5be193ff5
Building the docs I tried ``python setup.py build_sphinx`` and also ``make html``.

**Comment by emmanuelle** [comment]
Hum, no specific doc page for this I'm afraid. I just run ``make test`` to run the tests, and ``make html`` in ``doc`` directory to build the doc.

**Comment by emmanuelle** [comment]
I think we rely too much on Travis for tests, I also have a few tests failing...

**Comment by bsipocz** [comment]
or not relying enough on it :)The ``scikit-image`` travis matrix seems very simple comparing to what we have in astropy and affiliates (e.g. we also test for cases when the optional deps are not installed, or for older numpys (or the dev version), testing the docs build, etc. and still there are always a few failing things for release candidates when many people start testing it on all kind of setups). 

Anyway, I'll try to make the docs build work tomorrow (also my idea for #1813 seems not working, but it would be nice to get to the point that I can actually test it).

**Comment by emmanuelle** [comment]
Wow, that's impressive. Even with our simple matrix as you call it :-), it already feels like ages before Travis build completes. 

Thanks for your perseverance!

**Comment by rfezzani** [comment]
Any update on this issue? Can it be closed?
