### ISSUE TITLE
Failing tests due to "jpeg encoder error"

### ISSUE THREAD

**Issue by ashkurti** [scikit-image/scikit-image#1664]
The errors are similar, I am pasting the messages just for one of the 3 tests that fail. 
I am trying looking around internet for a solution to this as well.
```
ERROR: skimage.io.tests.test_pil.test_jpg_quality_arg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "skimage/io/tests/test_pil.py", line 108, in test_jpg_quality_arg
    imsave(jpg, chessboard, quality=95)
  File "skimage/io/_io.py", line 122, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "skimage/io/manage_plugins.py", line 208, in call_plugin
    return func(*args, **kwargs)
  File "skimage/io/_plugins/pil_plugin.py", line 283, in imsave
    img.save(fname, format=format_str, **kwargs)
  File "/home/adminuser/.local/lib/python2.7/site-packages/PIL/Image.py", line 1703, in save
    save_handler(self, fp, filename)
  File "/home/adminuser/.local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 697, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/home/adminuser/.local/lib/python2.7/site-packages/PIL/ImageFile.py", line 492, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/home/adminuser/.local/lib/python2.7/site-packages/PIL/Image.py", line 437, in _getencoder
    raise IOError("encoder %s not available" % encoder_name)
IOError: encoder jpeg not available
```

**Comment by ashkurti** [comment]
Good news is that I solved it (bad news at the end :D). 

The steps I followed in case anyone encounters the same problem are the following (CentOS environment):
```
rm -rf /usr/lib/python2.7/site-packages/PIL
rm -rf /usr/lib/python2.7/site-packages/PIL.pth
yum install zlib zlib-devel
yum install libjpeg libjpeg-devel
yum install freetype freetype-devel
```
Then add the following to setup.py:
```
TCL_ROOT = '/usr/lib64'
JPEG_ROOT = '/usr/lib64'
ZLIB_ROOT = '/usr/lib64'
TIFF_ROOT = '/usr/lib64'
FREETYPE_ROOT = '/usr/lib64'
LCMS_ROOT = '/usr/lib64'
```
Then, reinstall everything and retry the tests:
```
pip install -r requirements.txt
pip install .
python setup.py develop
python setup.py build_ext -i
make test
```
All tests work apart from one that does not relate with this problem and that has been explained at #1668
