### ISSUE TITLE
All Travis 3.x builds failing

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1751]
For recent PRs, all Travis builds for Python 3.x are failing. This was limited to just Python 3.5, but now we're getting these three errors consistently for all 3.x branches. Seems related to fancy indexing, and I believe the rollout of NumPy 1.10 is correlated with their appearance.

``` python
======================================================================
ERROR: Test a grayscale float image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scikit-image/scikit-image/skimage/exposure/tests/test_exposure.py", line 218, in test_adapthist_grayscale
    adapted = exposure.equalize_adapthist(img, kernel_size=(57, 51), clip_limit=0.01, nbins=128)
  File "/opt/python/3.3.5/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/home/travis/build/scikit-image/scikit-image/skimage/_shared/_warnings.py", line 112, in expected_warnings
    raise ValueError('Unexpected warning: %s' % str(warn.message))
ValueError: Unexpected warning: boolean index did not match indexed array along dimension 0; dimension is 128 but corresponding boolean dimension is 127
======================================================================
ERROR: Test an RGB color uint16 image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scikit-image/scikit-image/skimage/exposure/tests/test_exposure.py", line 234, in test_adapthist_color
    adapted = exposure.equalize_adapthist(img, clip_limit=0.01)
  File "/opt/python/3.3.5/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/home/travis/build/scikit-image/scikit-image/skimage/_shared/_warnings.py", line 112, in expected_warnings
    raise ValueError('Unexpected warning: %s' % str(warn.message))
ValueError: Unexpected warning: boolean index did not match indexed array along dimension 0; dimension is 256 but corresponding boolean dimension is 86
======================================================================
ERROR: Test an RGBA color image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scikit-image/scikit-image/skimage/exposure/tests/test_exposure.py", line 253, in test_adapthist_alpha
    adapted = exposure.equalize_adapthist(img)
  File "/opt/python/3.3.5/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/home/travis/build/scikit-image/scikit-image/skimage/_shared/_warnings.py", line 112, in expected_warnings
    raise ValueError('Unexpected warning: %s' % str(warn.message))
ValueError: Unexpected warning: boolean index did not match indexed array along dimension 0; dimension is 256 but corresponding boolean dimension is 86
----------------------------------------------------------------------
```

**Comment by stefanv** [comment]
An actual bug that was caught.  Win!
