### ISSUE TITLE
threshold_otsu raises exception when image is one color

### ISSUE THREAD

**Issue by wolever** [scikit-image/scikit-image#1856]
Tested against current HEAD:

```pycon
>>> import numpy as np
>>> from skimage.filters import threshold_otsu
>>> threshold_otsu(np.array([1,2,3]))
1
>>> threshold_otsu(np.array([1,1,1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/skimage/filters/thresholding.py", line 140, in threshold_otsu
    idx = np.argmax(variance12)
  File "…/numpy/core/fromnumeric.py", line 968, in argmax
    return argmax(axis, out)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by JDWarner** [comment]
Thanks for the report. Looks like at minimum this should be caught and a more informative error raised.

**Comment by OrkoHunter** [comment]
@JDWarner I've created #1903 in favor of this. Please take a look at it.
