### ISSUE TITLE
test_keypoints_orb_desired_no_of_keypoints fails but skimage.test() passes

### ISSUE THREAD

**Issue by cgohlke** [scikit-image/scikit-image#1935]
See https://ci.appveyor.com/project/blink1073/scikit-image-qbl76/build/1.0.1019#L5834 and https://travis-ci.org/scikit-image/scikit-image/jobs/108000802#L1856

Without `@test_parallel()` decorator:

```
======================================================================
FAIL: skimage.feature.tests.test_orb.test_keypoints_orb_desired_no_of_keypoints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27-x64\lib\site-packages\skimage\feature\tests\test_orb.py", line 34, in test_keypoints_orb_desired_no_of_keypoints
    assert_almost_equal(exp_scales, detector_extractor.scales)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 497, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([ 323.   ,  328.   ,  282.24 ,  292.   ,  281.664,   85.   ,
        260.   ,  284.   ,  328.8  ,  267.   ])
 y: array([ 1.   ,  1.   ,  1.44 ,  1.   ,  1.728,  1.   ,  1.   ,  1.   ,
        1.2  ,  1.   ])
```

**Comment by soupault** [comment]
Closed via #1937 , #1982 .
