### ISSUE TITLE
Unable to build the development version 

### ISSUE THREAD

**Issue by lizsz** [scikit-image/scikit-image#1971]
The build process fails at : 

```
building 'skimage.morphology._skeletonize_3d_cy' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/core/include -I/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/core/include -I/opt/shared/python/2.7.6/include/python2.7 -c'
gcc: skimage/morphology/_skeletonize_3d_cy.c
skimage/morphology/_skeletonize_3d_cy.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
skimage/morphology/_skeletonize_3d_cy.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/core/include -I/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/core/include -I/opt/shared/python/2.7.6/include/python2.7 -c skimage/morphology/_skeletonize_3d_cy.c -o build/temp.linux-x86_64-2.7/skimage/morphology/_skeletonize_3d_cy.o" failed with exit status 1
```

**Comment by stefanv** [comment]
Please send us the output of Cython as well.

**Comment by stefanv** [comment]
(I.e., ``cython _skeletonize_3d_cy.pyx``)

**Comment by lizsz** [comment]
I do not think I have it. Attached is the full output
[skimage.log.txt](https://github.com/scikit-image/scikit-image/files/152049/skimage.log.txt)

**Comment by lizsz** [comment]
See below. I have also attached two files. One is  the output from 
>python setup.py build_ext -i

[skimage.log.txt](https://github.com/scikit-image/scikit-image/files/152051/skimage.log.txt)

and another one is a clean install after pulling sources from github via git clone ...


> pip install --user -e .

[skimage.clean.install.log.failed.txt](https://github.com/scikit-image/scikit-image/files/152061/skimage.clean.install.log.failed.txt)

This one probably:
```
    Cythonizing /src/scikit-image/skimage/morphology/_greyreconstruct.pyx
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            npy_intp p, r, c
            bint no_change
    
            list simple_border_points
            Py_ssize_t num_border_points, i, j
            (npy_intp, npy_intp, npy_intp) point
                    ^
    ------------------------------------------------------------
    
    skimage/morphology/_skeletonize_3d_cy.pyx:69:17: Expected ')', found ','
    Compiling /src/scikit-image/skimage/morphology/_skeletonize_3d_cy.pyx because it changed.
    Cythonizing /src/scikit-image/skimage/morphology/_skeletonize_3d_cy.pyx
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/src/scikit-image/setup.py", line 146, in <module>
        **extra
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/src/scikit-image/setup.py", line 69, in configuration
        config.add_subpackage('skimage')
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/setup.py", line 21, in configuration
        config.add_subpackage('morphology')
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/morphology/setup.py", line 19, in configuration
        cython(['_skeletonize_3d_cy.pyx.in'], working_path=base_path)
      File "skimage/_build.py", line 46, in cython
        cythonize(pyxfile)
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 840, in cythonize
        cythonize_one(*args[1:])
      File "/opt/shared/python/2.7.6/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: /src/scikit-image/skimage/morphology/_skeletonize_3d_cy.pyx
```

**Comment by jni** [comment]
@lizsz You may have an older version of Cython. What is the output of typing "cython --version" in the command line?

**Comment by lizsz** [comment]
I think it is 0.21.1 
typing cython --version resulted in the 
``` cython: command not found ```
However, I was able to import it to python (v 2.7.6) and call .__version__ which gave me 0.21.1

**Comment by JDWarner** [comment]
That may be the problem. In #1923 the Cython requirement was bumped to 0.23.4 on Travis in [this commit](https://github.com/scikit-image/scikit-image/commit/304660d287b73fbdbf000c599375b4293d4caba3). Try updating your Cython to or above 0.23.4 and trying again, @lizsz.

If that _does_ solve the problem, it looks like our human readable `requirements.txt` needs to be updated to reflect this - it still says 0.21.

**Comment by lizsz** [comment]
this did the trick. The install failed at first (in different place, though), but when I cleared and pulled it again from github, it compiled. Gentlemen, thank you for help!

**Comment by ev-br** [comment]
Apologies for making a mess and thanks for cleaning it up!
I was not sure what is(are) the definitive place(s) for specifying the cython version, and I missed this one here.
