### ISSUE TITLE
Denoise bilateral tests take disproportionately long to execute

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1993]

**Comment by cournape** [comment]
I see this especially on windows, where it looks like the test basically hangs (> 10 minutes and still runnning, compared to linux/osx where it only takes 2-3 mins to run the full test suite).

**Comment by soupault** [comment]
From AppVeyor logs:
```
[00:44:56] skimage.restoration.tests.test_denoise.test_denoise_bilateral_2d ... 
[00:46:59] ok
[00:46:59] skimage.restoration.tests.test_denoise.test_denoise_bilateral_color ... 
[00:52:04] ok
[00:52:04] skimage.restoration.tests.test_denoise.test_denoise_bilateral_3d_grayscale ... 
[00:52:04] ok
[00:52:04] skimage.restoration.tests.test_denoise.test_denoise_bilateral_3d_multichannel ... 
[00:52:06] ok
[00:52:06] skimage.restoration.tests.test_denoise.test_denoise_bilateral_multidimensional ... 
[00:52:06] ok
[00:52:06] skimage.restoration.tests.test_denoise.test_denoise_bilateral_nan ... 
[00:52:06] ok
```

**Comment by mangancha** [comment]
Same issue in Ubuntu 14.04

Running python test_denoise.py -v

======================================================================
ERROR: skimage.restoration.tests.test_denoise.test_nl_means_denoising_2d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/tests/test_denoise.py", line 247, in test_nl_means_denoising_2d
    denoised = restoration.denoise_nl_means(img, 7, 5, 0.2, fast_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/non_local_means.py", line 118, in denoise_nl_means
    patch_size, patch_distance, h)))
  File "skimage/restoration/_nl_means_denoising.pyx", line 193, in skimage.restoration._nl_means_denoising._nl_means_denoising_2d (skimage/restoration/_nl_means_denoising.c:3505)
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

======================================================================
ERROR: skimage.restoration.tests.test_denoise.test_denoise_nl_means_2drgb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/tests/test_denoise.py", line 261, in test_denoise_nl_means_2drgb
    denoised = restoration.denoise_nl_means(img, 7, 9, 0.3, fast_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/non_local_means.py", line 118, in denoise_nl_means
    patch_size, patch_distance, h)))
  File "skimage/restoration/_nl_means_denoising.pyx", line 193, in skimage.restoration._nl_means_denoising._nl_means_denoising_2d (skimage/restoration/_nl_means_denoising.c:3505)
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

======================================================================
ERROR: skimage.restoration.tests.test_denoise.test_denoise_nl_means_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/tests/test_denoise.py", line 275, in test_denoise_nl_means_3d
    multichannel=False)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/non_local_means.py", line 125, in denoise_nl_means
    patch_distance, h))
  File "skimage/restoration/_nl_means_denoising.pyx", line 299, in skimage.restoration._nl_means_denoising._nl_means_denoising_3d (skimage/restoration/_nl_means_denoising.c:4986)
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

======================================================================
ERROR: skimage.restoration.tests.test_denoise.test_no_denoising_for_small_h
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/tests/test_denoise.py", line 307, in test_no_denoising_for_small_h
    denoised = restoration.denoise_nl_means(img, 7, 5, 0.01, fast_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/skimage/restoration/non_local_means.py", line 118, in denoise_nl_means
    patch_size, patch_distance, h)))
  File "skimage/restoration/_nl_means_denoising.pyx", line 193, in skimage.restoration._nl_means_denoising._nl_means_denoising_2d (skimage/restoration/_nl_means_denoising.c:3505)
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

----------------------------------------------------------------------
Ran 24 tests in 87.439s

FAILED (errors=4)

**Comment by stefanv** [comment]
@mangancha I don't think that's the same error.  Also, are you running the latest version (0.12)?

**Comment by mangancha** [comment]
I am running 0.12.3. 

It might be the parameters that I used from your webpage.

denoise_bilateral(noisy, sigma_range=0.05, sigma_spatial=15))

I got a warning that sigma_range is about to be deprecated. Once I used sigma_range=None, it performed well.

Thanks and keep up the goos work!

Enviado desde mi iPhone

**Comment by kevin-coder** [comment]
@stefanv , I also encounter this issue, running but taking a long time on Windows. I will have a look at this issue.
Basic Test Environment:
Windows 8.1 + Python 2.7.10
