### ISSUE TITLE
`rank.autolevel` test failure on windows 64 bits

### ISSUE THREAD

**Issue by cournape** [scikit-image/scikit-image#1996]
I see this error on windows 64 bits w/ the release `0.12.3`:

```
======================================================================
FAIL: skimage.filters.rank.tests.test_rank.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
skimage\filters\rank\tests\test_rank.py", line 16, in test_all
    check_all()
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
skimage\_shared\testing.py", line 232, in inner
    result = func(*args, **kwargs)
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
skimage\filters\rank\tests\test_rank.py", line 27, in check_all
    rank.autolevel(image, selem))
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
numpy\testing\utils.py", line 275, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Users\vagrant\src\buildsystem-git\build\master-env\lib\site-packages\
numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 91.84%)
 x: array([[  0, 255,  37, 171,   8, 255,   0, 218, 255,  98, 255,   0,  25,
        249,   0,  49,   0, 255, 225, 165, 255, 195, 126, 255,   0],
       [255,   0, 241, 126, 168,  42, 255,  80, 148,   0, 196, 253,  31,...
 y: array([[255, 151, 222,  87,  27,   5, 112, 198,  67, 139, 255,   3,   0,
        192, 196, 212, 216, 255,   8, 120,   0, 255,  40, 255,   0],
       [  0, 164,  35,  20, 255,   0, 255,  50, 100, 255,   0, 255,   3,...

----------------------------------------------------------------------
Ran 1388 tests in 237.656s

FAILED (SKIP=65, failures=1)
```

Built against numpy `1.9.2`, scipy `0.17.0`, using the MKL `11.1.4`.

**Comment by soupault** [comment]
Reminds me of https://github.com/scikit-image/scikit-image/pull/1937#issuecomment-192468021 .

**Comment by cournape** [comment]
It does look similar. It could be a race condition ?

**Comment by soupault** [comment]
I have no idea yet.
@cournape which Python version are you using?

**Comment by cournape** [comment]
`2.7.6`.

**Comment by stefanv** [comment]
Sharp eyes, Egor. Thanks for reporting, David; if you run this test again,
does the same failure occur?

**Comment by JDWarner** [comment]
Indeed, Travis didn't reproduce this on the restarted build but it looks remarkably similar. 

I'd really like to see the failed test array, which might give us additional insight. That could be a challenge.

**Comment by cournape** [comment]
@stefanv I could reproduce it every time. Note that this is specific to windows in my case, never saw it on linux or mac os x.

**Comment by stefanv** [comment]
@cournape Do you have a Valgrind equivalent that you can run during
execution?
​

**Comment by stefanv** [comment]
@matthew-brett, can you reproduce this problem on your Windows buildbot?

**Comment by matthew-brett** [comment]
I can:

```
(skimage) PS C:\repos\scikit-image\dist> nosetests skimage.filters.rank.tests.test_rank
c:\repos\skimage\lib\site-packages\skimage\viewer\__init__.py:6: UserWarning: Viewer requires Qt
  warn('Viewer requires Qt')
c:\repos\skimage\lib\site-packages\skimage\filter\__init__.py:6: skimage_deprecation: The `skimage.filter` modul
ed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\repos\skimage\lib\site-packages\skimage\filters\rank\tests\test_rank.py", line 27, in check_all
    rank.autolevel(image, selem))
  File "c:\Python27\lib\site-packages\numpy\testing\utils.py", line 275, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "c:\Python27\lib\site-packages\numpy\testing\utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "c:\Python27\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 91.84%)
 x: array([[  0, 255,  37, 171,   8, 255,   0, 218, 255,  98, 255,   0,  25,
        249,   0,  49,   0, 255, 225, 165, 255, 195, 126, 255,   0],
       [255,   0, 241, 126, 168,  42, 255,  80, 148,   0, 196, 253,  31,...
 y: array([[255, 151, 222,  87,  27,   5, 112, 198,  67, 139, 255,   3,   0,
        192, 196, 212, 216, 255,   8, 120,   0, 255,  40, 255,   0],
       [  0, 164,  35,  20, 255,   0, 255,  50, 100, 255,   0, 255,   3,...

..............................
----------------------------------------------------------------------
Ran 30 tests in 7.875s

OK
```

**Comment by JDWarner** [comment]
Just got this on a master build in Python 2.6 (after a clean and completely unrelated PR branch build) which I'm not restarting so we can reference it here: https://travis-ci.org/scikit-image/scikit-image/builds/115367775

**Comment by hmaarrfk** [comment]
probably.
