### ISSUE TITLE
Requirement of cython 2.3

### ISSUE THREAD

**Issue by vodp** [scikit-image/scikit-image#2025]
Recently I install scikit-image with the command `pip install -U scikit-image` but failed due to requirement of Cython 0.23.
```
Downloading/unpacking scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
  Running setup.py (path:/tmp/pip_build_pateheo/scikit-image/setup.py) egg_info for package scikit-image
    Partial import of skimage during the build process.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_pateheo/scikit-image/setup.py", line 146, in <module>
        **extra
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip_build_pateheo/scikit-image/setup.py", line 69, in configuration
        config.add_subpackage('skimage')
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/setup.py", line 9, in configuration
        config.add_subpackage('_shared')
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/_shared/setup.py", line 16, in configuration
        cython(['geometry.pyx'], working_path=base_path)
      File "skimage/_build.py", line 30, in cython
        raise RuntimeError('Cython >= 0.23 needed to build scikit-image')
    RuntimeError: Cython >= 0.23 needed to build scikit-image
    Complete output from command python setup.py egg_info:
    Partial import of skimage during the build process.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_pateheo/scikit-image/setup.py", line 146, in <module>

    **extra

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup

    config = configuration()

  File "/tmp/pip_build_pateheo/scikit-image/setup.py", line 69, in configuration

    config.add_subpackage('skimage')

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "skimage/setup.py", line 9, in configuration

    config.add_subpackage('_shared')

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "skimage/_shared/setup.py", line 16, in configuration

    cython(['geometry.pyx'], working_path=base_path)

  File "skimage/_build.py", line 30, in cython

    raise RuntimeError('Cython >= 0.23 needed to build scikit-image')

RuntimeError: Cython >= 0.23 needed to build scikit-image

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_pateheo/scikit-image
Storing debug log for failure in /home/pateheo/.pip/pip.log
```

I have tried to install cython from `Cython version 0.20.1post0` to 0.23 and higher but could not do it. All of the ways `pip install cython`, or download cython and build from source, I always get `cython --version' equals `Cython version 0.20.1post0`. However if I try `pip show cython` then it shows 
```
---
Name: Cython
Version: 0.23.5
Location: /usr/local/lib/python2.7/dist-packages/Cython-0.23.5-py2.7-linux-x86_64.egg
Requires: 
```

This may seem the problem of cython, not scikit-image, but do you encounter similar cases as mine?

**Comment by JDWarner** [comment]
This sounds like a problem with your system PATH. If you run `which cython`, you will likely find there is another Cython installation around which precedes your pip installed version. Tweaking the PATH or uninstalling that one are the best options.

**Comment by meanmee** [comment]
Ｉ have the same problem, Who can help? Thx a lot

**Comment by soupault** [comment]
@meanmee I highly recommend you to start with @JDWarner suggestion: paste here the output of `which cython` and (if possible) `echo $PATH`.

**Comment by meanmee** [comment]
@soupault @JDWarner I am not very fimiliar with Linux, Here are my outputs of `which cython` and `echo $PATH`:

dell@dell-Precision-Tower-7910:~/Cython-0.24b0$ which cython
/usr/local/bin/cython
dell@dell-Precision-Tower-7910:~/Cython-0.24b0$ echo $PATH
/home/dell/src/torch/install/bin:/home/dell/.luarocks/bin:/home/dell/src/torch/install/bin:/usr/local/cuda-7.5/bin:/usr/lib/jvm/jdk1.8.0_65/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

So, What should I do next?

**Comment by meanmee** [comment]
It seems like there are two versions of Cython in my Computer, one by apt-get, another by pip. So i just  
use the command below：
‘’‘
sudo apt-get autoremove cython
'''
Then there is only left the version of pip

**Comment by JDWarner** [comment]
Closing as resolved - solution above worked as expected.

**Comment by vodp** [comment]
Thanks. The solution is to remove completely cython and its dependencies. Sometimes pip uninstall cython is not enough. After doing that, reinstall cython will work!

**Comment by alexpghayes** [comment]
Following up with a newbie question here: I'm running into the same issue on a server that I don't have admin privileges on.

I can install Cython locally into a .pip folder for my project (following the advice [here](https://www.zoomeranalytics.com/blog/pip-install-t)), and then I get

```
$ pip install Cython -t .pip
$ python ./.pip/cython.py --version
Cython version 0.25.2
```

I've added `./.pip` to the beginning of my PYTHONPATH, but when I try to install scikit-image I get

```
$ pip install --user scikit-image
...
RuntimeError: Cython >= 0.23 needed to build scikit-image
```

Similarly,

```
$ which Cython
/opt/apps/software/MPI/GCC/4.8.3/OpenMPI/1.8.8/Python/2.7.9/bin/cython
```

How can I tell the pip installation to use the version of Cython sitting in `my_project/.pip'?

**Comment by jni** [comment]
Hi @alexpghayes! I don't know exactly what's going wrong with your path. In addition to your PYTHONPATH, you may need to prepend a subdirectory of .pip to your PATH. (PYTHONPATH is only used for `import` statements in Python, not for shell calls.)

My recommendation would be to install miniconda in your home dir and make a conda environment for this purpose. Although the author of that blog post says they're overkill, in my opinion they greatly simplify path and dependency management.

**Comment by alexpghayes** [comment]
Figured it out! When I loaded Python on the cluster I was using, the module loader was loading the older version of Cython into `sys.path` way above anything I could add. 

The solution was to use a `virtualenv` and `pip install` my requirements into the virtualenv, after which I could call `/path/to/virtualenv/python my_file.py`. Leaving this here in case it helps out somebody else.

**Comment by ntbk1919** [comment]
if youre doing inside miniconda env pip install Cython there
