### ISSUE TITLE
qt_plugin.py: ImportError: cannot import name 'warn'

### ISSUE THREAD

**Issue by klonuo** [scikit-image/scikit-image#2069]
Trying to run skivi raises this Exception:
``` python
Traceback (most recent call last):
  File "C:\Python35\Scripts\skivi-script.py", line 9, in <module>
    load_entry_point('scikit-image==0.12.3', 'console_scripts', 'skivi')()
  File "c:\python35\lib\site-packages\skimage\scripts\skivi.py", line 12, in main
    io.use_plugin('qt')
  File "c:\python35\lib\site-packages\skimage\io\manage_plugins.py", line 255, in use_plugin
    _load(name)
  File "c:\python35\lib\site-packages\skimage\io\manage_plugins.py", line 299, in _load
    fromlist=[modname])
  File "c:\python35\lib\site-packages\skimage\io\_plugins\qt_plugin.py", line 1, in <module>
    from ..._shared import warn
ImportError: cannot import name 'warn'
```

So changing `from ..._shared import warn` into `from ..._shared.utils import warn` resolved the issue.

**Comment by soupault** [comment]
@klonuo thank you for reporting!
There is indeed a bug in imports block. Would you like to to submit a PR?

**Comment by klonuo** [comment]
It's a small typo, so I didn't make PR, as it would be much simpler for someone already contributing ;)

Cheers
