### ISSUE TITLE
matplotlib error when trying to open image in ImageViewer

### ISSUE THREAD

**Issue by ChrisK91** [scikit-image/scikit-image#2094]
## Description

For testing purposes, I'm trying to display an image in the ImageViewer. The image won't display (neither as png nor as tiff), and the error `ValueError: 'box_aspect' and 'fig_aspect' must be positive` is displayed.

```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 176, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "D:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "D:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1159, in draw
    func(*args)
  File "D:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2223, in draw
    self.apply_aspect()
  File "D:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1359, in apply_aspect
    pb1 = pb.shrunk_to_aspect(box_aspect, pb, fig_aspect)
  File "D:\Anaconda3\lib\site-packages\matplotlib\transforms.py", line 600, in shrunk_to_aspect
    raise ValueError("'box_aspect' and 'fig_aspect' must be positive")
```
## Way to reproduce

Copy both images to the working directory. Create the following script and run it

```
from skimage.io import imread
from skimage.viewer import ImageViewer

image = imread("sample1.tif")
viewer = ImageViewer(image)
viewer.show()
```

The same error occurs, when I try to open the image in an existing instance of ImageViewer (via File -> Open)

OS:
- Windows 10 x64
- `python --version`: `Python 3.5.1 :: Anaconda 4.0.0 (64-bit)`
- `skimage.__version__`: `'0.12.3'`

[images.zip](https://github.com/scikit-image/scikit-image/files/272651/images.zip)
![sample1](https://cloud.githubusercontent.com/assets/1904175/15395247/3e1e0e68-1dd7-11e6-9132-e44a1a8a7113.png)

**Comment by soupault** [comment]
I can open the image on my setup, but the same error is raised (nonetheless it works without any issues).

Win7 x64, Python 3.5, skimage 0.12.3.

**Comment by sciunto** [comment]
I can open each image and no error on my system.
python 3.5.1 or 2.7.11, GNU/Linux.

@soupault Do you have the same backtrace?

Looks like a backend issue anyway. Maybe @tacaswell has an idea or knows some similar issues.

**Comment by soupault** [comment]
Same behaviour Linux x64, Python 3.5, skimage 0.12.3.
Here is the traceback:
```
In [5]: viewer.show()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py in __draw_idle_agg(self, *args)
    174     def __draw_idle_agg(self, *args):
    175         try:
--> 176             FigureCanvasAgg.draw(self)
    177             self.update()
    178         finally:

/usr/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    472 
    473         try:
--> 474             self.figure.draw(self.renderer)
    475         finally:
    476             RendererAgg.lock.release()

/usr/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/usr/lib/python3.5/site-packages/matplotlib/figure.py in draw(self, renderer)
   1157         dsu.sort(key=itemgetter(0))
   1158         for zorder, a, func, args in dsu:
-> 1159             func(*args)
   1160 
   1161         renderer.close_group('figure')

/usr/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/usr/lib/python3.5/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2221             self.apply_aspect(pos)
   2222         else:
-> 2223             self.apply_aspect()
   2224 
   2225         artists = self.get_children()

/usr/lib/python3.5/site-packages/matplotlib/axes/_base.py in apply_aspect(self, position)
   1357                 box_aspect = A * self.get_data_ratio()
   1358             pb = position.frozen()
-> 1359             pb1 = pb.shrunk_to_aspect(box_aspect, pb, fig_aspect)
   1360             self.set_position(pb1.anchored(self.get_anchor(), pb), 'active')
   1361             return

/usr/lib/python3.5/site-packages/matplotlib/transforms.py in shrunk_to_aspect(self, box_aspect, container, fig_aspect)
    598         """
    599         if box_aspect <= 0 or fig_aspect <= 0:
--> 600             raise ValueError("'box_aspect' and 'fig_aspect' must be positive")
    601         if container is None:
    602             container = self

ValueError: 'box_aspect' and 'fig_aspect' must be positive
Out[5]: []
```

**Comment by tacaswell** [comment]
It smells like there is a race condition someplace and the first draw is
being triggered before all of the artists are set up fully but i have not
tried to debug this.

**Comment by stefanv** [comment]
If anything, this is a bug in matplotlib.  Thanks for reporting; I see @tacaswell took note.  Closing.

**Comment by tacaswell** [comment]
Does not mean I _did_ anything about it....
