### ISSUE TITLE
manylinux1 wheels compiled against too new numpy version

### ISSUE THREAD

**Issue by letmaik** [scikit-image/scikit-image#2108]
scikit-image claims to require numpy >= 1.7.2. However, for scikit-image 0.12.3 the manylinux1 wheels were built against a newer numpy. This then leads to runtime errors like "ValueError: numpy.dtype has the wrong size, try recompiling" or "RuntimeError: module compiled against API version 9 but this version of numpy is 7". I tested this against the x64 wheels in Python 2.7, 3.3., 3.4, and 3.5 with numpy 1.7.2. It fails for all those versions except 3.4, which is a bit weird, so I assume this particular wheel was built against an older numpy.

As a proof, have a look at this build log: https://travis-ci.org/neothemachine/rawpy/jobs/132485700#L1660 This is for building my own manylinux1 wheels for my own library in a docker container, so maybe you want to test this in a simpler setup, just installing an old numpy version and trying to install and run scikit-image from a manylinux1 wheel in different Python versions.

**Comment by stefanv** [comment]
I built the wheel against the first version of numpy for which a manylinux wheel is available on PyPi.  I'm not sure PyPi will allow me to re-upload a file with the same name, so may have to make a point release to fix this.

**Comment by matthew-brett** [comment]
There's a pypi wheel for numpy 1.7.2 - maybe there was none at the time though.

You may be able to get away with adding a build number to the wheel filename - see https://www.python.org/dev/peps/pep-0425/ and look for "build tag".

I don't think anyone's tested it yet, so maybe try rebuilding and uploading as e.g. `scikit_image-0.12.3-2-cp27-cp27mu-manylinux1_x86_64.whl` might work - worth a try?

**Comment by matthew-brett** [comment]
I see from the pip source that pip doesn't do anything with the build tags : https://github.com/pypa/pip/blob/master/tests/unit/test_wheel.py#L111 .  I guess then it will come down to sorting whether pip installs the wheel with the build tag compared to the wheel without, and you may need to delete the old untagged wheel file to be able to install new one.

**Comment by bmorris3** [comment]
I'm not sure if this is a related issue, but I'm trying to build docs for a [package](https://github.com/bmorris3/shampoo) of mine, and I'm having trouble building docs on Read The Docs due to tifffile via scikit-image, which has a similar error message: 

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 549, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 105, in <module>
    __import__(setup_cfg['package_name'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev120-py2.7.egg/shampoo/__init__.py", line 8, in <module>
    from .reconstruction import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev120-py2.7.egg/shampoo/reconstruction.py", line 19, in <module>
    from .vis import save_scaled_image
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev120-py2.7.egg/shampoo/vis.py", line 5, in <module>
    from skimage.io import imsave
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9
The full traceback has been saved in /tmp/sphinx-err-zPPK_b.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Segmentation fault
```

[Here's the build](https://readthedocs.org/projects/shampoo/builds/4238947/).

**Comment by matthew-brett** [comment]
Stefan - I have now tested the so-called "build tag" on pypi, and it works : 

https://github.com/h5py/h5py/issues/731#issuecomment-230826012

I just took the liberty of triggering a rebuild of the scikit-image wheels via the building repo.  

If these are builds work, and are acceptable, I can add the build tag (`1`) so you can upload them to pypi.  Does that sound feasible?

**Comment by matthew-brett** [comment]
Builds OK apart from the previous 32-bit failures : https://travis-ci.org/scikit-image/scikit-image-wheels/builds/147798529

I can upload the wheels with the added build tag, if you like.

**Comment by stefanv** [comment]
@matthew-brett Yes, please, that'd be fantastic.

**Comment by matthew-brett** [comment]
OK - done.  @bmorris3 - try your build again - does it work?

**Comment by bmorris3** [comment]
I'm still seeing the same issue. @bsipocz and I are experimenting with using the conda install rather than pip.

**Comment by matthew-brett** [comment]
Hum - can you find where `scikit_image` is installed?  I can only find a line saying that the requirements is already satisfied.  Is this a caching issue on the readthedocs side?

**Comment by bmorris3** [comment]
It was being installed with pip, and we solved the problem by switching to installing it via conda.

**Comment by matthew-brett** [comment]
Sure - but I am guessing that a fresh install with pip would also have worked.  It was not clear to me where in your build logs scikit-image was coming from, and I suspect it was being cached, hence the continued error after updating pypi.
