### ISSUE TITLE
testsuite fails on Big Endian Archs.

### ISSUE THREAD

**Issue by LocutusOfBorg** [scikit-image/scikit-image#2120]
powerpc, and s390x are having a testsuite failure
https://buildd.debian.org/status/package.php?p=skimage&suite=unstable
seems an endianess sadness issue (NOTE: I didn't check this, I'm only guessing because it fails on all BE architectures).
```
======================================================================
FAIL: skimage.io.tests.test_pil.test_all_mono
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/tests/test_pil.py", line 220, in test_all_mono
    mono_check('pil')
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/skimage/_shared/testing.py", line 176, in mono_check
    testing.assert_allclose(r4, img_as_uint(img4))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 737, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 50.3448486328%)
 x: array([[29812, 29812, 31354, ..., 23645, 24672, 24672],
       [29812, 29812, 31354, ..., 23645, 24672, 24672],
       [29812, 29812, 31354, ..., 23645, 24672, 24672],...
 y: array([[29812, 29812, 31354, ..., 23900, 24672, 24672],
       [29812, 29812, 31354, ..., 23900, 24672, 24672],
       [29812, 29812, 31354, ..., 23900, 24672, 24672],...
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
PIL.PngImagePlugin: DEBUG: STREAM pHYs 41 9
PIL.PngImagePlugin: DEBUG: STREAM vpAg 62 9
PIL.PngImagePlugin: DEBUG: vpAg 62 9 (unknown)
PIL.PngImagePlugin: DEBUG: STREAM IDAT 83 32768
PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 44189
PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 2414
PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 55702
PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 65536
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1383 tests in 328.278s

FAILED (SKIP=54, failures=1)
gram) = 0.0218803320738
delta (1 iteration) = 0.0270287245737
delta (1 iteration) = 0.0270287245737
delta (2 iterations) = 0.0232331483658
delta (2 iterations) = 0.0232331483658
delta (1 iteration, clip) = 0.0248932960634
delta (1 iteration, clip) = 0.0248932960634
delta (1 iteration, shifted sinogram) = 0.0293641116974
delta (1 iteration, shifted sinogram) = 0.0293641116974

	argmax of circle: (16, 0)
	argmax of square: (26, 0)
	argmax of circle to square: (26, 0)
0.0540346850989 2.56600451074

	argmax of circle: (18, 18)
	argmax of square: (29, 18)
	argmax of circle to square: (29, 18)
0.00038362409814 0.0956193976186
(61, 61)
(61, 61)
(61, 61)
(61, 61)
(79, 79)
(79, 79)
(97, 97)
(97, 97)
(61, 61)
(61, 61)
(61, 61)
(61, 61)
(79, 79)
(79, 79)
(97, 97)
(97, 97)
debian/rules:59: recipe for target 'python-test2' failed
make[1]: *** [python-test2] Error 1
make[1]: Leaving directory '/«PKGBUILDDIR»'
debian/rules:25: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-arch gave error exit status 2
```

**Comment by soupault** [comment]
Do we even state to support those platforms? :older_man:
And how many users of those are actually using `skimage`?

**Comment by LocutusOfBorg** [comment]
Hi, sorry but I don't have any per-arch numbers, but I guess considering also Ubuntu it might be a considerable userbase.

**Comment by CDLuminate** [comment]
Maybe this is not arch-specific. There is positive history that skimage compiles on s390x and powerpc.

https://buildd.debian.org/status/logs.php?pkg=skimage&arch=s390x
https://buildd.debian.org/status/logs.php?pkg=skimage&arch=powerpc
