### ISSUE TITLE
`StopIteration` when calling `img_as_float` on small RGB int image

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#2137]
## Description

Attempting to call `img_to_float` on a small RGB `int` image raises a `StopIteration` error. 

## Way to reproduce
```
import skimage.util 
import numpy as np

I = np.array([
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
    ]).transpose([1,2,0])

I2 = skimage.util.img_as_float(I)
```
produces: 
```
/usr/local/lib/python3.4/dist-packages/skimage/util/dtype.py:110: UserWarning: Possible precision loss when converting from int64 to float64
  "%s to %s" % (dtypeobj_in, dtypeobj))
Traceback (most recent call last):
  File "test_new_issue_image_as_float.py", line 49, in <module>
    I2 = skimage.util.img_as_float(I)
  File "/usr/local/lib/python3.4/dist-packages/skimage/util/dtype.py", line 301, in img_as_float
    return convert(image, np.float64, force_copy)
  File "/usr/local/lib/python3.4/dist-packages/skimage/util/dtype.py", line 241, in convert
    np.float32, np.float64))
  File "/usr/local/lib/python3.4/dist-packages/skimage/util/dtype.py", line 114, in _dtype
    return next(dt for dt in dtypes if itemsize < np.dtype(dt).itemsize)
StopIteration
```

**Comment by soupault** [comment]
In my environment (Python 3.5, numpy 1.11.0, skimage 0.12.3) happens only if `I.dtype` is in `(np.uint64, np.int64)`.

**Comment by soupault** [comment]
@jmetz see http://scikit-image.org/docs/stable/user_guide/data_types.html :
`With a few exceptions, 64-bit (u)int images are not supported.`

**Comment by jmetz** [comment]
Fair enough - apologies, assumed all standard `numpy` dtypes would be supported. Cheers!
