### ISSUE TITLE
AppVeyor builds fail because of missing `_fblas`

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2207]
## Description
AppVeyor builds started to fail (for a different reason :smiley:) since https://ci.appveyor.com/project/stefanv/scikit-image-1w3sk/build/1.0.461.

Error output:
```
...
    Found link http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com//scipy-0.14.0-cp27-none-win32.whl (from http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com/appveyor_pip_index.html), version: 0.14.0
  Using version 0.14.0 (newest of versions: 0.14.0)
  "GET //scipy-0.14.0-cp27-none-win32.whl HTTP/1.1" 200 39806196
  Downloading http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com//scipy-0.14.0-cp27-none-win32.whl (39.8MB)
  Downloading from URL http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com//scipy-0.14.0-cp27-none-win32.whl (from http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com/appveyor_pip_index.html)
...
Installing collected packages: numpy, scipy, cython, pytz, pyparsing, six, python-dateutil, matplotlib, pillow, nose
Successfully installed cython-0.24.1 matplotlib-1.4.2 nose-1.3.7 numpy-1.11.1 pillow-2.6.1 pyparsing-2.1.5 python-dateutil-2.5.3 pytz-2016.6.1 scipy-0.14.0 six-1.10.0
...
Traceback (most recent call last):
  File "tools/build_modref_templates.py", line 56, in <module>
    docwriter.write_api_docs(outdir)
  File "C:\projects\scikit-image-1w3sk\doc\tools\apigen.py", line 426, in write_api_docs
    self.write_modules_api(modules,outdir)
  File "C:\projects\scikit-image-1w3sk\doc\tools\apigen.py", line 393, in write_modules_api
    api_str = self.generate_api_doc(m)
  File "C:\projects\scikit-image-1w3sk\doc\tools\apigen.py", line 261, in generate_api_doc
    functions, classes = self._parse_module_with_import(uri)
  File "C:\projects\scikit-image-1w3sk\doc\tools\apigen.py", line 203, in _parse_module_with_import
    mod = __import__(uri, fromlist=[uri.split('.')[-1]])
  File "C:\Python27_32\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Python27_32\lib\site-packages\skimage\color\colorconv.py", line 59, in <module>
    from scipy import linalg
  File "C:\Python27_32\lib\site-packages\scipy\linalg\__init__.py", line 159, in <module>
    from .misc import *
  File "C:\Python27_32\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from . import blas
  File "C:\Python27_32\lib\site-packages\scipy\linalg\blas.py", line 145, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.
Running Sphinx v1.4.5
making output directory...
loading pickled environment... not yet created
plotting code blocks in ..\examples\color_exposure\plot_adapt_rgb.py
________________________________________________________________________________
..\examples\color_exposure\plot_adapt_rgb.py is not compiling:
Traceback (most recent call last):
  File "C:\projects\scikit-image-1w3sk\doc\source\..\ext\sphinx_gallery\gen_rst.py", line 498, in execute_script
    exec(code_block, example_globals)
  File "<string>", line 1, in <module>
  File "c:\python27_32\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "c:\python27_32\lib\site-packages\skimage\color\colorconv.py", line 59, in <module>
    from scipy import linalg
  File "c:\python27_32\lib\site-packages\scipy\linalg\__init__.py", line 159, in <module>
    from .misc import *
  File "c:\python27_32\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from . import blas
  File "c:\python27_32\lib\site-packages\scipy\linalg\blas.py", line 145, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.
...
...
skimage.external.test_tifffile.test_extension ... ok
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (cannot import name _ni_support) ... ERROR
Failure: ImportError (cannot import name _ni_support) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (cannot import name _ni_support) ... ERROR
Failure: ImportError (cannot import name _ni_support) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
Failure: ImportError (DLL load failed: The specified module could not be found.) ... ERROR
======================================================================
ERROR: Failure: ImportError (DLL load failed: The specified module could not be found.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python27_32\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27_32\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python27_32\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Python27_32\lib\site-packages\skimage\color\colorconv.py", line 59, in <module>
    from scipy import linalg
  File "C:\Python27_32\lib\site-packages\scipy\linalg\__init__.py", line 159, in <module>
    from .misc import *
  File "C:\Python27_32\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from . import blas
  File "C:\Python27_32\lib\site-packages\scipy\linalg\blas.py", line 145, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.
...
******************************** AND SO ON *******************************
```

**Comment by almarklein** [comment]
This looks similar to https://github.com/matplotlib/matplotlib/issues/6115, though there the error seemed related to numpy's multiarray. The solution proposed there is to explicitly install `msvc_runtime`. See e.g. https://github.com/pydy/pydy/pull/354 and https://github.com/imageio/imageio/pull/159. It is not entirely clear to me whether this fixed it for MPL, but it did for imageio.
