### ISSUE TITLE
Build error in Ubuntu 14.04

### ISSUE THREAD

**Issue by chenboheng** [scikit-image/scikit-image#2322]
When I build the skimage from the source.
I first successfully run pip install -r requirements.txt.
Then I run pip install -e .
some errors happen:

```
chenboheng@chenboheng:/media/ResearchProject/python_code/scikit-image$ sudo pip install .
Unpacking /media/ResearchProject/python_code/scikit-image
  Running setup.py (path:/tmp/pip-6UgGEd-build/setup.py) egg_info for package from file:///media/ResearchProject/python_code/scikit-image
    Partial import of skimage during the build process.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-6UgGEd-build/setup.py", line 149, in <module>
        **extra
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-6UgGEd-build/setup.py", line 69, in configuration
        config.add_subpackage('skimage')
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/setup.py", line 9, in configuration
        config.add_subpackage('_shared')
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/_shared/setup.py", line 16, in configuration
        cython(['geometry.pyx'], working_path=base_path)
      File "skimage/_build.py", line 30, in cython
        raise RuntimeError('Cython >= 0.23 needed to build scikit-image')
    RuntimeError: Cython >= 0.23 needed to build scikit-image
    Complete output from command python setup.py egg_info:
    Partial import of skimage during the build process.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-6UgGEd-build/setup.py", line 149, in <module>

    **extra

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup

    config = configuration()

  File "/tmp/pip-6UgGEd-build/setup.py", line 69, in configuration

    config.add_subpackage('skimage')

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "skimage/setup.py", line 9, in configuration

    config.add_subpackage('_shared')

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "skimage/_shared/setup.py", line 16, in configuration

    cython(['geometry.pyx'], working_path=base_path)

  File "skimage/_build.py", line 30, in cython

    raise RuntimeError('Cython >= 0.23 needed to build scikit-image')

RuntimeError: Cython >= 0.23 needed to build scikit-image

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-6UgGEd-build
Storing debug log for failure in /home/chenboheng/.pip/pip.log
```

How can I solve this problem? The OS is Ubuntu 14.04 . skimage is 0.12.3

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/pull/2036

**Comment by soupault** [comment]
@chenboheng Hi! Have you tried to install Cython first (i.e. `pip install cython`)?

**Comment by chenboheng** [comment]
@soupault Yes， and cython -V
Cython version 0.24.1

**Comment by chenboheng** [comment]
@soupault I replaced to skimage 0.10 . And I can build the skiamge successfully. Maybe there is some problems in version 0.12.3

**Comment by soupault** [comment]
@chenboheng can you just `pip install scikit-image` from web, not local folder?

**Comment by chenboheng** [comment]
@soupault  Yes. In Ubuntu 14.04 . Using pip install scikit-image only can install version 0.9.3. But I need skimage.restoration model to complete my code. And I use version 0.10 now, the code runs normally.

**Comment by catalintucureanu** [comment]
can confirm the same error in CentOS 6.5 using python 2.7.2 (works with version <= 0.1)

**Comment by jmetz** [comment]
Is there a chance that this is due to multiple Cython versions... I had an issue like this before that and that was the problem then. Despite `cython -V`  showing the correct version, when Cython get's imported for the build internally it imports an older version. 
I'd suggest checking `/usr/lib/python2.7` and `/usr/local/lib/python2.7`... you might find both contain Cython (possibly in `site-packages`).

**Comment by xor007** [comment]
Same thing happened to me in an anaconda environment from current snapshot today on 31st March.

**Comment by AliAshrafRagab** [comment]
it worked for me when i removed cython , i think that was 2 versions installed 
pip uninstall cython

**Comment by hmaarrfk** [comment]
I'm going to close this since it seems that the original issue is quite old. Hopefully the suggestions there can help people in installing scikit-image.
