### ISSUE TITLE
can't install skimage (error code 1)

### ISSUE THREAD

**Issue by PedroBarcha** [scikit-image/scikit-image#2387]
Hi there, I have successfully installed skimage with apt-get install, however I couldn't import skimage.restoration in my codes. I then realized that maybe the reason was that skimage's version from mint's 17.3 repository was too old  (0.9.3-4).
Than I unnistaled it and tried to build it from source, but it didn't work.
When I run `pip install -r requirements.txt` ,
I get the following error:

----------------------------------------
```
  Can't roll back numpy; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_user/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ZyC11D-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_user/numpy
```

However, this is really strange, because I DO have numpy (v1.8.2) installed (and working).
And then when I run `pip install .` ,
I get:
```
Command python setup.py egg_info failed with error code 1 in /tmp/pip-sH0dtw-build
Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by JDWarner** [comment]
In the dev branch we now depend on a newer version of NumPy, which is probably what is going on here.  Please update to the latest stable release of NumPy and try again.

**Comment by PedroBarcha** [comment]
I have successfully installed the latest numpy version. 
So, I ran `pip install -r requirements.txt` once again and got no errors this time.
But for `pip install .` , I got:
```
------------------------------------------------------------
/usr/bin/pip run on Wed Nov 30 23:25:07 2016
Unpacking /home/banshee/scikit-image-master
  Running setup.py (path:/tmp/pip-4vAyKx-build/setup.py) egg_info for package from file:///home/banshee/scikit-image-master
    Unable to find pgen, not compiling formal grammar.
    No eggs found in /tmp/easy_install-gecVpc/Cython-0.25.1/egg-dist-tmp-Ej4y52 (setup script problem?)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-4vAyKx-build/setup.py", line 149, in <module>
        **extra
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup
        dist = setup(**new_attr)
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

No eggs found in /tmp/easy_install-gecVpc/Cython-0.25.1/egg-dist-tmp-Ej4y52 (setup script problem?)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-4vAyKx-build/setup.py", line 149, in <module>

    **extra

  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup

    dist = setup(**new_attr)

  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup

    return old_setup(**new_attr)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__

    Distribution.__init__(self, attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: cython>=0.21

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-4vAyKx-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-4vAyKx-build

```

**Comment by JDWarner** [comment]
Python tries to be informative when it throws error messages.  It's telling you exactly what it needs.  Look at the bottom of the traceback and see 

`DistributionNotFound: cython>=0.21` 

Does this error make sense to you?

**Comment by JDWarner** [comment]
Closing as resolved - ensure the proper dependencies are present and up to date.
