### ISSUE TITLE
DeprecationWarning for inspect.getargspec() in Python 3.5

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2414]
While reading https://github.com/numpy/numpy/issues/8413#issuecomment-269048456 for https://github.com/scikit-image/scikit-image/issues/2412

I ran

python skimage/transform/tests/test_integral.py

and I got (2nd failure):

```
======================================================================
ERROR: test suite for <module 'skimage.transform.tests.test_integral' from '/home/fr/github/scikit-image/skimage/transform/tests/test_integral.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/.local/share/virtualenvs/sk/lib/python3.5/site-packages/nose/suite.py", line 229, in run
    self.tearDown()
  File "/home/fr/.local/share/virtualenvs/sk/lib/python3.5/site-packages/nose/suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "/home/fr/.local/share/virtualenvs/sk/lib/python3.5/site-packages/nose/suite.py", line 368, in teardownContext
    try_run(context, names)
  File "/home/fr/.local/share/virtualenvs/sk/lib/python3.5/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
  File "/usr/lib64/python3.5/inspect.py", line 1041, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

----------------------------------------------------------------------

```

I found:

Issue from scikit-learn: https://github.com/scikit-learn/scikit-learn/issues/5281
Fix from scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/5301
Fix for numpy: https://github.com/numpy/numpydoc/pull/39/files

**Comment by sciunto** [comment]
See https://github.com/nose-devs/nose/issues/929 (Issue to nose)

**Comment by sciunto** [comment]
Closed, replaced by issue 2424.
