### ISSUE TITLE
ValueError: can not convert object to float64.

### ISSUE THREAD

**Issue by monajalal** [scikit-image/scikit-image#2503]
For the following code:
```
  1 #from pyimagesearch.helpers import pyramid
  2 from skimage import io; io.use_plugin('matplotlib')
  3 from skimage.transform import pyramid_gaussian
  4 import argparse
  5 import cv2
  6 
  7 # construct the argument parser and parse the arguments
  8 ap = argparse.ArgumentParser()
  9 ap.add_argument("-i", "--image", required=True, help="Path to the image")
 10 ap.add_argument("-s", "--scale", type=float, default=1.5, help="scale factor size")
 11 args = vars(ap.parse_args())
 12 
 13 # load the image
 14 image = cv2.imread(args["image"])
 15 
 16 # METHOD #1: No smooth, just scaling.
 17 # loop over the image pyramid
 18 '''
 19 for (i, resized) in enumerate(pyramid(image, scale=args["scale"])):
 20         # show the resized image
 21         cv2.imshow("Layer {}".format(i + 1), resized)
 22         cv2.waitKey(0)
 23 '''
 24 # close all windows
 25 cv2.destroyAllWindows()
 26 
 27 # METHOD #2: Resizing + Gaussian smoothing.
 28 for (i, resized) in enumerate(pyramid_gaussian(image, downscale=2)):
 29         # if the image is too small, break from the loop
 30         if resized.shape[0] < 30 or resized.shape[1] < 30:
 31                 break
 32 
 33         # show the resized image
 34         cv2.imshow("Layer {}".format(i + 1), resized)
 35         cv2.waitKey(0)
```
I get the following error:
```
mona@pascal:~/computer_vision/python_playground$ python pyramid.py -i cat.png
Traceback (most recent call last):
  File "pyramid.py", line 28, in <module>
    for (i, resized) in enumerate(pyramid_gaussian(image, downscale=2)):
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/pyramids.py", line 186, in pyramid_gaussian
    image = img_as_float(image)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 287, in img_as_float
    return convert(image, np.float64, force_copy)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 99, in convert
    raise ValueError("can not convert %s to %s." % (dtypeobj_in, dtypeobj))
ValueError: can not convert object to float64.

```

Is this a bug? 
```
$ uname -a; lsb_release -a; python --version
Linux pascal 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Python 2.7.6

```

**Comment by sciunto** [comment]
@monajalal First, why don't you use `io.imread()` from scikit-image?
Otherwise, could you check the dtype of the image you pass to pyramid?

I link this issue to this ticket: #2500
