### ISSUE TITLE
ORB descriptor fails on 32-bit

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2529]
```
======================================================================
FAIL: skimage.feature.tests.test_orb.test_descriptor_orb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/venv/local/lib/python2.7/site-packages/skimage/feature/tests/test_orb.py", line 99, in test_descriptor_orb
    detector_extractor.descriptors[100:120, 10:20])
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 257, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 719, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 46.5%)
 x: array([[False,  True,  True,  True, False,  True, False,  True, False,
         True],
       [ True,  True,  True, False, False,  True, False, False,  True,...
 y: array([[ True, False, False, False, False, False, False, False,  True,
         True],
       [False,  True,  True,  True, False,  True, False,  True, False,...
```

**Comment by soupault** [comment]
Fails on both https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/tests/test_orb.py#L99 (see `orb_{ref/act}`) and https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/tests/test_orb.py#L103 (see `orb_2_{ref/act}`).

[arrays_orb.zip](https://github.com/scikit-image/scikit-image/files/832136/arrays_orb.zip)

**Comment by soupault** [comment]
Duplicate of https://github.com/scikit-image/scikit-image/issues/2111 .

**Comment by stonebig** [comment]
shouldn't this duplicate issue be closes ? we would be then 1 issue away  from scikit-imagte-0.13.0rc1.

**Comment by soupault** [comment]
@stonebig no, it is not fixed yet.

**Comment by matthew-brett** [comment]
Still failing : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/391261685#L993

**Comment by grlee77** [comment]
Should we close this? We do not distribute 32-bit linux wheels anymore as of 0.19.0. We do have 32-bit Windows wheels but only for Python 3.7-3.9 since NumPy dropped 32-bit windows wheels for Python 3.10.

**Comment by hmaarrfk** [comment]
Unfortunately, I think this is the only thing we can do. We should re-open if this bug reappears. Unless somebody can recreate the issue on a modern system.
