### ISSUE TITLE
Normalized cut error on Py 36

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2530]
```
======================================================================
FAIL: Test to catch an error thrown when subgraph has all equal edges.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/scikit-image/scikit-image-wheels/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/travis/build/scikit-image/scikit-image-wheels/venv/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/Users/travis/build/scikit-image/scikit-image-wheels/venv/lib/python3.6/site-packages/skimage/future/graph/tests/test_rag.py", line 180, in test_ncut_stable_subgraph
    assert new_labels.max() == 0
AssertionError
```

https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/203631060

**Comment by stefanv** [comment]
Closing as duplicate of https://github.com/scikit-image/scikit-image/issues/2450
