### ISSUE TITLE
skimage.color.rgb2hed scale not between (-1,1)

### ISSUE THREAD

**Issue by jessejohns** [scikit-image/scikit-image#2546]
## Description

Hello, when I convert an image from RGB to HED, I am no longer able to use other skimage tools like util.img_as_ubyte.  In particular, I get the following error:

`    img = util.img_as_ubyte(img)
  File "/home/jesse/programs/anaconda/lib/python2.7/site-packages/skimage/util/dtype.py", line 409, in img_as_ubyte
    return convert(image, np.uint8, force_copy)
  File "/home/jesse/programs/anaconda/lib/python2.7/site-packages/skimage/util/dtype.py", line 236, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1`

The min/max output from the image before conversion:
> 0  255
after conversion:
> -1.60028053318 0.694133338597

## Way to reproduce

```
from skimage.color import rgb2hed
from skimage import util
print np.min(img), np.max(img)
img = np.array(rgb2hed(img))

print np.min(img), np.max(img)
img = util.img_as_ubyte(img)
```

I am using Kubuntu 64-bit, Python 2 with Anaconda.

>>> skimage.__version__
'0.12.3

**Comment by sciunto** [comment]
Could you provide the image please?

**Comment by jessejohns** [comment]
I can't share any of images I'm working with, but if you grab anything from Google images you'll encounter the same issue.

**Comment by sciunto** [comment]
Thanks. As a workaround, you can use this function after converting your images to rescale the range between -1, 1

http://scikit-image.org/docs/stable/api/skimage.exposure.html#rescale-intensity

**Comment by f0k** [comment]
It's the same for the CIE LAB space:
```
>>> skimage.color.rgb2lab([[[1., 1., 1.]]])
array([[[  1.00000000e+02,  -2.45493786e-03,   4.65342115e-03]]])
>>> skimage.color.lab2rgb([[[100., 0, 0]]])
array([[[ 1.        ,  0.99999542,  1.        ]]])
```
It's not a problem as long as I use float64, but when I provide float32 input, it's unhappy:
```
>>> skimage.color.lab2rgb(np.array([[[100., 0, 0]]], np.float32))
```
<details><summary>stack trace</summary>

```
Traceback (most recent call last)
<ipython-input-3-0a2b36865b6f> in <module>()
----> 1 skimage.color.lab2rgb(np.array([[[100., 0, 0]]], np.float32))

/raid/user/jan/.local/lib/python2.7/site-packages/skimage/color/colorconv.pyc in lab2rgb(lab)
    963     This function uses lab2xyz and xyz2rgb.
    964     """
--> 965     return xyz2rgb(lab2xyz(lab))
    966 
    967 

/raid/user/jan/.local/lib/python2.7/site-packages/skimage/color/colorconv.pyc in lab2xyz(lab, illuminant, observer)
    890     """
    891 
--> 892     arr = _prepare_colorarray(lab).copy()
    893 
    894     L, a, b = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2]

/raid/user/jan/.local/lib/python2.7/site-packages/skimage/color/colorconv.pyc in _prepare_colorarray(arr)
    151         raise ValueError(msg)
    152 
--> 153     return dtype.img_as_float(arr)
    154 
    155 

/raid/user/jan/.local/lib/python2.7/site-packages/skimage/util/dtype.pyc in img_as_float(image, force_copy)
    299 
    300     """
--> 301     return convert(image, np.float64, force_copy)
    302 
    303 

/raid/user/jan/.local/lib/python2.7/site-packages/skimage/util/dtype.pyc in convert(image, dtype, force_copy, uniform)
    203     if kind_in == 'f':
    204         if np.min(image) < -1.0 or np.max(image) > 1.0:
--> 205             raise ValueError("Images of type float must be between -1 and 1.")
    206         if kind == 'f':
    207             # floating point -> floating point

ValueError: Images of type float must be between -1 and 1.
```
</details>

This is with skimage 0.12.3, haven't checked with more recent ones. Either the color space definitions need to change, or the conversion code. Changing the color space definitions to have Lightness range from 0 to 1 instead of 0 to 100 would break any user code that depends on the current definition.

**Comment by rfezzani** [comment]
Can close, it is fixed by #2599.

**Comment by jni** [comment]
@rfezzani that PR was never merged...?

**Comment by rfezzani** [comment]
:+1: @jni... By the way, is this really a bug? The stain separation method based on linear system inversion  do absolutely not guaranty any bounds on the output values.
An option would be to add a `rescale` argument to the `rgb2hed` function that, if set to true, rescales the result like @sciunto did in #2599.

**Comment by rfezzani** [comment]
I would like to refer to @crisluengo https://github.com/scikit-image/scikit-image/pull/4725#issuecomment-629583372 that explains why `rgb2hed` scale isn't (and should not be) between -1 and 1.
I will remove the `Bug` label and let anyone else decide if we should close this issue ;)
