### ISSUE TITLE
Label and intensity images can have different shapes

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2561]
RegionProps reports, for

```regionprops(label_image, intensity_image=image)```

with

`label_image` -> `(500, 500)`
`intensity_image` -> `(500, 500, 3)`

```
Traceback (most recent call last):
  File "/tmp/foofoo.py", line 28, in <module>
    regions = measure.regionprops(label_img, intensity_image=img)
  File "/home/stefan/src/scikit-image/skimage/measure/_regionprops.py", line 551, in regionprops
    cache)
  File "/home/stefan/src/scikit-image/skimage/measure/_regionprops.py", line 98, in __init__
    raise ValueError('Label and intensity image must have the'
ValueError: Label and intensity image must have thesame shape.
```

It is quite common to have a label_image that combines he RGB channels; this common use case should be supported.

**Comment by nzoghb** [comment]
The potential fix would be included in `class _RegionProperties` I believe. What would be a good way to go about this fix?

**Comment by jni** [comment]
@nzoghb indeed, we want to allow nD images, not just 2D, so that's not the best check.

**Comment by nzoghb** [comment]
Along the same lines of thought, could we just compare lengths and ensure they are the same ±1. It's another janky solution.

**Comment by noahstier** [comment]
`if not intensity_image.shape == label_image.shape or intensity_image.shape[:-1] == label_image.shape`? Seems like those are the two cases that should be allowed
