### ISSUE TITLE
io.imshow doesn't work

### ISSUE THREAD

**Issue by PeterZs** [scikit-image/scikit-image#2595]
## Description
[Please provide a general introduction to the issue/proposal.]
I installed skimage 0.13.0 on Ubutun 16.04 (VMware Workstation player12)   and  python2.7

I test skimage use the following program:

from skimage import data, io, filters
image = data.coins()
edges = filters.sobel(image)
io.imshow(edges)
io.show()

The error message is below:

```
>>> io.imshow(edges)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 156, in imshow
    return call_plugin('imshow', arr, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 198, in call_plugin
    raise RuntimeError(msg % kind)
RuntimeError: No suitable plugin registered for imshow.

You may load I/O plugins with the `skimage.io.use_plugin` command.  A list of all available plugins are shown in the `skimage.io` docstring.
>>> io.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 198, in show
    return call_plugin('_app_show')
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 198, in call_plugin
    raise RuntimeError(msg % kind)
RuntimeError: No suitable plugin registered for _app_show.

You may load I/O plugins with the `skimage.io.use_plugin` command.  A list of all available plugins are shown in the `skimage.io` docstring.
```

**Comment by soupault** [comment]
@PeterZs Hi!
To diagnose we'll need the output of 
1. `pip list`;
2. `io.find_available_plugins()`;
3. `io.find_available_plugins(loaded=True)`;

If the output of `3.` on your system is not empty, try `io.use_plugin(%string with the plugin name%)` and then repeat the execution of your code.

For more information, see http://scikit-image.org/docs/dev/user_guide/plugins.html.

Let us know if this helps or not.

**Comment by PeterZs** [comment]
@soupault  
The execute report

pip list --format columns:

Package            Version    
------------------ -----------
adium-theme-ubuntu 0.3.4      
cycler             0.10.0     
decorator          4.0.11     
functools32        3.2.3.post2
matplotlib         2.0.0      
networkx           1.11       
numpy              1.12.1     
olefile            0.44       
Pillow             4.1.0      
pip                9.0.1      
pyparsing          2.2.0      
python-dateutil    2.6.0      
pytz               2017.2     
PyWavelets         0.5.2      
scikit-image       0.13.0     
scipy              0.19.0     
setuptools         20.7.0     
six                1.10.0     
subprocess32       3.2.7      
unity-lens-photos  1.0        
wheel              0.29.0  


>>> io.find_available_plugins()
{'tifffile': ['imread', 'imsave', 'imread_collection'], 'pil': ['imread', 'imsave', 'imread_collection'], 'qt': ['imshow', 'imsave', 'imread', 'imread_collection'], 'freeimage': ['imread', 'imsave', 'imread_collection'], 'gtk': ['imshow'], 'matplotlib': ['imshow', 'imread', 'imshow_collection', 'imread_collection'], 'test': ['imsave', 'imshow', 'imread', 'imread_collection', 'imshow_collection'], 'simpleitk': ['imread', 'imsave', 'imread_collection'], 'imread': ['imread', 'imsave', 'imread_collection'], 'imageio': ['imread', 'imsave', 'imread_collection'], 'fits': ['imread', 'imread_collection'], 'gdal': ['imread', 'imread_collection']}


>>> io.find_available_plugins(loaded=True)
{'pil': ['imread', 'imsave', 'imread_collection']}


then I use    io.use_plugin('matplotlib'), but I got another error

>>> io.use_plugin('matplotlib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 255, in use_plugin
    _load(name)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 299, in _load
    fromlist=[modname])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

**Comment by PeterZs** [comment]
@soupault 

After I install  python-tk use "sudo apt-get install python-tk" ,   it works. 

Thank U a lot.

**Comment by johndpope** [comment]
osx -> https://qiita.com/atuyosi/items/9dd9f637e3f53a41f010

$ brew install qt
$ pip install PyQt5



>>> from skimage import io
>>> io.use_plugin('matplotlib')
>>> io.find_available_plugins(loaded=True)
{'matplotlib': ['imshow', 'imread', 'imshow_collection', 'imread_collection'], 'pil': ['imread', 'imsave', 'imread_collection']}

>>> from skimage import io
>>> img =  io.imread("test.jpg")
>>> io.imshow(img)
<matplotlib.image.AxesImage object at 0x110ba1160>
>>> io.show()
^C
io.imshow()

**Comment by licheeng** [comment]
conda install -c conda-forge scikit-image

it works very well
