### ISSUE TITLE
32-bit test failures on latest master

### ISSUE THREAD

**Issue by matthew-brett** [scikit-image/scikit-image#2670]
Running a wheel build / test on latest master:

https://travis-ci.org/scikit-image/scikit-image-wheels/builds/236518849

I am getting 3 test failures for the 32-bit builds:

https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/236518852

```
::test_descriptor_orb <- ../../venv/lib/python2.7/site-packages/skimage/feature/tests/test_orb.py FAILED
```

```
::TestRank::test_all <- ../../venv/lib/python2.7/site-packages/skimage/filters/rank/tests/test_rank.py Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/venv/lib/python2.7/site-packages/skimage/filters/rank/tests/test_rank.py", line 87, in check_all
    rank.entropy(self.image, selem))
  File "/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 322, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 813, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 1.28%)
 x: array([[ 1.584963,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,...
 y: array([[ 1.584963,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,...

FAILED
```

```
::test_ellipse_model_estimate_failers <- ../../venv/lib/python2.7/site-packages/skimage/measure/tests/test_fit.py FAILED
```

There is more verbose detail in the log above.

**Comment by matthew-brett** [comment]
For testing see : https://github.com/scikit-image/scikit-image/wiki/Testing-in-32-bit-environment

**Comment by soupault** [comment]
@matthew-brett those are the very bug we observed before the release of 0.13: issue for `rank` - https://github.com/scikit-image/scikit-image/issues/2528, issue for `ORB` - https://github.com/scikit-image/scikit-image/issues/2529. The one for `ellipse_model` is new though. I've renamed the issue to be linked only to the latter.

**Comment by matthew-brett** [comment]
Latest run : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/391261685#L1183
