### ISSUE TITLE
plot_matches does not draw lines

### ISSUE THREAD

**Issue by retsyo** [scikit-image/scikit-image#2795]
I use `scikit_image‑0.13.0‑cp36‑cp36m‑win_amd64.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image on my `Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32` which has `matplotlib‑2.1.0rc1‑cp36‑cp36m‑win_amd64.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#matplotlib

I tested the code from http://scikit-image.org/docs/dev/auto_examples/features_detection/plot_brief.html
but get the following msg. However, I searched and found https://github.com/scikit-image/scikit-image/issues/2649 on which a similar msg is said to be fixed

```bash
>e:\prg\py\Anaconda3_64\python.exe -u "test_brief.py"
Traceback (most recent call last):
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\colors.py", line 141, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
TypeError: unhashable type: 'numpy.ndarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 197, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\axes\_base.py", line 2426, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\lines.py", line 803, in draw
    ln_color_rgba = self._get_rgba_ln_color()
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\lines.py", line 1344, in _get_rgba_ln_color
    return mcolors.to_rgba(self._color, self._alpha)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\colors.py", line 143, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\matplotlib\colors.py", line 194, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: array([[ 0.85443664],
       [ 0.85820926],
       [ 0.23652066]])
>Exit code: 0

```

**Comment by retsyo** [comment]
sorry, I found this has been fixed in the git-cloned code. Please close this. Thanks
