### ISSUE TITLE
3 tests fail in 32bit

### ISSUE THREAD

**Issue by yarikoptic** [scikit-image/scikit-image#2844]
- [x] Operating system and version: debian unstable 32bit
- [x] Python version: 2.7.14 (I think)
- [x] scikit-image version: 0.13.1

```
======================================================================
ERROR: skimage.filters.rank.tests.test_rank.TestRank.test_bitdepth
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/filters/rank/tests/test_rank.py
", line 190, in test_bitdepth
    out=out, shift_x=0, shift_y=0, p0=.1, p1=.9)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/_shared/_warnings.py", line 121
, in expected_warnings
    raise ValueError('Unexpected warning: %s' % str(warn.message))
ValueError: Unexpected warning: Possible precision loss when converting from float64 to uint8

======================================================================
FAIL: skimage.feature.tests.test_orb.test_descriptor_orb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/feature/tests/test_orb.py", lin
e 104, in test_descriptor_orb
    detector_extractor.descriptors[100:120, 10:20])
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 343, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 46.5%)
 x: array([[False,  True,  True,  True, False,  True, False,  True, False,
         True],
       [ True,  True,  True, False, False,  True, False, False,  True,...
 y: array([[ True, False, False, False, False, False, False, False,  True,
         True],
       [False,  True,  True,  True, False,  True, False,  True, False,...
======================================================================
FAIL: skimage.filters.rank.tests.test_rank.TestRank.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/filters/rank/tests/test_rank.py
", line 98, in test_all
    check_all()
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/_shared/testing.py", line 235, 
in inner
    result = func(*args, **kwargs)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/filters/rank/tests/test_rank.py", line 89, in check_all
    rank.entropy(self.image, selem))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 343, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 1.28%)
 x: array([[ 1.584963,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,...
 y: array([[ 1.584963,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,
         2.      ,  2.      ,  2.      ,  2.      ,  2.      ,  2.      ,...

```
Discovered while building backports for NeuroDebian.  I will upload 0.13.1 as is to see what other platforms give us ;)

**Comment by yarikoptic** [comment]
FWIW verified on master in a local 32bit chroot

**Comment by soupault** [comment]
Issue for ORB - https://github.com/scikit-image/scikit-image/issues/2529, issue for `skimage.filters.rank.tests.test_rank.TestRank.test_all` - https://github.com/scikit-image/scikit-image/issues/2528.
