### ISSUE TITLE
Trace back error while importing modules from skimage

### ISSUE THREAD

**Issue by shrestharikesh** [scikit-image/scikit-image#2970]
Hi,
I'm using python 2.7.14 and successfully installed skimage. But now I am having trouble importing modules from skimage. I got follwing issue

 >>>import skimage.io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *
  File "C:\Python27\lib\site-packages\skimage\io\_io.py", line 7, in <module>
    from ..color import rgb2grey
  File "C:\Python27\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Python27\lib\site-packages\skimage\color\colorconv.py", line 59, in <module>
    from scipy import linalg
  File "C:\Python27\lib\site-packages\scipy\linalg\__init__.py", line 186, in <module>
    from .misc import *
  File "C:\Python27\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Python27\lib\site-packages\scipy\linalg\blas.py", line 196, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

- [ windows 10] Operating system 
- [ 2.7.14] Python version
- [0.13.1 ] scikit-image version

**Comment by jni** [comment]
It looks like you didn't correctly install SciPy, which we depend on.

**Comment by shrestharikesh** [comment]
@jni I've installed scipy '1.0.0' for cp27 from 'www.lfd.uci.edu/~gohlke/pythonlibs/'

**Comment by jni** [comment]
Hmmm. My guess is that the Python that you installed SciPy for and the Python that you installed scikit-image for are different. What happens if you launch Python and then try:

```python
>>> import numpy as np
>>> from scipy import linalg
>>> x = np.random.random((2, 2))
>>> result = linalg.eig(x)
```

We will do our best to help you get an installation working, but in general, on Windows, I recommend installing Anaconda. (And Python 3.6.) Is there a specific reason why you didn't use that?

**Comment by shrestharikesh** [comment]
@jni  I cannot import linalg from scipy.
It gives following trace back error: 
>>>from scipy import linalg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\scipy\linalg\__init__.py", line 186, in <module>
    from .misc import *
  File "C:\Python27\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Python27\lib\site-packages\scipy\linalg\blas.py", line 196, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

**Comment by shrestharikesh** [comment]
I'm working on projects done in  Python 2.7.
To ease up my task I've been using the same version

**Comment by cgohlke** [comment]
> I've installed scipy '1.0.0' for cp27 from 'www.lfd.uci.edu/~gohlke/pythonlibs/'

For those scipy builds, make sure to use [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy), not the official numpy binaries from PyPI.
