### ISSUE TITLE
Incompatible modes with anti-aliasing in skimage.transform.resize

### ISSUE THREAD

**Issue by jsleb333** [scikit-image/scikit-image#3299]
## Bug description
When resizing an image with `skimage.transform.resize`, using the modes 'symmetric' or 'edge' with anti-aliasing set to True raises an error.

Traceback:
```
Traceback (most recent call last):
  File "d:\Dossier de Jean-Samuel\git\quadboost\test\issue.py", line 6, in <module>
    transform.resize(image, (8,6), order=3, mode='symmetric', anti_aliasing=True)
  File "C:\Users\Jean-Samuel\Miniconda3\lib\site-packages\skimage\transform\_warps.py", line 144, in resize
    cval=cval, mode=mode)
  File "C:\Users\Jean-Samuel\Miniconda3\lib\site-packages\scipy\ndimage\filters.py", line 286,
in gaussian_filter
    mode, cval, truncate)
  File "C:\Users\Jean-Samuel\Miniconda3\lib\site-packages\scipy\ndimage\filters.py", line 204,
in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "C:\Users\Jean-Samuel\Miniconda3\lib\site-packages\scipy\ndimage\filters.py", line 90, in correlate1d
    mode = _ni_support._extend_mode_to_code(mode)
  File "C:\Users\Jean-Samuel\Miniconda3\lib\site-packages\scipy\ndimage\_ni_support.py", line 52, in _extend_mode_to_code
    raise RuntimeError('boundary mode not supported')
RuntimeError: boundary mode not supported
```

## Way to reproduce
- Code example:
```python
import numpy as np
from skimage import transform

image = np.ones((10,10))
transform.resize(image, (8,6), order=3, mode='symmetric', anti_aliasing=True)
```
- Operating system and version: Windows 10 pro (version 10.0.17134)
- Python version: 3.6.5 (Anaconda)
- scikit-image version: 0.14.0

## Possible cause
The bug seems to be caused by the gaussian_filter used for anti-aliasing, that is computed from the scipy.ndimage module, which seems to support the following modes (in the file `_ni_support.py`):
```python
def _extend_mode_to_code(mode):
    """Convert an extension mode to the corresponding integer code.
    """
    if mode == 'nearest':
        return 0
    elif mode == 'wrap':
        return 1
    elif mode == 'reflect':
        return 2
    elif mode == 'mirror':
        return 3
    elif mode == 'constant':
        return 4
    else:
        raise RuntimeError('boundary mode not supported')
```
where the terminology is different and looks like 'symmetric' is 'mirror' and 'edge' is 'nearest'. For the record, my scipy version is 1.1.0.

**Comment by soupault** [comment]
Closed via #3368
