### ISSUE TITLE
Faliure to import hough_ellipse from skimage.transform 

### ISSUE THREAD

**Issue by macrostatic** [scikit-image/scikit-image#3332]
## Description
Hello, I just installed scikit-image but I found that I cannot import hough_ellipse at the Python Shell. 

I already installed matplotlib, numpy, pillow and scipy, which can have dependance with scikit_image. Like below lines, by command pip list.

Package               Version
--------------------- --------
cloudpickle           0.5.3
cycler                0.10.0
Cython                0.28.5
dask                  0.18.2
decorator             4.3.0
kiwisolver            1.0.1
matplotlib            2.2.2
networkx              2.1
numpy                 1.15.0
opencv-contrib-python 3.4.2.17
Pillow                5.2.0
pip                   18.0
pynput                1.4
pyparsing             2.2.0
python-dateutil       2.7.3
pytz                  2018.5
PyWavelets            0.5.2
scikit-image          0.14.0
scipy                 1.1.0
setuptools            39.0.1
six                   1.11.0
toolz                 0.9.0

however, i cannot import hough_ellipse at python shell. 

the command I entered is , >>from skimage.transform import hough_ellipse

the error code is like below,

Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    from skimage.transform import hough_ellipse
  File "E:\Users\Hansung\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\__init__.py", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "E:\Users\Hansung\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\hough_transform.py", line 2, in <module>
    from ._hough_transform import (_hough_circle,
  File "skimage\transform\_hough_transform.pyx", line 14, in init skimage.transform._hough_transform
  File "E:\Users\Hansung\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\draw\__init__.py", line 1, in <module>
    from .draw import (circle, ellipse, set_color, polygon_perimeter,
  File "E:\Users\Hansung\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\draw\draw.py", line 4, in <module>
    from .._shared._geometry import polygon_clip
ModuleNotFoundError: No module named 'skimage._shared._geometry'

How can I solve it?

**Comment by soupault** [comment]
It seems that your tried to install `scikit-image` on Windows using `pip` and didn't get it correctly built (due to missing compiler or other issues). I'd suggest to try installing pre-build package from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image, or use Conda distribution.

**Comment by soupault** [comment]
@macrostatic Any success so far?
