### ISSUE TITLE
Missing PyPI wheel for Python 3.7

### ISSUE THREAD

**Issue by evertrol** [scikit-image/scikit-image#3362]
PyPI is missing a wheel for Python 3.7. This causes pip to fail when installing scikit-image in an empty (virtual) environment. 

Example:
```
$ python3.7 -m venv test-install-scikit-image
$ source test-install-scikit-image/bin/activate
$ python --version
Python 3.7.0
$ which pip
/Users/evert/venv/test-install-scikit-image/bin/pip
$ pip --version
pip 10.0.1 from /Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/pip (python 3.7)
$ pip install scikit-image
[...]
```

which results in (last lines of backtrace)

```
  File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-zjlj_gvb/scikit-image/skimage/_build.py", line 42, in cython
    % CYTHON_VERSION)
RuntimeError: Cython >= 0.23 is required to build scikit-image from git checkout
```

Usually, a two-step installation (installing NumPy / Cython first) is no problem, but for some cases, there is no control of the environment and process doing the installation, and it has to be a one-step process.

In my particular case, this is for http://mybinder.org, which builds Docker images (for use with a Jupyter notebook) from a repository, reading the requirements file for the installation (which logically doesn't include Cython). Apparently, the default Docker image from which the image is build uses Python 3.7.
Though in this particular (using the `repo2docker` package to confirm myself), the installation fails because NumPy is apparently not installed first, and the `setup.py` errors. But the cause appears to be the same, and relies on not having to build from source (or requiring Cython/NumPy), but using a PyPI wheel.

related: #3356; [discussion on this particularly point starts here](https://github.com/scikit-image/scikit-image/issues/3356#issuecomment-413523398).

MacOSX 10.13.7, Homebrew Python 3.7.0, scikit-image 0.14.0 (source) from PyPI.

---

Full traceback for completeness (on second installation try, so skipping previously successfully installed packages):

```
$ pip install scikit-image
Collecting scikit-image
  Using cached https://files.pythonhosted.org/packages/fc/20/d3e736493b16e9455ce8579722d644b313814c599d5824d34e448845f746/scikit-image-0.14.0.tar.gz
    Complete output from command python setup.py egg_info:
    Partial import of skimage during the build process.
    Traceback (most recent call last):
      File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-trvmqya6/scikit-image/skimage/_build.py", line 30, in cython
        from Cython import __version__
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-trvmqya6/scikit-image/setup.py", line 149, in <module>
        **extra
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-trvmqya6/scikit-image/setup.py", line 70, in configuration
        config.add_subpackage('skimage')
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        caller_level = 2)
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
        caller_level = caller_level + 1)
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/setup.py", line 14, in configuration
        config.add_subpackage('feature')
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        caller_level = 2)
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
        caller_level = caller_level + 1)
      File "/Users/evert/venv/test-install-scikit-image/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/feature/setup.py", line 22, in configuration
        cython(['_haar.pyx'], working_path=base_path)
      File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-trvmqya6/scikit-image/skimage/_build.py", line 42, in cython
        % CYTHON_VERSION)
    RuntimeError: Cython >= 0.23 is required to build scikit-image from git checkout
    Cython >= 0.23 not found; falling back to pre-built geometry.c
    Cython >= 0.23 not found; falling back to pre-built transform.c
    Cython >= 0.23 not found; falling back to pre-built interpolation.c
    Cython >= 0.23 not found; falling back to pre-built _draw.c
    Cython >= 0.23 not found; falling back to pre-built corner_cy.c
    Cython >= 0.23 not found; falling back to pre-built censure_cy.c
    Cython >= 0.23 not found; falling back to pre-built orb_cy.c
    Cython >= 0.23 not found; falling back to pre-built brief_cy.c
    Cython >= 0.23 not found; falling back to pre-built _texture.c
    Cython >= 0.23 not found; falling back to pre-built _hessian_det_appx.c
    Cython >= 0.23 not found; falling back to pre-built _hoghistogram.c

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-trvmqya6/scikit-image/
```

**Comment by matthew-brett** [comment]
Wheels are built and tested for Python 3.7, I'm waiting for agreement to upload them to PyPI : https://github.com/scikit-image/scikit-image-wheels/issues/9

**Comment by matthew-brett** [comment]
Wheels should be available now - can you check that you get them?

**Comment by evertrol** [comment]
That was quick enough :-).

Tested, and works now, both on mybinder.org and in a local virtual environment.

Thanks!
