### ISSUE TITLE
Building the docs within conda

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3408]
Does anybody know how to build the docs within a conda environment? I keep getting
```
The HTML pages are in build/html.
embedding documentation hyperlinks...

Exception occurred:
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
The full traceback has been saved in /tmp/sphinx-err-qyxfuhev.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:53: recipe for target 'html' failed
```

```
# Sphinx version: 1.7.9
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   done
#   
#   build succeeded.
#   
#   
#   
#   The HTML pages are in build/html.
#   
#   embedding documentation hyperlinks...
#   
# Loaded extensions:
#   alabaster (0.7.11) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7.9) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.mathjax (1.7.9) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.autosummary (1.7.9) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   numpydoc (0.8.0) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/numpydoc/__init__.py
#   doi_role (0.1) from /home/mark/git/scikit-image/doc/source/../ext/doi_role.py
#   sphinx.ext.intersphinx (1.7.9) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.linkcode (1.7.9) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/ext/linkcode.py
#   sphinx_gallery.gen_gallery (0.2.0) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py
Traceback (most recent call last):
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/application.py", line 356, in build
    self.emit('build-finished', None)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 410, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 279, in _embed_code_links
    app.builder.outdir, src_gallery_dir, relative=True)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 180, in __init__
    index = get_data(index_url, gallery_dir)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 69, in get_data
    search_index = shelve.open(cached_file)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/mark/miniconda3/envs/sk-dev/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```
```
➤ python                                                                                                                                                                                                  (sk-dev) 
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by hmaarrfk** [comment]
The answer is that python needs to be compiled with gdbm support. for that to happen, gdbm needs to be present at build time.

These PRs 

 * https://github.com/conda-forge/python-feedstock/pull/195
 * https://github.com/conda-forge/staged-recipes/pull/6681

Attempt to fix that. I can confirm that after compiling python myself that this works.
