### ISSUE TITLE
Import error cannot import name 'geometry'

### ISSUE THREAD

**Issue by jiafatom** [scikit-image/scikit-image#3832]
## Description
I installed scikit-image via `conda install -c conda-forge scikit-image` on Windows, I am on python3.6, with `cython                    0.29.6           py36ha925a31_0`, `scikit-image              0.14.2           py36h6538335_0    conda-forge`. When I import using `import skimage;`, it gives me the error: 
```
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\__init__.py", line 153, in <module>
    from ._shared import geometry
ImportError: cannot import name 'geometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/dev/unet/main.py", line 7, in <module>
    import skimage; print("scikit-image version: {}".format(skimage.__version__))
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\__init__.py", line 156, in <module>
    _raise_build_error(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\__init__.py", line 137, in _raise_build_error
    %s""" % (e, msg))
ImportError: cannot import name 'geometry'
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
http://scikit-image.org/docs/stable/install.html 

Process finished with exit code 1`
```
I tried to search the issues in scikit-image, but didn't figure out. Could someone help? Thanks!

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
import skimage
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import numpy; print("numpy version: {}".format(numpy.__version__))
import skimage; print("scikit-image version: {}".format(skimage.__version__))
```

```python
# your output here
3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
numpy version: 1.14.6
```

**Comment by jni** [comment]
@jiafatom can you please provide the full error message, rather than the last line?

**Comment by jiafatom** [comment]
@jni Thanks for your reply, I updated my original post, thank you!

**Comment by jni** [comment]
@jiafatom I have to say I'm surprised. Have you attempted to install the scikit-image source from GitHub? Could you maybe try `conda uninstall scikit-image; pip uninstall scikit-image; conda install -c conda-forge scikit-image`? Another option is to install it from the defaults channel, as sometimes conda-forge and defaults packages are incompatible.

**Comment by hmaarrfk** [comment]
Can you please output the result of

conda list


pip list

**Comment by jiafatom** [comment]
It works after I conda/pip uninstall and conda install again, thank you!

**Comment by chouqin3** [comment]
不能含有conda-forge或者pip等关键字安装，在我电脑上使用 conda install scikit-image=0.17.2 安装成功

**Comment by josecelano** [comment]
I have a similar error using docker with a distroless image:

```
Traceback (most recent call last):
  File "/app/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
ImportError: cannot import name 'geometry' from 'skimage._shared' (/app/skimage/_shared/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 1, in <module>
    from skimage import img_as_ubyte
  File "/app/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)
  File "/app/skimage/__init__.py", line 104, in _raise_build_error
    %s""" % (e, msg))
ImportError: cannot import name 'geometry' from 'skimage._shared' (/app/skimage/_shared/__init__.py)
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
```

I have created a git repo explaining how you can reproduce the error: https://github.com/josecelano/skimage-distroless
