### ISSUE TITLE
AttributeError: module 'pywt' has no attribute 'dwtn'

### ISSUE THREAD

**Issue by yythrive** [scikit-image/scikit-image#3863]
When I recovered the modern code, I encountered such a problem.
Traceback (most recent call last):
  File "/home/yy/桌面/pycharm-2018.2.4/CS/mri(deep piror)/toepli.py", line 40, in <module>
    sigma_est = np.mean(estimate_sigma(noisy, multichannel=True))
  File "/home/yy/anaconda3/lib/python3.6/site-packages/skimage/restoration/_denoise.py", line 747, in estimate_sigma
    image[..., c], multichannel=False) for c in range(nchannels)]
  File "/home/yy/anaconda3/lib/python3.6/site-packages/skimage/restoration/_denoise.py", line 747, in <listcomp>
    image[..., c], multichannel=False) for c in range(nchannels)]
  File "/home/yy/anaconda3/lib/python3.6/site-packages/skimage/restoration/_denoise.py", line 756, in estimate_sigma
    coeffs = pywt.dwtn(image, wavelet='db2')
AttributeError: module 'pywt' has no attribute 'dwtn'
How can I solve it?please help me

**Comment by grlee77** [comment]
This may be due to the following issue:
https://github.com/PyWavelets/pywt/issues/430

**Comment by yythrive** [comment]
Already solved, thank you very much
