### ISSUE TITLE
fast_exp missing when compiled in Alpine OS

### ISSUE THREAD

**Issue by hongquan** [scikit-image/scikit-image#3866]
## Description

When I use pip to install scikit-image inside Alpine OS 3.9 (which uses musl for standard lib C), the produced scikit-image is missing `fast_exp`

The normal import code:

```py
import skimage
```
leads to this error:

```
appareil/tasks.py:5: in <module>
    import skimage
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/__init__.py:135: in <module>
    from .data import data_dir
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/data/__init__.py:16: in <module>
    from ._binary_blobs import binary_blobs
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/data/_binary_blobs.py:2: in <module>
    from ..filters import gaussian
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/filters/__init__.py:3: in <module>
    from .edges import (sobel, sobel_h, sobel_v,
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/filters/edges.py:17: in <module>
    from ..restoration.uft import laplacian
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/restoration/__init__.py:10: in <module>
    from .non_local_means import denoise_nl_means
/root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/restoration/non_local_means.py:2: in <module>
    from ._nl_means_denoising import (
E   ImportError: Error relocating /root/.cache/pypoetry/virtualenvs/manwa-fys_VRJo-py3.6/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so: fast_exp: symbol not found
```

## Way to reproduce

I prepared a Docker images, where I installed build tools, libraries. I also built some Python packages to whl files, to help install faster. 

```
docker run -it quay.io/quan/docker-ansible-libav-django /bin/bash
```

Inside the Docker container, run

```
pip3 install scikit-image --extra-index-url https://dl.cloudsmith.io/public/agriconnect/python-musl/python/index/

python3
```
Inside Python3:

```py
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "/usr/lib/python3.6/site-packages/skimage/data/__init__.py", line 16, in <module>
    from ._binary_blobs import binary_blobs
  File "/usr/lib/python3.6/site-packages/skimage/data/_binary_blobs.py", line 2, in <module>
    from ..filters import gaussian
  File "/usr/lib/python3.6/site-packages/skimage/filters/__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "/usr/lib/python3.6/site-packages/skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "/usr/lib/python3.6/site-packages/skimage/restoration/__init__.py", line 10, in <module>
    from .non_local_means import denoise_nl_means
  File "/usr/lib/python3.6/site-packages/skimage/restoration/non_local_means.py", line 2, in <module>
    from ._nl_means_denoising import (
ImportError: Error relocating /usr/lib/python3.6/site-packages/skimage/restoration/_nl_means_denoising.cpython-36m-x86_64-linux-gnu.so: fast_exp: symbol not found
```

## Version information

```python
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.16.3
>>> import sys; print(sys.version)
3.6.8 (default, Apr  8 2019, 18:17:52) 
[GCC 8.3.0]
>>> import platform; print(platform.platform())
Linux-5.0.0-13-generic-x86_64-with
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.16.3

```

**Comment by hmaarrfk** [comment]
how does numpy address this? how did you install numpy?

**Comment by hongquan** [comment]
To build NumPy, I installed these packages (via `apk`) in Docker container: `python3`, `build-base`, `libffi-dev`, `python3-dev`, `jpeg-dev`, `zlib-dev`, `freetype-dev`, `libpng-dev`, `lapack-dev`, `gfortran`, `cython`, then built it with:

```
pip3 install numpy
```

**Comment by hmaarrfk** [comment]
Did it compile scikit image or did it use the wheel?

**Comment by hongquan** [comment]
@hmaarrfk I don't understand your question.
That error appears both when I let `pip` install scikit-image from source (`pip` download `tar.gz` and compile) and from wheel file (the wheel file was built from `pip` previously by me).

**Comment by hmaarrfk** [comment]
Ok i get it, i didn't know alpine automatically used source from pypi. I'm trying to build again locally, lets see what happens.

**Comment by hmaarrfk** [comment]
my first guess, if you are faster than me, is to try a different version of cython. Since you are in 3.6, you can use 0.28??? or even 3.0???

**Comment by hmaarrfk** [comment]
yeah, this was added 2 years ago. Were you able to get scikit-image working for version 0.14???

**Comment by hongquan** [comment]
You mean cython 0.14? The oldest cython in Alpine repository is already v0.23 (https://pkgs.alpinelinux.org/packages?name=cython&branch=v3.3). I hesitate to installl cython from source.

**Comment by jni** [comment]
No, he means scikit-image was using fast_exp as of two years ago, and scikit-image 0.14 should have had the same build problems. What is the *latest* Cython you have?

It looks like `fast_exp` is defined inline in a header-only file, `skimage/_shared/fast_exp.h`, so I think @hmaarrfk's intuition that this is a Cython problem (and not a libc problem) is correct. I haven't used the `cdef extern from "fast_exp.h":` syntax in Cython before so I don't know when it was introduced, but that appears to be the culprit (in `skimage/restoration/_nl_means_denoising.pyx`) based on your error message. (Note also that `skimage/restoration/setup.py` specifies the include paths, and that could also be where this is failing, if that syntax changed between Cython versions.)

**Comment by hmaarrfk** [comment]
yeah i just tried cython = 0.28.6 and 0.29 yesterday. Didn't work with either.

My guess is that it is a cython bug, because that file is header only, but maybe we didn't declare it right?

**Comment by hmaarrfk** [comment]
My guess is it has to do with the fact that we are using `__inline` https://stackoverflow.com/a/2765200/2321145

I think it is because 
https://stackoverflow.com/questions/22767523/what-inline-attribute-always-inline-means-in-the-function

```patch
diff --git a/skimage/_shared/fast_exp.h b/skimage/_shared/fast_exp.h
index 0c106673..a16a2dea 100644
--- a/skimage/_shared/fast_exp.h
+++ b/skimage/_shared/fast_exp.h
@@ -12,7 +12,7 @@
 /* For min. mean relative error */
 /* #define EXP_BC 1072625005 */        /* 1023*2^20 - 68243 */
 
-__inline double fast_exp (double y)
+double inline __attribute__((always_inline)) fast_exp (double y)
 {
     union
     {
diff --git a/skimage/restoration/_nl_means_denoising.pyx b/skimage/restoration/_nl_means_denoising.pyx
index 6528be32..99903c67 100644
--- a/skimage/restoration/_nl_means_denoising.pyx
+++ b/skimage/restoration/_nl_means_denoising.pyx
@@ -10,6 +10,7 @@ ctypedef np.float64_t IMGDTYPE
 
 cdef double DISTANCE_CUTOFF = 5.0
 
+
 cdef extern from "fast_exp.h":
     double fast_exp(double y) nogil
```

**Comment by hmaarrfk** [comment]
probably some gcc 8.3 issue.

**Comment by hmaarrfk** [comment]
@hongquan if you could try this patch I would be greatful
https://github.com/scikit-image/scikit-image/pull/3883
I would much prefer a cython implementation, than adding a bunch of `inline` statements in a "python" project.

**Comment by hongquan** [comment]
@hmaarrfk 

Failed to build scikit-image:

```
# python3 setup.py build_ext -i
Partial import of skimage during the build process.
Traceback (most recent call last):
  File "/Host/Build/scikit-image/skimage/_build.py", line 43, in cython
    from Cython import __version__
ModuleNotFoundError: No module named 'Cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 243, in <module>
    **extra
  File "/usr/lib/python3.6/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 156, in configuration
    config.add_subpackage('skimage')
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "skimage/setup.py", line 9, in configuration
    config.add_subpackage('_shared')
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "skimage/_shared/setup.py", line 18, in configuration
    'interpolation.pyx'], working_path=base_path)
  File "/Host/Build/scikit-image/skimage/_build.py", line 52, in cython
    for f in pyx_files]
  File "/Host/Build/scikit-image/skimage/_build.py", line 52, in <listcomp>
    for f in pyx_files]
  File "/Host/Build/scikit-image/skimage/_build.py", line 26, in _compiled_filename
    CYTHON_VERSION)
RuntimeError: Cython >= 0.23.4 is required to build scikit-image from git checkout
```

I'm using Alpine OS 3.9 and its Cython is only for [Python 2](https://pkgs.alpinelinux.org/contents?branch=v3.9&name=cython&arch=x86_64&repo=main). May be this is the cause.

**Comment by hmaarrfk** [comment]
on your alpine image, i was able to build cython from source.

You have to type `pip3 install cython` yourself before installing scikit-image.

There are some automated ways to do this, but eventually we found too many issues with this, and decided that "developers" either knew how to ask questions on github, or would figure out how to install cython somehow.

**Comment by hongquan** [comment]
I installed cython and build scikit-image on your branch:

```
# git status
On branch fast_exp_2
Your branch is up to date with 'origin/fast_exp_2'.

nothing to commit, working tree clean
```

But after building and installing scikit-image, `fast_exp` is still missing

```py
>>> import skimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Host/Build/scikit-image/skimage/__init__.py", line 133, in <module>
    from .data import data_dir
  File "/Host/Build/scikit-image/skimage/data/__init__.py", line 16, in <module>
    from ._binary_blobs import binary_blobs
  File "/Host/Build/scikit-image/skimage/data/_binary_blobs.py", line 2, in <module>
    from ..filters import gaussian
  File "/Host/Build/scikit-image/skimage/filters/__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "/Host/Build/scikit-image/skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "/Host/Build/scikit-image/skimage/restoration/__init__.py", line 10, in <module>
    from .non_local_means import denoise_nl_means
  File "/Host/Build/scikit-image/skimage/restoration/non_local_means.py", line 2, in <module>
    from ._nl_means_denoising import (
  File "skimage/restoration/_nl_means_denoising.pyx", line 1, in init skimage.restoration._nl_means_denoising
    #cython: initializedcheck=False
ModuleNotFoundError: No module named 'skimage._shared.fast_exp'
```

**Comment by hmaarrfk** [comment]
@hongquan Ok the new fix in 
https://github.com/conda-forge/numba-feedstock/pull/27

is one I am personally happy with, but it will still have to go through the review process.

Not sure if you got things compiling for yourself yet, but it should pass tests now.

Best of luck with alpine linux!

**Comment by hongquan** [comment]
Hi @hmaarrfk Please explain what to do with conda-forge/numba-feedstock#27.
I found no change of _scikit-image_ source code in that PR.

**Comment by hmaarrfk** [comment]
thats a numba related issue on conda-forge. they had temporarily force the version of numpy to be 1.15 which was doing strange to your conda environment when you tried to install it.
