### ISSUE TITLE
ImportError: No module named skimage.io

### ISSUE THREAD

**Issue by dujinyu** [scikit-image/scikit-image#4304]
## Description
I have had successfully compile the caffe, but when i import  caffe in python2.7, I encounter the problem "ImportError: No module named skimage.io" , so I try to pip install scikit-image==0.14.0. but it still raise error.
err Info is listed.
```bash
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-DM8uCI/PyWavelets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-DM8uCI/PyWavelets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-DM8uCI/PyWavelets/pip-egg-info
         cwd: /tmp/pip-install-DM8uCI/PyWavelets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-DM8uCI/PyWavelets/setup.py", line 24, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
official doc says that v0.14.0 is the last version that support python2.7。why?

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
>>> from __future__ import print_function
>>> import sys; print(sys.version)
2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0]
>>> import platform; print(platform.platform())
Linux-5.0.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named skimage
```
when i import numpy in the vscode integrated terminal,  it raised importError,
```
ImportError: No module named skimage
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "io/__init__.py", line 83, in <module>
    from matlab import loadmat, savemat, byteordercodes
  File "io/matlab/__init__.py", line 11, in <module>
    from mio import loadmat, savemat
  File "io/matlab/mio.py", line 14, in <module>
    from miobase import get_matfile_version, docfiller
  File "io/matlab/miobase.py", line 15, in <module>
    from scipy.misc import doccer
  File "/home/vector/.local/lib/python2.7/site-packages/scipy/__init__.py", line 73, in <module>
    from numpy.random import rand, randn
  File "/usr/local/lib/python2.7/dist-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "numpy.pxd", line 92, in init mtrand (numpy/random/mtrand/mtrand.c:35952)
AttributeError: 'module' object has no attribute 'dtype'
```
but dramatically import numpy successfully in ubuntu bash terminal.
thanks to any help.

**Comment by hmaarrfk** [comment]
Did you ever type `sudo pip`???

**Comment by dujinyu** [comment]
> Did you ever type `sudo pip`???

of cause, I even reinstall python2, it still doesn't work.
just now, i analyse the err info, i guess that maybe the err is cause by the version of  PyWavelets.
my partner installed the scikit-image successfully in python2 on windows 10, so i ask him to check which version of PyWavelets, its version is 1.0.3, but when  i install scikit-image==1.14.x, the PyWavelets version is 1.1.x

**Comment by hmaarrfk** [comment]
> of cause, I even reinstall python2, it still doesn't work.

Basically, typing `sudo pip` is almost guaranteed to destroy not only your installation of python, but your whole operating system.

The reason is that Ubuntu expects very specific versions to be installed and you've just installed much newer ones.

I realize now that the instructions: https://scikit-image.org/docs/stable/install.html
Don't really give a warning about that.

You should always type at least
```
pip install --user ....
```
(no sudo there)


I think the instructions
https://scikit-image.org/docs/stable/contribute.html#build-environment-setup

Are much better (shameless plug).

After you create your virtual env, please type `pip install scikit-image` and it should do the rest for you.

Finally, are you specifically trying to use Python 2????

**Comment by hmaarrfk** [comment]
I know installing python (or any science software) is hard.

For what it is worth, I'm really trying to improve how things are installed. 

Do followup with any issues you have with your install (operating system or just scikit-image). Happy to help how I can, though I'm crossing my fingers that your system python isn't broken :dancer:

**Comment by jni** [comment]
@hmaarrfk "sudo pip" was a factor here, but I think a bigger factor might be that installing on Py2.7 was broken. I guess it's because the OS version of pip must be quite old, because I can't install a newer PyWavelets than 1.0.3 on my machine, when creating a new Py2.7 environment.

@dujinyu sorry, working with Python can be hard, because the Python version required by the OS is often not the Python version that you want to do your work in. The community has created "environments" for this, which is a way of having multiple different Python installations on your machine. As @hmaarrfk has noted, you don't typically want to mess with the version that your OS ships, including the libraries that come with it.

To get a functional scikit-image install, I suggest you read about conda environments [here](https://kaust-vislab.github.io/introduction-to-conda-for-data-scientists/) and then using such an environment in which to install scikit-image.

I am going to close this for now, since it's not caused a bug in scikit-image, but feel free to continue asking questions until your installation problems are resolved, and we will do our best to help!

**Comment by jni** [comment]
In other news, Caffe depends on scikit-image? That's pretty cool! :sweat_smile:

**Comment by hmaarrfk** [comment]
At some point, pywavelets had the wrong metadata for the package. We noticed it when an other user couldn't install scikit-image on python 2.7.

```
python2 -m pip install scikit-image
```
(no sudo)

should give you a valid install.

<details> <summary> Valid install with python 2 </summary>

```
(base) $ conda create --name py2 python=2 --yes
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/mark/miniconda3/envs/py2

  added / updated specs:
    - python=2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-41.6.0          |           py27_1         625 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         625 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.9.11-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.9.11-py27_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  pip                conda-forge/linux-64::pip-19.3.1-py27_0
  python             conda-forge/linux-64::python-2.7.15-h5a48372_1009
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-41.6.0-py27_1
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.9-hed695b0_1003
  wheel              conda-forge/linux-64::wheel-0.33.6-py27_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006



Downloading and Extracting Packages
setuptools-41.6.0    | 625 KB    | ############################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) $ conda activate py2
(py2) mark@mark-xps:~$ python2 -m pip install scikit-image
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting scikit-image
  Downloading https://files.pythonhosted.org/packages/bb/7f/d27fadff2c2b8cd45fffe44330b3f26014e94e856d4b61e5bfd2701b1ccb/scikit_image-0.14.5-cp27-cp27mu-manylinux1_x86_64.whl (25.5MB)
     |████████████████████████████████| 25.5MB 6.4MB/s 
Processing ./.cache/pip/wheels/68/f8/29/b53346a112a07d30a5a84d53f19aeadaa1a474897c0423af91/networkx-2.2-py2.py3-none-any.whl
Collecting cloudpickle>=0.2.1
  Downloading https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
Collecting six>=1.10.0
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting pillow>=4.3.0
  Downloading https://files.pythonhosted.org/packages/1b/08/ff620ef5a6128ee6e7a505f5716f81fce7b71f3a69e99646ebe64e0b9984/Pillow-6.2.1-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 1.8MB/s 
Collecting matplotlib>=2.0.0
  Using cached https://files.pythonhosted.org/packages/32/6b/0368cfa5e1d1ae169ab7dc78addda3fd5e6262e48d7373a9114bac7caff7/matplotlib-2.2.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy>=0.17.0
  Using cached https://files.pythonhosted.org/packages/1d/f6/7c16d60aeb3694e5611976cb4f1eaf1c6b7f1e7c55771d691013405a02ea/scipy-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting PyWavelets>=0.4.0
  Using cached https://files.pythonhosted.org/packages/fa/f1/81d3ba0b461699a5e0dbd1a1c2c98c0b5a2e1757b7a54d49246e0a557aea/PyWavelets-1.0.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting decorator>=4.3.0
  Using cached https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.1
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Processing ./.cache/pip/wheels/68/39/1a/5e402bdfdf004af1786c8b853fd92f8c4a04f22aad179654d1/subprocess32-3.5.4-cp27-cp27mu-linux_x86_64.whl
Collecting cycler>=0.10
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache
  Downloading https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Collecting pytz
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
     |████████████████████████████████| 512kB 24.8MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl
Collecting numpy>=1.7.1
  Downloading https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
     |████████████████████████████████| 17.0MB 8.0MB/s 
Collecting kiwisolver>=1.0.1
  Using cached https://files.pythonhosted.org/packages/3d/78/cb9248b2289ec31e301137cedbe4ca503a74ca87f88cdbfd2f8be52323bf/kiwisolver-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: setuptools in ./miniconda3/envs/py2/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->scikit-image) (41.6.0.post20191101)
Installing collected packages: decorator, networkx, cloudpickle, six, pillow, python-dateutil, subprocess32, cycler, backports.functools-lru-cache, pytz, pyparsing, numpy, kiwisolver, matplotlib, scipy, PyWavelets, scikit-image
Successfully installed PyWavelets-1.0.3 backports.functools-lru-cache-1.6.1 cloudpickle-1.2.2 cycler-0.10.0 decorator-4.4.1 kiwisolver-1.1.0 matplotlib-2.2.4 networkx-2.2 numpy-1.16.5 pillow-6.2.1 pyparsing-2.4.5 python-dateutil-2.8.1 pytz-2019.3 scikit-image-0.14.5 scipy-1.2.2 six-1.13.0 subprocess32-3.5.4
(py2) mark@mark-xps:~$ python2 -c "import skimage; print(skimage.__version__)"
0.14.5
```
</details>

**Comment by jni** [comment]
@hmaarrfk indeed, but the bad version of PyWavelets is gone from PyPI. I think what's happening here is that old versions of pip don't even look at the Python version metadata. This is why our setup.py still has a Python3-only warning. The below *should* work with old versions of pip:

```
python2 -m pip install scikit-image==0.14.* PyWavelets==1.0.3 numpy==1.16.*
```

But, I might be forgetting some other Python3-only dependencies...

**Comment by hmaarrfk** [comment]
yes, that is correct.
