### ISSUE TITLE
from skimage import io,transform  Errors

### ISSUE THREAD

**Issue by spot92** [scikit-image/scikit-image#4317]
## Description
I am trying to do the following:
```
from skimage import io,transform
```
But I am receiving multiple errors.

## Version information
```
Python: 3.6.5
skimage: 0.16.2
numpy: 1.15.3
```
# Paste the output of the following python commands
```
from __future__ import print_function
import sys; print(sys.version)
3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]

import platform; print(platform.platform())
Windows-10-10.0.18362-SP0

import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2

import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.15.3

I realize the skimage and numpy is redundant, but I am just following the format.





**Error output:**

C:\Users\lukec\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\external\tifffile\tifffile.py:305: UserWarning: ImportError: No module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "ImportError: No module named '_tifffile'. "
Traceback (most recent call last):
  File "linear_color_transfer.py", line 4, in <module>
    from skimage import io,transform,img_as_float
  File "C:\Users\lukec\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\__init__.py", line 2, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "C:\Users\lukec\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\hough_transform.py", line 2, in <module>
    from ._hough_transform import (_hough_circle,
  File "__init__.pxd", line 918, in init skimage.transform._hough_transform
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

```
I have tried looking around the internet as well as going to the files and looking to see what is going on, but to no avail.

**Comment by hmaarrfk** [comment]
wow, this is exactly: https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024

can you update numpy?

**Comment by hmaarrfk** [comment]
^^^^ I'm quite shocked somebody else ran into the issue. It should be fixed in a new release of scikit-image, but we haven't gone through the process yet.

**Comment by spot92** [comment]
pip install --upgrade scikit-image imageio numpy scipy

That fixed it.
