### ISSUE TITLE
io.imread crashes on 0.16.0 but not on 0.15.0

### ISSUE THREAD

**Issue by milinddeore** [scikit-image/scikit-image#4391]
## Description
I have python code embedded inside c++ code. Its basically, downloading the images from network, and later user them to load for further processing using below code. It crashes on **0.16.0** but works on **0.15.0** version of **skimage** with python 3.7

--- Update ---
It works with python2.7 with skimage version 0.14.5.

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage
>>> skimage.__version__
'0.14.5'
>>> quit()
mdeore@mdeore-Lenovo:~/clone/cboxer-server-native/server$ python3
Python 3.7.6 (default, Dec 19 2019, 23:49:42)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage
>>> skimage.__version__
'0.15.0'
>>>
```
---

## Way to reproduce
```
from skimage import io

def prewhiten(img):
    logger.debug('Image path : {0}'.format(img))
    if not os.path.isfile(img):
        logger.error('File does not exists!!!')
        return 0
    try:
        x = io.imread(img)                 <<<<<<<<<<<< crash block
    except:
        logger.error('Image is corrupt!')
        return 0
    mean = np.mean(x)
    std = np.std(x)
    std_adj = np.maximum(std, 1.0/np.sqrt(x.size))
    y = np.multiply(np.subtract(x, mean), 1/std_adj)
    return y
```

Images is proper and not corrupt, because i verified it post crash on python shell. Even if it is corrupt for any other problem, i have `try` block, it should not crash. Works like charm on 0.15.0 version of skimage for python 3.7. 

# Crash log
```
# The log looks something like:

Jan  8 17:04:33 mdeore-Lenovo kernel: [8985055.390229] cboxerserver[8794]: segfault at ffffffffffffffff ip 00007fbffa51d611 sp 00007ffecffd4c80 error 5 in libpython2.7.so.1.0[7fbffa389000+2f2000]

# When i ran it inside GDB, i got to the function which cased this crash. 

(gdb) bt
#0  0x00007ffff210d51a in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#1  0x00007ffff214e7e6 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#2  0x00007ffff21371e5 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#3  0x00007ffff210d340 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#4  0x00007ffff21371e5 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#5  0x00007ffff210d340 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#6  0x00007ffff214e8ec in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#7  0x00007ffff209062a in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#8  0x00007ffff209172e in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#9  0x00007ffff2151076 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#10 0x00007ffff217c9a8 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#11 0x00007ffff2096485 in _PyEval_EvalFrameDefault () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#12 0x00007ffff2090c6f in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#13 0x00007ffff209172e in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#14 0x00007ffff2151076 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#15 0x00007ffff217c9a8 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#16 0x00007ffff2096485 in _PyEval_EvalFrameDefault () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#17 0x00007ffff2090c6f in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#18 0x00007ffff209172e in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#19 0x00007ffff2151076 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#20 0x00007ffff217c9a8 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#21 0x00007ffff2096485 in _PyEval_EvalFrameDefault () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#22 0x00007ffff2090c6f in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#23 0x00007ffff209135c in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#24 0x00007ffff2097563 in _PyEval_EvalFrameDefault () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#25 0x00007ffff208fa63 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#26 0x00007ffff2091085 in _PyFunction_FastCallDict () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#27 0x00007ffff217c211 in _PyObject_FastCallDict () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#28 0x00007ffff217c348 in PyObject_CallFunctionObjArgs () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#29 0x0000555555563163 in FaceClassifierServer::load_input_images (this=0x555555791ff0, start_index=0, end_index=10, unknown=false) at face_classifier_server_core.cpp:195
#30 0x000055555555baee in cboxer_process (userIds=std::vector of length 8, capacity 8 = {...}) at face_classifier_server_api.cpp:117
#31 0x000055555555c674 in main (argc=1, argv=0x7fffffffe2f8) at face_classifier_server_api.cpp:301
(gdb) f 29
#29 0x0000555555563163 in FaceClassifierServer::load_input_images (this=0x555555791ff0, start_index=0, end_index=10, unknown=false) at face_classifier_server_core.cpp:195
195				pReturn = PyObject_CallFunctionObjArgs(this->pPrewhitenFunc, py_imagePath, NULL);
(gdb) quit

```

**Comment by jni** [comment]
@milinddeore Neither scikit-image 0.15 nor 0.16 should be able to run on Python 2.7 at all, so it's pretty strange that it works at all. How did you build scikit-image binaries? What OS, compiler, and compiler flags are you using?

Are you able to share a minimal example, with an example image that crashes the process like this? Without being able to reproduce the crash, it's going to be very difficult to fix this.

... If it is indeed a fix that needs to happen on our end... It's not obvious to me that the error is not in how Python is being invoked...?

**Comment by milinddeore** [comment]
@jni Apologies, its my bad. I have updated the above PR with 'Updated' section where python2.7 with skimage version (0.14.5) works fine.

**Comment by sciunto** [comment]
I'm closing this issue as we do not know enough to be able to reproduce and fix it. If you have more, please reopen.
