### ISSUE TITLE
cythonizing fails with cython master branch

### ISSUE THREAD

**Issue by tacaswell** [scikit-image/scikit-image#4545]
It fails while trying to re-release the GIL.  Things cythonize without exception using cython 0.29 so I am reporting this here as I suspect that this is a result of cython getting stricter about re-entrant gil releaseing.

I have snipped to what I think is the relevant section of the build log:

```
   ....
   [1/1] Cythonizing /tmp/pip-req-build-uzsw5x6g/skimage/morphology/_skeletonize_3d_cy.pyx
    warning: skimage/morphology/_flood_fill_cy.pyx:14:0: Dotted filenames ('../morphology/_queue_with_history.pxi') are deprecated. Please use the normal Python package directory layout.
    warning: skimage/morphology/_flood_fill_cy.pyx:40:6: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    warning: skimage/morphology/_flood_fill_cy.pyx:40:6: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    warning: skimage/morphology/_flood_fill_cy.pyx:89:6: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    warning: skimage/morphology/_flood_fill_cy.pyx:89:6: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:66:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            QueueWithHistory queue
            QueueItem current_index, neighbor

        with nogil:
            ^
    ------------------------------------------------------------

    skimage/morphology/_flood_fill_cy.pyx:121:9: Trying to release the GIL while it was previously released.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-uzsw5x6g/setup.py", line 190, in <module>
        setup(
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-req-build-uzsw5x6g/setup.py", line 152, in configuration
        config.add_subpackage('skimage')
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/setup.py", line 21, in configuration
        config.add_subpackage('morphology')
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage/morphology/setup.py", line 21, in configuration
        cython(['_flood_fill_cy.pyx'], working_path=base_path)
      File "/tmp/pip-req-build-uzsw5x6g/skimage/_build.py", line 65, in cython
        cythonize(pyx_files, nthreads=cpu_count(),
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1099, in cythonize
        cythonize_one(*args)
      File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1222, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: /tmp/pip-req-build-uzsw5x6g/skimage/morphology/_flood_fill_cy.pyx
    Compiling /tmp/pip-req-build-uzsw5x6g/skimage/morphology/_flood_fill_cy.pyx because it changed.
    [1/1] Cythonizing /tmp/pip-req-build-uzsw5x6g/skimage/morphology/_flood_fill_cy.pyx
```

**Comment by hmaarrfk** [comment]
hmm nice.

Those two functions `_flood_fill_equal` and `_flood_fill_tolerage` seem to only be called from python. It doesn't seem like they should have been declared as being `nogil` safe in the first place.

I think remove the qualifier `nogil` in the function definition should be enough to fix this warning.

**Comment by tacaswell** [comment]
Is it better to remove the function level nogil or the context manager?

Sorry to steal a good first issue, but I want to un-break my personal environment.

**Comment by hmaarrfk** [comment]
I guess i'm agnostic to the change. whichever makes sense to you.
