### ISSUE TITLE
Built-images in `data` module don't work [Windows]

### ISSUE THREAD

**Issue by LaurentRDC** [scikit-image/scikit-image#4574]
## Description

Hello,

I'm trying to load one of the built-in images from the `data` module, but it appears to fail inexplicably.

## Way to reproduce
With a fresh install of scikit-image:

```python
from skimage.data import camera
camera()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\skimage\data\__init__.py", line 109, in camera
    return _load("camera.png")
  File "C:\Miniconda3\lib\site-packages\skimage\data\__init__.py", line 96, in _load
    return imread(_os.path.join(data_dir, f), plugin='pil', as_gray=as_gray)
  File "C:\Miniconda3\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Miniconda3\lib\site-packages\skimage\io\manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 36, in imread
    return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
  File "C:\Miniconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 66, in pil_to_ndarray     
    image.seek(i)
  File "C:\Miniconda3\lib\site-packages\PIL\PngImagePlugin.py", line 748, in seek
    self._seek(f)
  File "C:\Miniconda3\lib\site-packages\PIL\PngImagePlugin.py", line 791, in _seek
    cid, pos, length = self.png.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

For the record, the files (e.g. 'camera.png') are located where I would expect them to be, in the `data` folder.

## Version information
```python
>>> import sys; print(sys.version)
3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.18.1
```

**Comment by sciunto** [comment]
This is due to the recent issues with pillow. Please, downgrade to pillow < 7.1.0.

**Comment by sciunto** [comment]
Also, in the next versions, we will not enforce the use of pillow to read our data #4560

**Comment by LaurentRDC** [comment]
I'm looking at pillow's [issues](https://github.com/python-pillow/Pillow/issues) but there doesn't seem to be anything related. Do you know which issue in particular?

**Comment by sciunto** [comment]
You can check, but I guess that it's due to https://github.com/python-pillow/Pillow/issues/4509 Your issue will be solved if you downgraded (I tested it).

**Comment by LaurentRDC** [comment]
Yes indeed, thank you!

**Comment by hugovk** [comment]
Pillow 7.1.2 was released yesterday and has a fix for https://github.com/python-pillow/Pillow/issues/4509.

**Comment by sciunto** [comment]
Thanks @hugovk
