### ISSUE TITLE
skimage.image's ransac function does not handle well when best_inliers are all False

### ISSUE THREAD

**Issue by jimlinntu** [scikit-image/scikit-image#4816]
## Description

`ransac` routine is supposed to handle well on arbitrary data input.
However, when the best sample model regards all data points as all outliers, `ransac` routine will fail immediately after this line because the `best_inliers` are all `False`:
https://github.com/scikit-image/scikit-image/blob/34c2809ab509acd4e34a0a8c5530588adf0e68e7/skimage/measure/fit.py#L873

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!

import numpy as np
from numpy.polynomial import Polynomial as Poly
from skimage.measure import ransac

class LinearXModel(object):
    def estimate(self, data):
        self.params = Poly.fit(data[:, 1], data[:, 0], 1, domain=[-1, 1])
        return True

    def residuals(self, data):
        return abs(self.params(data[:, 1]) - data[:, 0])

def main():
    data = np.array(
      [[ 943. , 1374.5],
       [1518. , 3293.5],
       [ 749. , 3450.5],
       [2237. , 3578.5],
       [1022. , 3668.5]], dtype=np.float64)
    model, inliers = ransac(data, LinearXModel, 3, 2.2, random_state=1523427)

if __name__ == "__main__":
    main()
```

The output:
```
Traceback (most recent call last):
  File "ransac_bug.py", line 23, in <module>
    main()
  File "ransac_bug.py", line 20, in main
    model, inliers = ransac(data, LinearXModel, 3, 2.2, random_state=1523427)
  File "/home/user/miniconda3/envs/rebook/lib/python3.6/site-packages/skimage/measure/fit.py", line 874, in ransac
    best_model.estimate(*data_inliers)
  File "ransac_bug.py", line 7, in estimate
    self.params = Poly.fit(data[:, 1], data[:, 0], 1, domain=[-1, 1])
  File "/home/user/miniconda3/envs/rebook/lib/python3.6/site-packages/numpy/polynomial/_polybase.py", line 892, in fit
    res = cls._fit(xnew, y, deg, w=w, rcond=rcond, full=full)
  File "/home/user/miniconda3/envs/rebook/lib/python3.6/site-packages/numpy/polynomial/polynomial.py", line 1336, in polyfit
    return pu._fit(polyvander, x, y, deg, rcond, full, w)
  File "/home/user/miniconda3/envs/rebook/lib/python3.6/site-packages/numpy/polynomial/polyutils.py", line 668, in _fit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0]
Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.17.2
numpy version: 1.18.5
```

**Comment by jni** [comment]
Good catch @jimlinntu! We'll need to fix this. If you have the time and inclination, a pull request would be appreciated, but otherwise this might make a good topic for the upcoming SciPy sprint! 😊

**Comment by sciunto** [comment]
Would be good to check this as well: #2698
