### ISSUE TITLE
scikit-image is not installable from source

### ISSUE THREAD

**Issue by kousu** [scikit-image/scikit-image#4919]
## Description

I cannot install skimage from its source tarball on pypi. It fails because numpy.distutils is a build-time dependency, but setup.py does not declare it to be one.

## Way to reproduce
```bash
python -m virtualenv .venv
. .venv/bin/activate
pip install scikit-image@https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
```

As a result, only platforms for which a wheel has been pre-built and posted to https://pypi.org/project/scikit-image/#files can use it. Most platforms are covered, but on python3.9 or macOS 10.12

```
pip install scikit-image
```

fails.

The workaround is to do

```
pip install numpy
pip install scikit-image
```

(`pip install numpy scikit-image` *will not work*: this form of pip installs everything in a batch at the end, after building each, which of course it can't do:

<details>

```
$ pip install numpy scikit-image@https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
Collecting numpy
  Using cached numpy-1.19.1-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
Collecting scikit-image@ https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
  Using cached scikit-image-0.17.2.tar.gz (29.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/kousu/src/neuropoly/.venv36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ab_ucb20/scikit-image/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ab_ucb20/scikit-image/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h6tg6lsv
         cwd: /tmp/pip-install-ab_ucb20/scikit-image/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ab_ucb20/scikit-image/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-install-ab_ucb20/scikit-image/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.2.2 is available.
You should consider upgrading via the '/home/kousu/src/neuropoly/.venv36/bin/python -m pip install --upgrade pip' command.
```
</details> )

but this is weird. It means that I can't really make a package that depends on `scikit-image` where `pip install $pkg` works. Instead I need provide an install script with the workaround, or say that I can only support what your build server supports.

## Version information
```python
# Paste the output of the following python commands
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.6.6 (default, Aug  9 2020, 09:22:17) 
[GCC 10.1.0]
>>> import platform; print(platform.platform())
Linux-5.7.6-arch1-1-x86_64-with-arch
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'skimage'
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

```python
# your output here
$ pip install scikit-image@https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
Collecting scikit-image@ https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
  Using cached scikit-image-0.17.2.tar.gz (29.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/kousu/src/neuropoly/.venv36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2c6ugifd/scikit-image/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2c6ugifd/scikit-image/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m0fs0xn6
         cwd: /tmp/pip-install-2c6ugifd/scikit-image/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2c6ugifd/scikit-image/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-install-2c6ugifd/scikit-image/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.2.2 is available.
You should consider upgrading via the '/home/kousu/src/neuropoly/.venv36/bin/python -m pip install --upgrade pip' command.
```

**Comment by kousu** [comment]
# Problem

```
rm -rf venv; python -m virtualenv venv
. venv/bin/activate

wget https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
pip install scikit-image-0.17.2.tar.gz

deactivate
```

```
[kousu@laptop test]$ rm -rf venv; python -m virtualenv venv
created virtual environment CPython3.8.5.final.0-64 in 454ms
  creator CPython3Posix(dest=/home/kousu/src/neuropoly/scikit-image/test/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[kousu@laptop test]$ . venv/bin/activate
(venv) [kousu@laptop test]$ 
(venv) [kousu@laptop test]$ wget https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
--2020-08-15 12:28:42--  https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.137.63, 2a04:4e42:20::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.137.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29818001 (28M) [application/x-tar]
Saving to: ‘scikit-image-0.17.2.tar.gz’

scikit-image-0.17.2.tar.gz     100%[==================================================>]  28.44M  3.66MB/s    in 7.5s    

2020-08-15 12:28:49 (3.77 MB/s) - ‘scikit-image-0.17.2.tar.gz’ saved [29818001/29818001]

(venv) [kousu@laptop test]$ pip install scikit-image-0.17.2.tar.gz
Processing ./scikit-image-0.17.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/kousu/src/neuropoly/scikit-image/test/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-m3zdjk40/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-m3zdjk40/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6v5mc5ll
         cwd: /tmp/pip-req-build-m3zdjk40/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-m3zdjk40/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/tmp/pip-req-build-m3zdjk40/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/home/kousu/src/neuropoly/scikit-image/test/venv/bin/python -m pip install --upgrade pip' command.
(venv) [kousu@laptop test]$ deactivate

```


# Protoype #1: import scipy's pyproject.toml directly

```
rm -rf venv; python -m virtualenv venv
. venv/bin/activate

mkdir demo
cd demo

wget https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
gunzip scikit-image-0.17.2.tar.gz
(mkdir scikit-image-0.17.2; cd scikit-image-0.17.2; wget https://raw.githubusercontent.com/scipy/scipy/2ed8169c5c4c9181cd38a52db614c692eb802c15/pyproject.toml)
tar -rf scikit-image-0.17.2.tar scikit-image-0.17.2/pyproject.toml 
gzip scikit-image-0.17.2.tar

pip install scikit-image-0.17.2.tar.gz
deactivate
```

```
[kousu@laptop test]$ python -m virtualenv venv
created virtual environment CPython3.8.5.final.0-64 in 322ms
  creator CPython3Posix(dest=/home/kousu/src/neuropoly/scikit-image/test/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[kousu@laptop test]$ . venv/bin/activate
(venv) [kousu@laptop test]$ 
(venv) [kousu@laptop test]$ mkdir demo
(venv) [kousu@laptop test]$ cd demo
(venv) [kousu@laptop demo]$ 
(venv) [kousu@laptop demo]$ wget https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
--2020-08-15 12:02:09--  https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.137.63, 2a04:4e42:20::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.137.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29818001 (28M) [application/x-tar]
Saving to: ‘scikit-image-0.17.2.tar.gz’

scikit-image-0.17.2.tar.gz     100%[==================================================>]  28.44M  3.50MB/s    in 8.4s    

2020-08-15 12:02:17 (3.39 MB/s) - ‘scikit-image-0.17.2.tar.gz’ saved [29818001/29818001]

(venv) [kousu@laptop demo]$ gunzip scikit-image-0.17.2.tar.gz
(venv) [kousu@laptop demo]$ (mkdir scikit-image-0.17.2; cd scikit-image-0.17.2; wget https://raw.githubusercontent.com/scipy/scipy/2ed8169c5c4c9181cd38a52db614c692eb802c15/pyproject.toml)
--2020-08-15 12:02:18--  https://raw.githubusercontent.com/scipy/scipy/2ed8169c5c4c9181cd38a52db614c692eb802c15/pyproject.toml
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.136.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.136.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 533 [text/plain]
Saving to: ‘pyproject.toml’

pyproject.toml                 100%[==================================================>]     533  --.-KB/s    in 0s      

2020-08-15 12:02:18 (9.40 MB/s) - ‘pyproject.toml’ saved [533/533]

(venv) [kousu@laptop demo]$ tar -rf scikit-image-0.17.2.tar scikit-image-0.17.2/pyproject.toml 
(venv) [kousu@laptop demo]$ gzip scikit-image-0.17.2.tar
(venv) [kousu@laptop demo]$ 
(venv) [kousu@laptop demo]$ pip install scikit-image-0.17.2.tar.gz
Processing ./scikit-image-0.17.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting networkx>=2.0
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0
  Using cached Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2020.8.13-py3-none-any.whl (146 kB)
Collecting imageio>=2.3.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting matplotlib!=3.0.0,>=2.0.0
  Downloading matplotlib-3.3.1-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 78 kB/s 
Collecting numpy>=1.15.1
  Using cached numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting scipy>=1.0.1
  Downloading scipy-1.5.2-cp38-cp38-manylinux1_x86_64.whl (25.7 MB)
     |████████████████████████████████| 25.7 MB 1.5 MB/s 
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.1.1-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 3.7 MB/s 
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl (92 kB)
     |████████████████████████████████| 92 kB 50 kB/s 
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: scikit-image
  Building wheel for scikit-image (PEP 517) ... done
  Created wheel for scikit-image: filename=scikit_image-0.17.2-cp38-cp38-linux_x86_64.whl size=34706551 sha256=45b90d62fc991e3c73c3f6551db67d9bdca33d41c7d064b95982d8ca826237dd
  Stored in directory: /home/kousu/.cache/pip/wheels/e8/65/fa/20c68f93bf4b1a3369d06e3e26eb0fde1b61a42c54bf825c52
Successfully built scikit-image
Installing collected packages: decorator, networkx, pillow, numpy, tifffile, imageio, six, cycler, certifi, pyparsing, python-dateutil, kiwisolver, matplotlib, scipy, PyWavelets, scikit-image
Successfully installed PyWavelets-1.1.1 certifi-2020.6.20 cycler-0.10.0 decorator-4.4.2 imageio-2.9.0 kiwisolver-1.2.0 matplotlib-3.3.1 networkx-2.4 numpy-1.19.1 pillow-7.2.0 pyparsing-2.4.7 python-dateutil-2.8.1 scikit-image-0.17.2 scipy-1.5.2 six-1.15.0 tifffile-2020.8.13
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/home/kousu/src/neuropoly/scikit-image/test/venv/bin/python -m pip install --upgrade pip' command.
(venv) [kousu@laptop test]$ deactivate
```


Great, that worked. Now I just need to figure out how to integrate that directly.

**Comment by kousu** [comment]
:trumpet: got it https://github.com/scikit-image/scikit-image/pull/4920
