### ISSUE TITLE
TypeError: unexpected keyword argument: img_num

### ISSUE THREAD

**Issue by alexcwsmith** [scikit-image/scikit-image#4979]
## Description
I have the same error as in this stackoverflow post when trying to concatenate images loaded via imread_collection:
https://stackoverflow.com/questions/62010698/typeerror-unexpected-keyword-argument-img-num

## Way to reproduce
```
load_pattern = '/d2/studies/ClearMap/FosTRAP_ChR2/F2_RT/seg-TrailMap/githubUpload/seg-F2_RT_ChR2_gaus_min*.tif'

stack = io.imread_collection(load_pattern, conserve_memory=False)

im = io.concatenate_images(stack)

```
The same error occurs with:
```
im = stack.concatenate()
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0]
Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.17.2
numpy version: 1.19.1
```
##Traceback:
```python
im = io.concatenate_images(stack)
Traceback (most recent call last):

  File "<ipython-input-8-5e667c801cfc>", line 1, in <module>
    im = io.concatenate_images(stack)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/collection.py", line 47, in concatenate_images
    all_images = [image[np.newaxis, ...] for image in ic]

  File "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/collection.py", line 47, in <listcomp>
    all_images = [image[np.newaxis, ...] for image in ic]

  File "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/collection.py", line 328, in __iter__
    yield self[i]

  File "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/collection.py", line 276, in __getitem__
    self.data[idx] = self.load_func(fname, **kwargs)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))

  File "/home/smith/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())

  File "/home/smith/anaconda3/lib/python3.7/site-packages/imageio/plugins/tifffile.py", line 226, in _open
    self._tf = _tifffile.TiffFile(f, **kwargs)

  File "/home/smith/anaconda3/lib/python3.7/site-packages/tifffile/tifffile.py", line 2608, in __init__
    raise TypeError(f'unexpected keyword argument: {key}')

TypeError: unexpected keyword argument: img_num

```

##Minimal Data to Reproduce (2 images):
Since GitHub apparently doesn't support TIF images, and this is likely an issue with Tifffile, you can access two images here:
https://drive.google.com/drive/folders/1gtwsAPCm2xbhVijjN4-luBlnZ9CIIIxm?usp=sharing

**Comment by jni** [comment]
Yeah the weird thing for me is:

> "/home/smith/anaconda3/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py"

I don't understand why this is going through imageio rather than directly to tifffile. In our own plugin, we change the `img_num` kwarg correctly to `key` as tifffile expects:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/io/_plugins/tifffile_plugin.py#L27-L28

I'll try to investigate. Thank you for the report @alexcwsmith and for the example files!

**Comment by jni** [comment]
Just as a side note, here is a workaround that forces the use of tifffile as the plugin:

```python
from skimage import io

imread_tif = lambda fn: io.imread(fn, plugin='tifffile')
imread_coll_tiff = io.imread_collection_wrapper(imread_tif)
stack2 = imread_coll_tiff('*.tif', conserve_memory=False)
im = io.concatenate_images(stack2)
```

This seems to work. (I get a stack of shape `(2, 2550, 1875)`.) So indeed something fishy is going on with the plugin detection in the default case.

**Comment by jni** [comment]
Ok. I was confused: if you do `io.ImageCollection('*.tif')`, each file will get loaded with `imread` using the appropriate plugin. This is set here:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/io/collection.py#L209-L213

And within `imread`, the first three lines are:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/io/_io.py#L43-L45

which is why I was surprised that imageio was being called! But debugging the above I saw that `self.load_func` was *not* our own imread, it was imageio's! So how did it get set? It's because our own `imread_collection()` does not have such logic: it looks for `imread_collection` plugins, which are a whole different thing!

Fortunately, we *do* have a tifffile imread_collection plugin, so the fix is to write:

```python
from skimage import io

stack = io.imread_collection('*.tif', conserve_memory=False, plugin='tifffile')
im = io.concatenate_images(stack)
```

This works. (Same stack as above.)

I guess the fix is to again change the default plugin when all files in a collection are tiff, same as we do for imread. But @alexcwsmith I hope this last fix is good enough to get you going!

**Comment by jni** [comment]
@scikit-image/core Actually I'm not sure now whether fiddling with the `imread_collection` plugin call order is the right thing. I think the right thing is for `imread_collection` to just call `ImageCollection`, which will call `imread` individually on each file (so each file can be opened by the appropriate plugin). Any thoughts? Happy to implement this if we get consensus.

CC @stefanv

**Comment by alexcwsmith** [comment]
Specifying the plugin works! Thanks very much for looking into this so quickly!
