### ISSUE TITLE
No DLL module _fblas when importing skimage.io

### ISSUE THREAD

**Issue by amirhesam2998** [scikit-image/scikit-image#5011]
Hi
when i run skiamge it works but when i call skimage.io it doesnt work 
how to solve this issue???

my version information :
```
3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
scikit-image version: 0.17.2
numpy version: 1.19.2
```

Error :
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS E:\python_codes> & C:/Users/Hesam/AppData/Local/Programs/Python/Python39/python.exe e:/python_codes/image_pro.py
Traceback (most recent call last):
  File "e:\python_codes\image_pro.py", line 1, in <module>
    import skimage.io
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\io\_io.py", line 4, in <module>      
    from ..color.colorconv import rgb2gray, rgba2rgb
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\color\colorconv.py", line 56, in <module>
    from scipy import linalg
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\linalg\__init__.py", line 194, in <module>
    from .misc import *
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\linalg\misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\Hesam\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\linalg\blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed while importing _fblas: The specified module could not be found.
PS E:\python_codes> 
```

**Comment by amirhesam2998** [comment]
import skimage.io
this is my code

**Comment by lagru** [comment]
This is the crucial bit

> `from scipy.linalg import _fblas`
> `ImportError: DLL load failed while importing _fblas: The specified module could not be found.`

It seems like your Python installation is missing a linear algebra library. So this is not directly a scikit-image related issue but should also happen when calling `from scipy import linalg`.

Do you remember how you installed SciPy? 
Is the [scientific Python distribution Anaconda](https://www.anaconda.com/products/individual) a viable alternative for you? That might be the easiest way to get scientific Python working on your system right now without going into further details.

(I took the liberty to reformat your post a little bit to make it more readable. Hope you don't mind.)

**Comment by amirhesam2998** [comment]
@lagru thank u for make my post readable .
yes i install scipy by windows powershell :
pip install "package address"
scipy-1.5.2-cp39-cp39-win_amd64.whl

**Comment by amirhesam2998** [comment]
@lagru after i reinstall anaconda i cant find anaconda navigtor and that is my problem too

**Comment by amirhesam2998** [comment]
i get same error when i call :
from scipy.linalg import _fblas

**Comment by amirhesam2998** [comment]
i reinstall scipy and it solve thanks @lagru

**Comment by hmaarrfk** [comment]
Nice!

**Comment by codecular** [comment]
Same issue was there for me while running on jupyter lab .  
While running jupyter lab i install it from its terminal .
I restart the kernal and then works for me

**Comment by hmaarrfk** [comment]
Please don’t post on an issue from 2020. 

Please open a new issue filling in all the information we ask for in the template.
