### ISSUE TITLE
MemoryError in computing Convex Hull of a large 3D image

### ISSUE THREAD

**Issue by kushaangupta** [scikit-image/scikit-image#5019]
## Description
While following the discussion [here](https://forum.image.sc/t/convex-hull-of-3d-image-with-sparsely-dispersed-particles/43903), following error was discovered in `skimage.morphology.convex_hull_image`.

## Way to reproduce
[Source](https://forum.image.sc/t/convex-hull-of-3d-image-with-sparsely-dispersed-particles/43903/4)
```python
import numpy as np
from skimage.morphology import convex_hull_image

tmp = np.random.randn(100, 1024, 1024) > 0
ch = convex_hull_image(tmp)
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\skimage\morphology\convex_hull.py", line 89, in convex_hull_image
    coords_in_hull = np.all(hull.equations[:, :ndim].dot(gridcoords) +
MemoryError: Unable to allocate 67.2 GiB for an array with shape (86, 104857600) and data type float64
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.16299-SP0
scikit-image version: 0.17.2
numpy version: 1.18.5
```

**Comment by jni** [comment]
I think this was closed by #5020. Anyone stumbling on the same issue please open a new issue, as further fixes will require additional code.
