### ISSUE TITLE
Store pivchallenge data on gitlab

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#5022]
## Description

I'm seeing a fair number of failed builds due to pivchallenge.org rejecting http requests. I think it is not designed to get hammered by CI builds! 😂 We should contact the authors (this is on my to-do, haven't gotten around to it yet) to ask whether we could host that image ourselves.

example build:

https://travis-ci.org/github/scikit-image/scikit-image/jobs/735724132

```pytb
/home/travis/build/scikit-image/scikit-image/doc/examples/registration/plot_opticalflow.py failed to execute correctly: Traceback (most recent call last):
  File "/home/travis/build/scikit-image/scikit-image/doc/examples/registration/plot_opticalflow.py", line 92, in <module>
    image0 = imageio.imread("http://www.pivchallenge.org/pub/B/B001_1.tif")
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/plugins/tifffile.py", line 222, in _open
    self._f = f = open(self.request.get_local_filename(), "rb")
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/request.py", line 377, in get_local_filename
    shutil.copyfileobj(self.get_file(), file)
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/request.py", line 353, in get_file
    self._file = urlopen(self.filename, timeout=float(timeout))
  File "/home/travis/venv/lib/python3.6/site-packages/imageio/core/util.py", line 34, in urlopen
    return urlopen(*args, **kwargs)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/python/3.6.3/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by sciunto** [comment]
First step of the challenge, get the image :)
