### ISSUE TITLE
when missing intensity_image, regionprop_table fails with less explicit error message than regionprop

### ISSUE THREAD

**Issue by surchs** [scikit-image/scikit-image#5048]
## Description

When [`regionprops_table`](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops_table) is called without the `intensity_image` attribute specified but a property is requested that requires it (e.g. `mean_intensity`), the resulting error message is less explicit than the one from `regionprop`.

## Way to reproduce
Based on the [Measure region properties example](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_label.html#sphx-glr-auto-examples-segmentation-plot-label-py).
```
import logging
from skimage import data, filters, measure, morphology

logger = logging.getLogger(__name__)

img = data.coins()
threshold = filters.threshold_otsu(img)
mask = img > threshold
labels = measure.label(mask)

try:
    table_props = measure.regionprops_table(labels, properties=("mean_intensity",))
except KeyError as e:
    logger.exception("\n!! regionprops_table failed with:\n")

try:
    props = measure.regionprops(labels)
    getattr(props[0], "mean_intensity")
except AttributeError as e:
    logger.exception("\n!! regionprops failed with:\n")

```

Output:
```
!! regionprops_table failed with:
Traceback (most recent call last):
  File "issue_demonstrator.py", line 21, in <module>
    table_props = measure.regionprops_table(labels, properties=("mean_intensity",))
  File "./skimage/measure/_regionprops.py", line 640, in regionprops_table
    return _props_to_dict(regions, properties=properties, separator=separator)
  File "./skimage/measure/_regionprops.py", line 504, in _props_to_dict
    r = regions[0][prop]
  File "./skimage/measure/_regionprops.py", line 397, in __getitem__
    return getattr(self, PROPS[key])
KeyError: 'mean_intensity'

!! regionprops failed with:
Traceback (most recent call last):
  File "issue_demonstrator.py", line 16, in <module>
    getattr(props[0], "mean_intensity")
  File "./skimage/measure/_regionprops.py", line 279, in mean_intensity
    return np.mean(self.intensity_image[self.image])
  File "./skimage/measure/_regionprops.py", line 122, in wrapper
    cache[prop] = f(obj)
  File "./skimage/measure/_regionprops.py", line 261, in intensity_image
    raise AttributeError('No intensity image specified.')
AttributeError: No intensity image specified.
```

## Version information
```
sys.version ='3.8.5 (default, Jul 28 2020, 12:59:40) \n[GCC 9.3.0]'
skimage.__version__ ='0.17.2'
numpy.__version__ ='1.19.4'
platform.platform() ='Linux-5.4.0-52-generic-x86_64-with-glibc2.29'
```

In my opinion, `"No intensity image specified."` is a lot more explicit on how the issue can be fixed than `KeyError: 'mean_intensity'`. It would be great if the `regionprop` error message could be propagated to the `regionprop_table` error.

I have noticed that this behaviour has changed in `0.18.0.dev0`. There, `regionprop_table` raises an `AttributeError` like `regionprop` but both have the less descriptive error message: `"object has no attribute 'mean_intensity'"`. Maybe this should be a separate issue?

**Comment by jni** [comment]
Thanks for the report, @surchs! I agree that the error message needs to be clearer here. I'm unclear about your last point: what is the situation right now on master and how does it compare to what you think the ideal situation would be?

**Comment by surchs** [comment]
Hey @jni. On master the situation is:
```
!! regionprops_table failed with:
Traceback (most recent call last):
  File "issue_demonstrator.py", line 19, in <module>
    table_props = measure.regionprops_table(labels, properties=("mean_intensity",))
  File "./scikit-image/skimage/measure/_regionprops.py", line 862, in regionprops_table
    return _props_to_dict(
  File "./scikit-image/skimage/measure/_regionprops.py", line 671, in _props_to_dict
    rp = getattr(r, prop)
  File "./scikit-image/skimage/measure/_regionprops.py", line 271, in __getattr__
    raise AttributeError(
AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'mean_intensity'

!! regionprops failed with:
Traceback (most recent call last):
  File "issue_demonstrator.py", line 14, in <module>
    getattr(props[0], "mean_intensity")
  File "./scikit-image/skimage/measure/_regionprops.py", line 271, in __getattr__
    raise AttributeError(
AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'mean_intensity'
```
That is, on master, `regionprop` and `regionprop_table` have the same error and error message. But I think that the previous error message (`AttributeError: No intensity image specified.`) was more explicit. That said, I am not sure why the current error message is raised in master as there seems to be [an even more explicit error message set up for this situation](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py#L261). Let me know if this (the error message in master) should be a separate issue.
