### ISSUE TITLE
Building from source on master fails on Windows 10.0.19041

### ISSUE THREAD

**Issue by FirefoxMetzger** [scikit-image/scikit-image#5091]
## Description

On Python 3.9 building from source on Windows fails with the error below. On Python 3.7 the build works fine.

The reason appears to be a bug in the windows binary `ucrtbase.dll` that was updated in the recent (Oct 2020) Windows update. This causes numpy to fail on windows. Here is the accompanying bug report on the Windows Dev Forums: https://developercommunity.visualstudio.com/content/problem/1208774/fpu-exception-in-fmod0-x-in-windows-10-version-200.html

The bug report suggests using the previous version of numpy (`1.19.3`) as a workaround; however, this doesn't seem to be enough for us.

## Way to reproduce
```bash
git clone git@github.com:scikit-image/scikit-image.git
cd scikit-image && pip install -e .
```

#### Current Result
<details>
  <summary>>`C:\Python39\python.exe -m pip install -e .`</summary>
  
  ```
Obtaining file:///C:/Users/Sebastian/Desktop/test/scikit-image
  Installing build dependencies ... done
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python39\python.exe' 'C:\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\SEBAST~1\AppData\Local\Temp\tmpn4se5hkm'
       cwd: C:\Users\Sebastian\Desktop\test\scikit-image
  Complete output (22 lines):
  Traceback (most recent call last):
    File "C:\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 168, in <module>
      from numpy.distutils.core import setup
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "C:\Users\Sebastian\AppData\Local\Temp\pip-build-env-arg1yqp5\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('C:\\Users\\Sebastian\\AppData\\Local\\Temp\\pip-build-env-arg1yqp5\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python39\python.exe' 'C:\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\SEBAST~1\AppData\Local\Temp\tmpn4se5hkm' Check the logs for full command output.
```
</details>

#### Expected Result
`Successfully Installed scikit-image-0.18.0.dev0`

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
# scikit-image failed to install
numpy version: 1.19.3
```

for comparison my python37 setup
```python
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
scikit-image version: 0.18.0.dev0
numpy version: 1.19.3
```

**Comment by emmanuelle** [comment]
Thanks for reporting this @FirefoxMetzger . The wheels build fine on Windows and Python 3.9 in Github Actions https://github.com/scikit-image/scikit-image/runs/1462630342, do you know what could be different compared to your setup?

**Comment by FirefoxMetzger** [comment]
@emmanuelle Good question, my guess is a difference in Windows versions. The automated build uses `Microsoft Windows Server 2019 10.0.17763`, I think that (1) the faulty library may not have been rolled out to servers yet, and (2) the server may not have been upgraded to use the latest (and faulty) version.

**Comment by stefanv** [comment]
We've switched the underlying build system to Meson since this issue was filed, so @FirefoxMetzger if you could try building with clang (not MSVC) on Windows, we can open a new issue for any failures that arise.
