### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage.filters._sparse_cy'

### ISSUE THREAD

**Issue by wang88888** [scikit-image/scikit-image#5215]
## Description
when i use the fuction skimage.feature.greycomatrix,
pycharm error:ModuleNotFoundError: No module named 'skimage.filters._sparse_cy',
the version of skimage:  0.18.1

## Code:
from skimage.feature import greycomatrix, greycoprops
import cv2
img_org = cv2.imread('train_video/frame/tr_123.jpg')
result = skimage.feature.greycomatrix(img_org, [1], [0, np.pi/2], levels=4)

#Output:
Traceback (most recent call last):
  File "D:/thomas/py_code/test_4.py", line 7, in <module>
    from skimage.feature import greycomatrix, greycoprops
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\feature\__init__.py", line 3, in <module>
    from ._canny import canny
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\feature\_canny.py", line 18, in <module>
    from ..filters import gaussian
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\filters\__init__.py", line 12, in <module>
    from .thresholding import (threshold_local, threshold_otsu, threshold_yen,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\filters\thresholding.py", line 14, in <module>
    from ._sparse import correlate_sparse, _validate_window_size
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\filters\_sparse.py", line 2, in <module>
    from ._sparse_cy import _correlate_sparse_offsets
ModuleNotFoundError: No module named 'skimage.filters._sparse_cy'

**Comment by superhy** [comment]
I encounter the same issue when I tried to:
import skimage.feature

in windows, we can not just install it directly by pip.
you need to install the binary compiled Lib from: https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image

or you can install it by Conda:
conda install -c conda-forge scikit-image

Above information is available at the git main page (README.md) of this project.

**Comment by wang88888** [comment]
i installed the binary compiled Lib,it works,thank you

**Comment by jni** [comment]
Hmmm, you *should* be able to install from pip in windows. We also have [compiled versions on PyPI](https://pypi.org/project/scikit-image/#files). Which Windows version do you have, and what version of pip (`pip --version`)? It seems to not be picking up the compiled binary for some reason...
