### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS It seems that scikit-image has not been built correctly.

### ISSUE THREAD

**Issue by xzkzdx** [scikit-image/scikit-image#5457]
Traceback (most recent call last):
  File "/root/.virtualenvs/adnerf/lib/python3.7/site-packages/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_util/process_data.py", line 4, in <module>
    import face_alignment
  File "/root/.virtualenvs/adnerf/lib/python3.7/site-packages/face_alignment/__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "/root/.virtualenvs/adnerf/lib/python3.7/site-packages/face_alignment/api.py", line 4, in <module>
    from skimage import io
  File "/root/.virtualenvs/adnerf/lib/python3.7/site-packages/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)
  File "/root/.virtualenvs/adnerf/lib/python3.7/site-packages/skimage/__init__.py", line 104, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen: cannot load any more object with static TLS
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html

**Comment by grlee77** [comment]
Can you provide more information on your OS and how you are installing scikit-image? 

I have seen this kind of message in the distant past, but am not sure it is an issue with scikit-image itself. This is a lot more discussion for example the following comments and their issues may hold some clues. It sounds like even changing import order can sometimes resolve the issue.

https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-822678559
https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-522218682
https://github.com/pytorch/pytorch/issues/2575#issuecomment-523657178

**Comment by grlee77** [comment]
deleted the discussion (we are moving back to issues), but have not reopened this due to lack of feedback
