### ISSUE TITLE
scikit-image 0.18.2 fails on OS X 10.13.6

### ISSUE THREAD

**Issue by greenonline** [scikit-image/scikit-image#5465]
## Description

This issue would appear to be very similar to [Importing scikit-learn==0.24.0 fails on macOS 10.13: "Symbol not found: ____chkstk_darwin" #19063](https://github.com/scikit-learn/scikit-learn/issues/19063), which was fixed.

Running on OS X High Sierra 10.13.6. On Python 3.7 and 3.9.

The highlight of the error message is this line

```
  Referenced from: /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
```

It appears that binaries built on 10.15 are incompatible with 10.13.6.

## Way to reproduce
```python
# In PyCharm, create new project, add these packages (you actually don't need to manually add all of them, only imgaug and the dependencies will load the rest automatically):

# opencv-python
# matplotlib
# pandas
# sklearn
# imgaug
# tensorflow

# Then create a new Python file with just this line, on its own, and run it. No other code is required to repro the issue
from imgaug import augmenters as iaa
```
this will result in
```
/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/bin/python /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/TestCrash.py
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
ImportError: dlopen(/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/geometry.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/TestCrash.py", line 2, in <module>
    from imgaug import augmenters as iaa
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/imgaug/__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 104, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen(/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/geometry.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 

Process finished with exit code 1
```

## Version information - Python 3.7
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/bin/python /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/CrashInfo.py
3.7.10 (default, May  1 2021, 23:35:31) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Darwin-17.7.0-x86_64-i386-64bit
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
ImportError: dlopen(/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/geometry.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/CrashInfo.py", line 4, in <module>
    import skimage; print("scikit-image version: {}".format(skimage.__version__))
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)
  File "/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/__init__.py", line 104, in _raise_build_error
    %s""" % (e, msg))
ImportError: dlopen(/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/geometry.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/lib/python3.7/site-packages/skimage/_shared/../.dylibs/libomp.dylib
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 

Process finished with exit code 1

```

With this line 
```
# import skimage; print("scikit-image version: {}".format(skimage.__version__))
```

commented out, the output is:

```
/Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/venv/bin/python /Users/macbook/PycharmProjects/SelfDrivingSimulatorv3/CrashInfo.py
3.7.10 (default, May  1 2021, 23:35:31) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Darwin-17.7.0-x86_64-i386-64bit
numpy version: 1.21.0

Process finished with exit code 0
```
## Version information - Python 3.9
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
# import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```
/Users/macbook/PycharmProjects/scikit-image-test/venv3.9/bin/python /Users/macbook/PycharmProjects/scikit-image-test/CrashInfo.py
3.9.4 (default, Apr 17 2021, 22:46:43) 
[Clang 10.0.0 (clang-1000.10.44.4)]
macOS-10.13.6-x86_64-i386-64bit
numpy version: 1.21.0

Process finished with exit code 0
```

----

FWIW, Installing `scikit-image` via the terminal gives the same end result. This output shows the version number at the bottom:
```
pip3 install -U --no-cache-dir --no-binary :all scikit-image
Collecting scikit-image
  Downloading scikit_image-0.18.2-cp37-cp37m-macosx_10_9_x86_64.whl (12.7 MB)
     |████████████████████████████████| 12.7 MB 1.4 MB/s 
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in ./venv/lib/python3.7/site-packages (from scikit-image) (8.3.1)
Requirement already satisfied: tifffile>=2019.7.26 in ./venv/lib/python3.7/site-packages (from scikit-image) (2021.7.2)
Requirement already satisfied: PyWavelets>=1.1.1 in ./venv/lib/python3.7/site-packages (from scikit-image) (1.1.1)
Requirement already satisfied: networkx>=2.0 in ./venv/lib/python3.7/site-packages (from scikit-image) (2.5.1)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in ./venv/lib/python3.7/site-packages (from scikit-image) (3.4.2)
Requirement already satisfied: numpy>=1.16.5 in ./venv/lib/python3.7/site-packages (from scikit-image) (1.21.0)
Requirement already satisfied: imageio>=2.3.0 in ./venv/lib/python3.7/site-packages (from scikit-image) (2.9.0)
Requirement already satisfied: scipy>=1.0.1 in ./venv/lib/python3.7/site-packages (from scikit-image) (1.7.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (2.4.7)
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from cycler>=0.10->matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.16.0)
Requirement already satisfied: decorator<5,>=4.3 in ./venv/lib/python3.7/site-packages (from networkx>=2.0->scikit-image) (4.4.2)
Installing collected packages: scikit-image
Successfully installed scikit-image-0.18.2
(venv) MacBook-Pro-van-Macbook:SelfDrivingSimulatorv3 macbook$ 
```

**Comment by jni** [comment]
Thanks for the references @greenonline! This appears to be the sklearn PR with the fix:

https://github.com/scikit-learn/scikit-learn/pull/19064

Should be reasonably easy to fix in upcoming releases. 🤞

**Comment by hmaarrfk** [comment]
Do we only build with openmp for python 3.9? why is that?

**Comment by hmaarrfk** [comment]
<details>

```patch
diff --git a/.github/workflows/wheel_tests_and_release.yml b/.github/workflows/wheel_tests_and_release.yml
index 7ee991d65..4497a115e 100644
--- a/.github/workflows/wheel_tests_and_release.yml
+++ b/.github/workflows/wheel_tests_and_release.yml
@@ -9,7 +9,6 @@ env:
   CIBW_TEST_REQUIRES: "-r requirements/test.txt"
   CIBW_TEST_COMMAND: pytest --pyargs skimage

-
 jobs:
   build_linux_37_and_above_wheels:
     name: Build python ${{ matrix.cibw_python }} wheels on ${{ matrix.os }}
@@ -59,6 +58,9 @@ jobs:
       fail-fast: false
       matrix:
         os: [macos-latest]
+    env:
+      MACOSX_DEPLOYMENT_TARGET: "10.13"
+

     steps:
       - uses: actions/checkout@v2
@@ -75,7 +77,14 @@ jobs:
           python -m pip install cibuildwheel
       - name: Build wheels for CPython 3.9 and Mac OS
         run: |
-          brew install libomp
+          # Make sure to use a libomp version binary compatible with the oldest
+          # supported version of the macos SDK as libomp will be vendored into the
+          # scikit-learn wheels for macos. The list of bottles can be found at:
+          # https://formulae.brew.sh/api/formula/libomp.json. Currently, the oldest
+          # supported macos version is: High Sierra / 10.13. When upgrading this, be
+          # sure to update the MACOSX_DEPLOYMENT_TARGET environment variable
+          wget https://homebrew.bintray.com/bottles/libomp-11.0.0.high_sierra.bottle.tar.gz
+          brew install libomp-11.0.0.high_sierra.bottle.tar.gz
           python -m cibuildwheel --output-dir dist
         env:
           CIBW_BUILD: "cp39-*"
```
</details>
