### ISSUE TITLE
Constructing Cascade from XML causes segfault

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#5492]
Running [this gallery example](https://scikit-image.org/docs/dev/auto_examples/applications/plot_face_detection.html#sphx-glr-auto-examples-applications-plot-face-detection-py) on [this XML file](https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml) causes a segfault.

```python
from skimage import data
from skimage.feature import Cascade

import matplotlib.pyplot as plt
from matplotlib import patches

# Initialize the detector cascade.
detector = Cascade('haarcascade_frontalface_default.xml')

img = data.astronaut()

detected = detector.detect_multi_scale(img=img,
                                       scale_factor=1.2,
                                       step_ratio=1,
                                       min_size=(60, 60),
                                       max_size=(123, 123))

plt.imshow(img)
img_desc = plt.gca()
plt.set_cmap('gray')

for patch in detected:

    img_desc.add_patch(
        patches.Rectangle(
            (patch['c'], patch['r']),
            patch['width'],
            patch['height'],
            fill=False,
            color='r',
            linewidth=2
        )
    )

plt.show()
```

gdb reports the problem at

```
__Pyx_GetItemInt_Fast (o=0x7fffaef01880, i=1, wraparound=<optimized out>, boundscheck=0, is_list=0) at feature/_cascade.cpp:43232
```

**Comment by grlee77** [comment]
I figured this was likely due to out-of-bounds access somewhere, so I recompiled `_cascade.pyx`, but changing to `boundscheck=True` up to. This results in the following more helpful error:

```
Traceback (most recent call last):
  File "doc/examples/applications/plot_face_detection.py", line 76, in <module>
    detector = Cascade('/home/lee8rx/Downloads/haarcascade_frontalface_default.xml')
  File "skimage/feature/_cascade.pyx", line 471, in skimage.feature._cascade.Cascade.__init__
    self._load_xml(xml_file, eps)
  File "skimage/feature/_cascade.pyx", line 848, in skimage.feature._cascade.Cascade._load_xml
    new_feature = MBLBP(params[1], params[0], params[2], params[3])
IndexError: list index out of range
```

**Comment by grlee77** [comment]
I have no prior experience with this Cascade class in skimage or this feature in OpenCV, but I suspect the root difference is related to the difference in the classifier type used. The `.xml` file bundled in our data package uses 

```xml
<featureType>LBP</featureType>
```

while the XML file in this issue uses
```xml
<featureType>HAAR</featureType>
```

**LBP** = Local Binary Pattern while **HAAR** = Haar-like wavelet features ([reference](https://docs.opencv.org/4.5.2/dc/d88/tutorial_traincascade.html))


Given that the struct where the error in my prior message occurs is named `MBLBP` and its members are integers it would seem our `Cascade` class is only compatible with the LBP feature type. We should definitely try to extract this field from the XML and raise a useful error if HAAR features are encountered instead!
