### ISSUE TITLE
Error of using scikit-image together with pywin32

### ISSUE THREAD

**Issue by timonmerk** [scikit-image/scikit-image#5597]
I experience a strange error, that does not allow me to import skimage _if pywin32 is installed_ (which I require for example to run the venv in jupyter notebook).

## Way to reproduce
First I **CAN** correctly use skimage, with a venv without having pywin32 installed:

> (pyneuromodulation) C:\Users\ICN_admin>python -c "import skimage; print(skimage.__version__)"
> 0.18.3

I then print the python path in that environment:

> np.array(sys.path)
> array(['', 'c:\\nrn\\lib\\python',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\python39.zip',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\DLLs',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages\\Pythonwin',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib\\site-packages'],
>       dtype='<U74')

Please don't mind the np.array, it's only for having the individual entries in separate rows.
Going on, I am now installing pywin32 with `pip install pywin32` :

> Collecting pywin32
>   Using cached pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
> Installing collected packages: pywin32
> Successfully installed pywin32-301

and check the sys.path variables:

> array(['', 'c:\\nrn\\lib\\python',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\python39.zip',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\DLLs',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32',
>        'C:\\Users\\ICN_admin\\AppData\\Roaming\\Python\\Python39\\site-packages\\Pythonwin',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib\\site-packages',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib\\site-packages\\win32',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib\\site-packages\\win32\\lib',
>        'C:\\Users\\ICN_admin\\Anaconda3\\envs\\pyneuromodulation\\lib\\site-packages\\Pythonwin'],
>       dtype='<U79')

Okay, it added some paths in the 'envs\pyneuromodulation' folder there. 

BUT now the weird part, importing skimage gives me suddely this import error:
`import skimage`
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\__init__.py", line 135, in <module>
>     from .data import data_dir
>   File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\data\__init__.py", line 166, in <module>
>     image_fetcher, data_dir = create_image_fetcher()
>   File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\data\__init__.py", line 149, in create_image_fetcher
>     path=pooch.os_cache("scikit-image"),
>   File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\pooch\utils.py", line 99, in os_cache
>     return Path(appdirs.user_cache_dir(project))
>   File "C:\Users\ICN_admin\AppData\Roaming\Python\Python39\site-packages\appdirs.py", line 293, in user_cache_dir
>     path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
>   File "C:\Users\ICN_admin\AppData\Roaming\Python\Python39\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
>     from win32com.shell import shellcon, shell
> ImportError: DLL load failed while importing shell: The specified procedure could not be found.

Do you have any idea where this could come from? I have a feeling that it might be related to the used pythonpath variables, that's why I printed them here.

## Version information
```python
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:37:25) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.19042-SP0
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\__init__.py", line 135, in <module>
    from .data import data_dir
  File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\data\__init__.py", line 166, in <module>
    image_fetcher, data_dir = create_image_fetcher()
  File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\skimage\data\__init__.py", line 149, in create_image_fetcher
    path=pooch.os_cache("scikit-image"),
  File "C:\Users\ICN_admin\Anaconda3\envs\pyneuromodulation\lib\site-packages\pooch\utils.py", line 99, in os_cache
    return Path(appdirs.user_cache_dir(project))
  File "C:\Users\ICN_admin\AppData\Roaming\Python\Python39\site-packages\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Users\ICN_admin\AppData\Roaming\Python\Python39\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.
>>> import numpy; print(f'numpy version: {numpy.__version__}')
numpy version: 1.19.5
```

```python
# your output here

```

**Comment by timonmerk** [comment]
Thanks @hmaarrfk! This solved it :) I will stick with `pip install --user` in future!
