### ISSUE TITLE
Attempts to access numpy array fail

### ISSUE THREAD

**Issue by rogermc2** [scikit-image/scikit-image#6273]
## Description
Attempts to build the following instruction fail:
```
mg = np.array(X[4]).reshape(28,28)
```
## Way to reproduce
Save and build
```python
[index_error.pdf](https://github.com/scikit-image/scikit-image/files/8157922/index_error.pdf)
```

## Version information
```python
3.8.6 (default, Oct 29 2021, 12:03:32) 
[Clang 10.0.0 (clang-1000.11.45.5)]
macOS-10.13.6-x86_64-i386-64bit
scikit-image version: 0.19.2
numpy version: 1.22.2
```
Problem also occurs on my other computer which uses OSX Catalina

# your output here

```url
api/v1/json/data/list/data_name/mnist_784/limit/2/data_version/1
Traceback (most recent call last):
  File "/Users/rogermcmurtrie/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Ada_Projects/machine_learning/great_courses/ML4/lesson4.py", line 6, in <module>
    img = np.array(X[4]).reshape(28,28)
  File "/Users/rogermcmurtrie/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/rogermcmurtrie/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 4
[Finished in 52.3s with exit code 1]
[cmd: ['/Users/rogermcmurtrie/.pyenv/versions/3.8.6/bin/python', '-u', '/Ada_Projects/machine_learning/great_courses/ML4/lesson4.py']]
[dir: /Ada_Projects/machine_learning/great_courses/ML4]
[path: /Users/rogermcmurtrie/.pyenv/versions/3.8.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/gnat/bin:/usr/local/opt/bison/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Ada_Source/alr/bin:/usr/local/Cellar/gtk+3/3.24.23]
```

**Comment by rogermc2** [comment]
Fixed by author of original code
