### ISSUE TITLE
Error importing skimage graph merging helper functions

### ISSUE THREAD

**Issue by d-diaz** [scikit-image/scikit-image#6287]
## Description
Trying to import helper functions from future.graph.graph_merge raises `ImportError: dlopen: cannot load any more object with static TLS`

Full error message: 
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/future/__init__.py", line 8, in <module>
    from . import graph
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/future/graph/__init__.py", line 2, in <module>
    from .rag import rag_mean_color, RAG, show_rag, rag_boundary
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/future/graph/rag.py", line 8, in <module>
    from ... import measure, segmentation, util, color
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/storage/miniconda3/envs/skimage/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/segmentation/__init__.py", line 3, in <module>
    from .active_contour_model import active_contour
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/segmentation/active_contour_model.py", line 6, in <module>
    from ..filters import sobel
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/_shared/lazy.py", line 64, in __getattr__
    submod = importlib.import_module(
  File "/storage/miniconda3/envs/skimage/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/restoration/__init__.py", line 13, in <module>
    from .rolling_ball import rolling_ball, ball_kernel, ellipsoid_kernel
  File "/storage/miniconda3/envs/skimage/lib/python3.10/site-packages/skimage/restoration/rolling_ball.py", line 4, in <module>
    from ._rolling_ball_cy import apply_kernel, apply_kernel_nan
ImportError: dlopen: cannot load any more object with static TLS
```

## Way to reproduce
```
conda create -n skimage -c conda-forge scikit-image
conda activate skimage
python -c 'from skimage.future.graph.graph_merge import _revalidate_node_eges'
```

## Version information
```python
3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:53:57) [GCC 9.4.0]
Linux-3.13.0-162-generic-x86_64-with-glibc2.19
scikit-image version: 0.19.2
numpy version: 1.22.3
```

**Comment by d-diaz** [comment]
A bit further info. If I install `scikit-image<=0.18.2` on my Linux machine I don't get this error. It looks like something in 0.18.3 is where a breaking change was introduced. Same error message as above, stemming from `from ._rolling_ball_cy import apply_kernel, apply_kernel_nan`. 

When I try this on a windows machine, I don't need to specify version (current stable 0.19.2 works without error).

**Comment by hmaarrfk** [comment]
What else do you have in your environment? Do you have a limited RAM machine?

What else are you importing before skimage?

I've seen this before in CIs with very limited RAM (or that was my reasoning)

**Comment by d-diaz** [comment]
Environment and imports are shown above in “Way to reproduce”. RAM is 64GB and not running low.

**Comment by hmaarrfk** [comment]
can you provide the outputs of `conda list` and `pip list`?

On linux, 64 bit, I ran
```
mamba create -n skimage --override-channels --channel conda-forge scikit-image
mamba activate skimage
python -c 'from skimage.future.graph.graph_merge import _revalidate_node_edges'
```
and it worked without error.

<details> 

```
$ mamba list
# packages in environment at /home/mark/mambaforge/envs/skimage:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aom                       3.3.0                h27087fc_1    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-blosc2                  2.0.4                h5f21a17_1    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8       py310hff52083_1    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
charls                    2.3.4                h9c3ff4c_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2          py310h6acc77f_1    conda-forge
dask-core                 2022.3.0           pyhd8ed1ab_0    conda-forge
fonttools                 4.31.1          py310h5764c6d_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
imagecodecs               2022.2.22       py310h8534204_0    conda-forge
imageio                   2.16.1             pyhcf75d05_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.0           py310hbf28c38_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libavif                   0.9.3                h166bdaf_1    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h2283fc2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            11.2.0              h69a702a_14    conda-forge
libgfortran5              11.2.0              h5c6108e_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib-base           3.5.1           py310h23f4a51_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
numpy                     1.22.3          py310h45f3432_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1           py310hb5077e9_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pillow                    9.0.1           py310he619898_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
python                    3.10.2          hc74c709_4_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0           py310hde88566_0    conda-forge
pyyaml                    6.0             py310h6acc77f_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scikit-image              0.19.2          py310hb5077e9_0    conda-forge
scipy                     1.8.0           py310hea5193d_1    conda-forge
setuptools                60.10.0         py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.37.1               h4ff8645_0    conda-forge
tifffile                  2022.3.16          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0          py310h6acc77f_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

```
$ pip list
Package         Version
--------------- ---------
certifi         2021.10.8
cloudpickle     2.0.0
cycler          0.11.0
cytoolz         0.11.2
dask            2022.3.0
fonttools       4.31.1
fsspec          2022.2.0
imagecodecs     2022.2.22
imageio         2.16.1
kiwisolver      1.4.0
locket          0.2.0
matplotlib      3.5.1
munkres         1.1.4
networkx        2.7.1
numpy           1.22.3
packaging       21.3
pandas          1.4.1
partd           1.2.0
Pillow          9.0.1
pip             22.0.4
pyparsing       3.0.7
python-dateutil 2.8.2
pytz            2021.3
PyWavelets      1.3.0
PyYAML          6.0
scikit-image    0.19.2
scipy           1.8.0
setuptools      60.10.0
six             1.16.0
tifffile        2022.3.16
toolz           0.11.2
unicodedata2    14.0.0
wheel           0.37.1
```
</details>

**Comment by d-diaz** [comment]
For an environment that is failing, here's the output of `conda list` ...
```
# packages in environment at /storage/miniconda3/envs/skimage:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aom                       3.3.0                h27087fc_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py310h6acc77f_1003    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-blosc2                  2.0.4                h5f21a17_1    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8       py310hff52083_1    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
charls                    2.3.4                h9c3ff4c_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.1          py310h685ca39_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2          py310h6acc77f_1    conda-forge
dask-core                 2022.2.1           pyhd8ed1ab_0    conda-forge
fonttools                 4.30.0          py310h5764c6d_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.2.22       py310h8534204_0    conda-forge
imageio                   2.16.1             pyhcf75d05_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.0           py310hbf28c38_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libavif                   0.9.3                h166bdaf_1    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            11.2.0              h69a702a_14    conda-forge
libgfortran5              11.2.0              h5c6108e_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib-base           3.5.1           py310h23f4a51_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
numpy                     1.22.3          py310h45f3432_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1           py310hb5077e9_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pillow                    9.0.1           py310he619898_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310hff52083_4    conda-forge
python                    3.10.2          h85951f9_4_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0           py310hde88566_0    conda-forge
pyyaml                    6.0             py310h6acc77f_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scikit-image              0.18.3          py310hb5077e9_1    conda-forge
scipy                     1.8.0           py310hea5193d_1    conda-forge
setuptools                60.10.0         py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.37.1               h4ff8645_0    conda-forge
tifffile                  2022.3.16          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0          py310h6acc77f_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

... and here's the output of `pip list`:
```
Package            Version
------------------ ---------
appdirs            1.4.4
brotlipy           0.7.0
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.12
cloudpickle        2.0.0
cryptography       36.0.1
cycler             0.11.0
cytoolz            0.11.2
dask               2022.2.1
fonttools          4.30.0
fsspec             2022.2.0
idna               3.3
imagecodecs        2022.2.22
imageio            2.16.1
kiwisolver         1.4.0
locket             0.2.0
matplotlib         3.5.1
munkres            1.1.4
networkx           2.7.1
numpy              1.22.3
packaging          21.3
pandas             1.4.1
partd              1.2.0
Pillow             9.0.1
pip                22.0.4
pooch              1.6.0
pycparser          2.21
pyOpenSSL          22.0.0
pyparsing          3.0.7
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2021.3
PyWavelets         1.3.0
PyYAML             6.0
requests           2.27.1
scikit-image       0.18.3
scipy              1.8.0
setuptools         60.10.0
six                1.16.0
tifffile           2022.3.16
toolz              0.11.2
unicodedata2       14.0.0
urllib3            1.26.9
wheel              0.37.1
```

**Comment by hmaarrfk** [comment]
Are you able to try plotting with matplotlib? I believe Tobias might be able to help you, but he seems busy now

**Comment by d-diaz** [comment]
I was able to import pyplot and save a figure as a png. I'm running this on a headless server and don't normally use it to view live graphics from a python console, normally setting up environments like this using jupyter and then forwarding to my local machine, but set this environment up with minimal requirements to reproduce the skimage importing issue. 

The server is running an old version of Ubuntu (14.04.6 Trusty), and I have had some sporadic issues in the past building  non-python programs from source code that required more up-to-date compilers. Speculating there might be some unusual dependencies or issues with compiling the cython that it seems like this depends on, but not quite sure how to isolate that.

**Comment by d-diaz** [comment]
Definitely seems related to running an old version of Ubuntu now. After a colleague and I spent a few hours crawling google and GitHub issues, we came [across this one](https://github.com/vanheeringen-lab/gimmemotifs/issues/102). 

Was able to fix this error by setting an environment variable in the conda environment upon activation:
LD_PRELOAD=${CONDA_PREFIX}/lib/libgomp.so

The longer-term solution is probably upgrading Ubuntu on the machine we're using, but this works for now...

**Comment by grlee77** [comment]
great detective work, @d-diaz. Thanks for reporting back here
