### ISSUE TITLE
`channel_axis` argument in `exposure.histogram` does not always work

### ISSUE THREAD

**Issue by sbinnee** [scikit-image/scikit-image#6412]
## Description

Current `channel_axis` implementation assumes to have the same binning for all channels to `np.stack` before returning. But it fails in most real cases, apparently. This issue was actually raised in #3772 when it was merged. Also [test](https://github.com/scikit-image/scikit-image/blob/6a4083354f326152935166d0406127118382f30b/skimage/exposure/tests/test_exposure.py#L132) does not raise error because it happens to construct an array with the same length of binning. 

I cannot think of other implementations to make it work while keeping skimage's histogram behavior that I like (I could get much nicer visualization using matplotlib). Returning both returns as list would be the best way, I believe. 

## Way to reproduce
```python
# This code passes only when 3 channels ended up having the same binning, which is not guaranteed. 
import numpy as np
from skimage import exposure

rng = np.random.default_rng(1)
img_rgb = rng.integers(0, 256, (4, 4, 3))
hist, bin_centers = exposure.histogram(img_rgb, channel_axis=-1)

Traceback (most recent call last):
  File "/home/seongbinlim/test_hist.py", line 6, in <module>
    hist, bin_centers = exposure.histogram(img_rgb, channel_axis=-1)
  File "/home/seongbinlim/miniconda3/envs/bioio/lib/python3.9/site-packages/skimage/_shared/utils.py", line 406, in fixed_func
    return func(*args, **kwargs)
  File "/home/seongbinlim/miniconda3/envs/bioio/lib/python3.9/site-packages/skimage/exposure/exposure.py", line 264, in histogram
    hist = np.stack(hist, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "/home/seongbinlim/miniconda3/envs/bioio/lib/python3.9/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
# your output here
3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0]
Linux-4.18.0-193.6.3.el8_2.x86_64-x86_64-with-glibc2.28
scikit-image version: 0.19.2
numpy version: 1.21.0
```

**Comment by grlee77** [comment]
Please try out the fix in #6413.
