### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by Dwiunzila** [scikit-image/scikit-image#6463]
## Description 
hello everyone i'm trying to build bandstructure using abinit but this error always appears

## Way to reproduce
~/Documents/Dwi Unzila/bandstructure/FeO Murni/percobaan 1$ abiopen.py t01o_DS2_GSR.nc --expose -sns=talk

## Version information
numpy version: 1.19.2
abinit : 9.6.2

Traceback (most recent call last):
  File "/home/komputasi6/.local/bin/abiopen.py", line 17, in <module>
    from abipy import abilab
  File "/home/komputasi6/.local/lib/python3.7/site-packages/abipy/__init__.py", line 18, in <module>
    from abipy.core import release
  File "/home/komputasi6/.local/lib/python3.7/site-packages/abipy/core/__init__.py", line 3, in <module>
    from .kpoints import *
  File "/home/komputasi6/.local/lib/python3.7/site-packages/abipy/core/kpoints.py", line 15, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/komputasi6/.local/lib/python3.7/site-packages/pymatgen/core/__init__.py", line 20, in <module>
    from .lattice import Lattice  # noqa
  File "/home/komputasi6/.local/lib/python3.7/site-packages/pymatgen/core/lattice.py", line 22, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/komputasi6/.local/lib/python3.7/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by mkcor** [comment]
Hi @Dwiunzila,

Where does scikit-image come into play? Did you mean to post under https://github.com/abinit/abinit/?

**Comment by stefanv** [comment]
Looks like a numpy version mismatch. Should be fixed by installing into clean env.
