### ISSUE TITLE
matplotlib 3.6.0 compatibility

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6521]
## Description

Just now in #6446, I saw the following new test failure in our Euler number example. It seems to be related to a deprecation in Matplotlib 3.6.0.

```
Warning, treated as error:
/home/runner/work/scikit-image/scikit-image/doc/examples/segmentation/plot_euler_number.py failed to execute correctly: Traceback (most recent call last):
  File "/home/runner/work/scikit-image/scikit-image/doc/examples/segmentation/plot_euler_number.py", line 151, in <module>
    display_voxels(cube)
  File "/home/runner/work/scikit-image/scikit-image/doc/examples/segmentation/plot_euler_number.py", line 129, in display_voxels
    ax = make_ax()
  File "/home/runner/work/scikit-image/scikit-image/doc/examples/segmentation/plot_euler_number.py", line 74, in make_ax
    ax = fig.gca(projection='3d')
TypeError: gca() got an unexpected keyword argument 'projection'
```

## Way to reproduce
see CI log [here](https://github.com/scikit-image/scikit-image/actions/runs/3068167689/jobs/4955299213)

**Comment by grlee77** [comment]
Change is mentioned here: https://matplotlib.org/devdocs/api/next_api_changes/removals/23077-GL.html#

**Comment by grlee77** [comment]
Looks like we just need to update that example to not pass any kwargs to `gca`
