### ISSUE TITLE
ORB.detect_and_extract fails if image too small for full pyramid

### ISSUE THREAD

**Issue by moi90** [scikit-image/scikit-image#6589]
### Description:

When the supplied image is so small that `pyramid_gaussian` returns an image where shape contains 1s, `ORB.detect_and_extract` fails with: "ValueError: The parameter `image` must be a 2-dimensional array"

The first octaves in `ORB.detect_and_extract` go fine, but at `octave=5`, the error occurs.

I think this error should be avoided by checking the shape of `octave_image` and breaking the loop early if `octave_image` is too small. This behavior would be the same as if no keypoints could be detected in the current octave.

The same would apply to `ORB.detect` (but not `ORB.extract`).

### Way to reproduce:

```Python
import numpy as np
from skimage.feature import ORB

img = np.random.rand(32,32)

orb = ORB(downscale=2)

orb.detect_and_extract(img)
```

### Traceback or output:

```Shell
Traceback (most recent call last):
  File "/tmp/ipykernel_855686/2532002236.py", line 10, in <module>
    orb.detect_and_extract(img)
  File ".../venv/lib/python3.10/site-packages/skimage/feature/orb.py", line 304, in detect_and_extract
    keypoints, orientations, responses = self._detect_octave(
  File ".../venv/lib/python3.10/site-packages/skimage/feature/orb.py", line 141, in _detect_octave
    fast_response = corner_fast(octave_image, self.fast_n,
  File ".../venv/lib/python3.10/site-packages/skimage/feature/corner.py", line 836, in corner_fast
    image = _prepare_grayscale_input_2D(image)
  File ".../venv/lib/python3.10/site-packages/skimage/feature/util.py", line 143, in _prepare_grayscale_input_2D
    check_nD(image, 2)
  File ".../venv/lib/python3.10/site-packages/skimage/_shared/utils.py", line 655, in check_nD
    raise ValueError(
ValueError: The parameter `image` must be a 2-dimensional array
```

### Version information:

```Shell
3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
Linux-5.4.0-126-generic-x86_64-with-glibc2.31
scikit-image version: 0.19.3
numpy version: 1.23.3
```

**Comment by stefanv** [comment]
Thanks for reporting @moi90! Are you interested in working on a fix?

**Comment by moi90** [comment]
Voilà!

**Comment by stefanv** [comment]
:magic_wand:
