### ISSUE TITLE
Exception axis_minor_length method in skimage.measure

### ISSUE THREAD

**Issue by brownmk** [scikit-image/scikit-image#6630]
### Description:

axis_minor_length uses: sqrt(10 * (-ev[0] + ev[1] + ev[2])) for 3D images.
The expression may be a tiny negative value and sqrt fails.
Reproducible with example included.

### Way to reproduce:

```Python
import numpy as np
import skimage.measure as skm
img=np.array(
[[[0,0,0,0,0,1,0,0,0,0],
  [0,0,0,0,1,1,1,1,0,0],
  [0,0,0,0,1,1,1,1,1,0],
  [0,0,1,1,1,1,1,1,1,0],
  [0,1,1,1,1,1,1,1,1,1],
  [1,1,1,0,1,1,1,1,1,0],
  [0,1,1,0,0,1,1,1,0,0],
  [0,1,1,0,1,1,1,1,0,0],
  [0,0,1,1,1,1,0,0,0,0]]], dtype=np.uint8)
props=skm.regionprops(img)
for p in props:
    p['MinorAxisLength']
```

### Traceback or output:

```Shell
Traceback (most recent call last):
  File "/dlab/ldrive/CBT/USLJ-DSDE_DATA-I10008/yzhou/hsc_tutorial/t.py", line 18, in <module>
    p['MinorAxisLength']
  File "/dlab/ldrive/CBT/USLJ-DSDE-I10007/DSDE/runtime_env/miniconda3/envs/hci3d/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 681, in __getitem__
    return getattr(self, PROPS[key])
  File "/dlab/ldrive/CBT/USLJ-DSDE-I10007/DSDE/runtime_env/miniconda3/envs/hci3d/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 528, in axis_minor_length
    return sqrt(10 * (-ev[0] + ev[1] + ev[2]))
_math domain error

# ev values is [9.429404414827156, 6.052764474908615, 3.376639939918539]
# (-ev[0] + ev[1] + ev[2]) is -1.3322676295501878e-15
```

### Version information:

```Shell
>>> import sys; print(sys.version)
3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)
[GCC 10.3.0]
>>> import platform; print(platform.platform())
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
scikit-image version: 0.19.2
>>> import numpy; print(f'numpy version: {numpy.__version__}')
numpy version: 1.23.4
```

**Comment by petsuter** [comment]
I run into the same error, also in scikit-image 0.19.3 unfortunately.

**Comment by petsuter** [comment]
The specific problem above worked without exception in older versions like e.g. scikit-image 0.18.1.

**Comment by bethac07** [comment]
We definitely are seeing this in CellProfiler as well - https://github.com/CellProfiler/CellProfiler/issues/4663#issuecomment-1338226513

We will probably pin skimage to 0.18 on our current "patch branch" until this is resolved! Thanks, let us know if we can help.

**Comment by NikeeShrestha** [comment]
Hi, I am having similar problem when measuring minor axis length. Is there any solution for this?

**Comment by NikeeShrestha** [comment]
> scikit-image 0.18.1.

I only solution that I could figure out is to downgrade scikit-image to 0.18.1.

**Comment by lagru** [comment]
Thanks for the detailed report and info everyone. I can confirm that this behavior appeared after 371964e9d5769c08973d9352f9ae5700de73ae7a. 

I noticed that in #6013 we ended up using 

https://github.com/scikit-image/scikit-image/blob/03862d2b3126a10769b483061cb59f2756c055e4/skimage/measure/_regionprops.py#L561-L563

instead of the one mentioned in the comment. The function `_inertia_eigvals_to_axes_lengths_3D` is never used by `regionprops`; [only in our test suite](https://github.com/scikit-image/scikit-image/blob/a91f4f8bab92c4eede48e4949805c748f436c4de/skimage/measure/tests/test_regionprops.py#L1216). Modifying the code snippet above to 
```python
  ev = self.inertia_tensor_eigvals
  return _inertia_eigvals_to_axes_lengths_3D(ev)[-1]
```
does also result in a math domain error.

@brownmk, I notice that your provided example has a shape of (1, 9, 10). Is this an abstracted example? Would you expect the algorithm to return a minor axis width that corresponds to the dimension of length 1 or the same result as if we were to use the shape (9, 10) (which is 7.350254351972905)?

**Comment by lagru** [comment]
Cc'ing @grlee77 and @jni as participants in #6013.

**Comment by brownmk** [comment]
The example came from a real 3D image, where there are many objects in it.
One object happens to be 1-pixel thick, therefore with a height of 1. It
would be nice if the library can work on all 3D objects without our
checking.  Thanks for looking into this!

**Comment by lagru** [comment]
Thanks that should indeed work. For curiosity's sake, I tried padding with zeros to get an img of shape (3, 9, 10), however the same error appears in that case.

**Comment by jni** [comment]
Oof, sorry that this got buried in the pile @brownmk @petsuter @bethac07! It's been a busy 6mo for all involved... @lagru this might not be a bad issue to tackle in a sprint at SciPy...!
