### ISSUE TITLE
Meson uses gcc on Windows instead of cl

### ISSUE THREAD

**Issue by DamienBoildieu** [scikit-image/scikit-image#6747]
### Description:

I'm struggling to compile the project from the command line `pip install -e . -vv`.
I use the `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat` to initliaze powershell with the correct environment but instead of use cl to compile, meson uses gcc from my Strawberry perl installation. Even by removing the perl/bin folder from my PATH environment variable, meson still uses its gcc and g++ compilers (The attached output error is produced when every perl folder is from PATH).

### Way to reproduce:

```Python
cmd /c '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" && start powershell'
..\venvs\skimage\Scripts\activate.ps1 # Assume the dev venv is located in ../venvs folder and is called skimage
pip install -e . -vv
```

### Traceback or output:

```Shell
Using pip 23.0 from C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip (python 3.9)
Non-user install because user site-packages disabled
Created temporary directory: C:\Users\damie\AppData\Local\Temp\pip-build-tracker-6s_6y35q
Initialized build tracking at C:\Users\damie\AppData\Local\Temp\pip-build-tracker-6s_6y35q
Created build tracker: C:\Users\damie\AppData\Local\Temp\pip-build-tracker-6s_6y35q
Entered build tracker: C:\Users\damie\AppData\Local\Temp\pip-build-tracker-6s_6y35q
Created temporary directory: C:\Users\damie\AppData\Local\Temp\pip-install-_i_q96vn
Created temporary directory: C:\Users\damie\AppData\Local\Temp\pip-ephem-wheel-cache-9siktej9
Obtaining file:///C:/Users/damie/Documents/dev/scikit-image
  Added file:///C:/Users/damie/Documents/dev/scikit-image to build tracker 'C:\\Users\\damie\\AppData\\Local\\Temp\\pip-build-tracker-6s_6y35q'
  Created temporary directory: C:\Users\damie\AppData\Local\Temp\pip-build-env-o2jnvmzf
  Running command pip subprocess to install build dependencies
  Using pip 23.0 from C:\Users\damie\Documents\dev\venvs\skimage\Lib\site-packages\pip (python 3.9)
  Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system != "Windows" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.11" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.12"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
  Collecting meson-python>=0.13.0rc0
    Using cached meson_python-0.13.0.pre0-py3-none-any.whl (82 kB)
  Collecting wheel
    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Collecting setuptools<=65.5
    Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
  Collecting packaging>=20.0
    Using cached packaging-23.0-py3-none-any.whl (42 kB)
  Collecting Cython>=0.29.24
    Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
  Collecting pythran
    Using cached pythran-0.12.1-py3-none-any.whl (4.2 MB)
  Collecting lazy_loader>=0.1
    Using cached lazy_loader-0.1-py3-none-any.whl (8.6 kB)
  Collecting numpy==1.21.1
    Using cached numpy-1.21.1-cp39-cp39-win_amd64.whl (14.0 MB)
  Collecting colorama
    Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Collecting pyproject-metadata>=0.6.1
    Using cached pyproject_metadata-0.7.1-py3-none-any.whl (7.4 kB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting meson>=0.63.3
    Using cached meson-1.0.0-py3-none-any.whl (900 kB)
  Collecting gast~=0.5.0
    Using cached gast-0.5.3-py3-none-any.whl (19 kB)
  Collecting beniget~=0.4.0
    Using cached beniget-0.4.1-py3-none-any.whl (9.4 kB)
  Collecting ply>=3.4
    Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
  Installing collected packages: ply, wheel, tomli, setuptools, packaging, numpy, meson, lazy_loader, gast, Cython, colorama, pyproject-metadata, beniget, pythran, meson-python
    Creating C:\Users\damie\AppData\Local\Temp\pip-build-env-o2jnvmzf\overlay\Scripts
  Successfully installed Cython-0.29.33 beniget-0.4.1 colorama-0.4.6 gast-0.5.3 lazy_loader-0.1 meson-1.0.0 meson-python-0.13.0rc0 numpy-1.21.1 packaging-23.0 ply-3.11 pyproject-metadata-0.7.1 pythran-0.12.1 setuptools-65.5.0 tomli-2.0.1 wheel-0.38.4
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Getting requirements to build editable ... done
  Running command pip subprocess to install backend dependencies
  Using pip 23.0 from C:\Users\damie\Documents\dev\venvs\skimage\Lib\site-packages\pip (python 3.9)
  Collecting ninja>=1.8.2
    Using cached ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
  Installing collected packages: ninja
    Creating C:\Users\damie\AppData\Local\Temp\pip-build-env-o2jnvmzf\normal\Scripts
  Successfully installed ninja-1.11.1
  Installing backend dependencies ... done
  Created temporary directory: C:\Users\damie\AppData\Local\Temp\pip-modern-metadata-8d5bo7ri
  Running command Preparing editable metadata (pyproject.toml)
  + meson setup --reconfigure --prefix=C:\Users\damie\AppData\Local\Programs\Python\Python39 C:\Users\damie\Documents\dev\scikit-image C:\Users\damie\Documents\dev\scikit-image\.mesonpy\editable\build --native-file=C:\Users\damie\Documents\dev\scikit-image\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --python.purelibdir C:\Users\damie\AppData\Local\Programs\Python\Python39\Lib\site-packages --python.platlibdir C:\Users\damie\AppData\Local\Programs\Python\Python39\Lib\site-packages
  The Meson build system
  Version: 1.0.0
  Source dir: C:\Users\damie\Documents\dev\scikit-image
  Build dir: C:\Users\damie\Documents\dev\scikit-image\.mesonpy\editable\build
  Build type: native build
  Project name: scikit-image
  Project version: 0.20.0rc5.dev0
  C compiler for the host machine: gcc (gcc 8.3.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
  C linker for the host machine: gcc ld.bfd 2.32

  ..\..\..\meson.build:1:0: ERROR: Unknown linker(s): [['gcc-ar'], ['ar'], ['gar']]
  The following exception(s) were encountered:
  Running `gcc-ar --version` gave "[WinError 2] Le fichier spécifié est introuvable"
  Running `ar --version` gave "[WinError 2] Le fichier spécifié est introuvable"
  Running `gar --version` gave "[WinError 2] Le fichier spécifié est introuvable"

  A full log can be found at C:\Users\damie\Documents\dev\scikit-image\.mesonpy\editable\build\meson-logs\meson-log.txt
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\damie\Documents\dev\venvs\skimage\Scripts\python.exe' 'C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' prepare_metadata_for_build_editable 'C:\Users\damie\AppData\Local\Temp\tmpm8shwxqe'
  cwd: C:\Users\damie\Documents\dev\scikit-image
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\operations\build\metadata_editable.py", line 37, in generate_editable_metadata
    distinfo_dir = backend.prepare_metadata_for_build_editable(metadata_dir)
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\utils\misc.py", line 735, in prepare_metadata_for_build_editable
    return super().prepare_metadata_for_build_editable(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 246, in prepare_metadata_for_build_editable
    return self._call_hook('prepare_metadata_for_build_editable', {
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\utils\subprocess.py", line 252, in runner
    call_subprocess(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\utils\subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing editable metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\commands\install.py", line 415, in run
    requirement_set = resolver.resolve(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 322, in __init__
    super().__init__(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 332, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\operations\prepare.py", line 633, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\distributions\sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\req\req_install.py", line 533, in prepare_metadata
    self.metadata_directory = generate_editable_metadata(
  File "C:\Users\damie\Documents\dev\venvs\skimage\lib\site-packages\pip\_internal\operations\build\metadata_editable.py", line 39, in generate_editable_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
Remote version of pip: 23.0
Local version of pip:  23.0
Was pip installed by pip? True
Removed file:///C:/Users/damie/Documents/dev/scikit-image from build tracker 'C:\\Users\\damie\\AppData\\Local\\Temp\\pip-build-tracker-6s_6y35q'
Removed build tracker: 'C:\\Users\\damie\\AppData\\Local\\Temp\\pip-build-tracker-6s_6y35q'
```

### Version information:

```Shell
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.20.0rc5.dev0+git20230210.1c4da031b
numpy version: 1.24.2
```

**Comment by stefanv** [comment]
Please double check that the compiler was removed from your PATH. It shouldn't be able to find it if it's not there.

Either way, this is not something we can solve in skimage, we rely on Meson to do compiler detection (but I don't think they have a bug, in this case).

**Comment by DamienBoildieu** [comment]
I checked and even after removed Perl, It kept to produce the same output.
However, after a Windows update issue, I had to reinstall the OS and once it was done I tried to compile using WSL and it worked. In order to not waste more time, I'll continue with WSL
