### ISSUE TITLE
Error introduced in version 0.20.0

### ISSUE THREAD

**Issue by rodrigomologni** [scikit-image/scikit-image#6784]
### Description:

The executable produced by [PyInstaller](https://pyinstaller.org/en/stable/) is producing an error introduced by scikit-image v0.20.0.

![image](https://user-images.githubusercontent.com/1608652/223493602-dc0ec9a4-5a61-4d8d-833f-c186e94a6cad.png)

### Traceback or output:

```Shell
Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "views\main_view.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "services\project_service.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "analysis\classify_fullcore.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "skimage\__init__.py", line 74, in <module>
  File "lazy_loader\__init__.py", line 243, in attach_stub
ValueError: Cannot load imports from non-existent stub 'D:\\Users\\Rodrigo\\GitHub\\mosis\\dist\\mosis\\skimage\\__init__.pyci'
```

### Version information:

```Shell
3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.20.0
numpy version: 1.24.2
```

**Comment by stefanv** [comment]
See also https://github.com/scientific-python/lazy_loader/pull/39

**Comment by Czaki** [comment]
more details how to solve it after lazy loader will be released could be found here https://github.com/scikit-image/scikit-image/issues/6772#issuecomment-1449671566
