### ISSUE TITLE
<ImportError: cannot import name '_validate_lengths'>

### ISSUE THREAD

**Issue by Adeel-farukh3** [scikit-image/scikit-image#7047]
### Description:

I need to know which version of scikit-image is compatible with Numpy1.19.5. As I already have the old version of scikit-image0.18.0, If I try to update the scikit-image version then it automatically updates the numpy version which is not required. 

### Way to reproduce:

Error message:  /home/adeel/.local/lib/python3.6/site-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "generate_data.py", line 3, in <module>
    from tool.dataset import clocs_data
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion-old/CLOC_fusion/tool/dataset.py", line 7, in <module>
    from pcdet.datasets.kitti.kitti_object_eval_python.eval import d3_box_overlap
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion-old/CLOC_fusion/pcdet/datasets/__init__.py", line 8, in <module>
    from .kitti.kitti_dataset import KittiDataset
  File "/home/adeel/PointPillars-Camera-LiDAR-Fusion-old/CLOC_fusion/pcdet/datasets/kitti/kitti_dataset.py", line 5, in <module>
    from skimage import io
  File "/usr/lib/python3/dist-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/usr/lib/python3/dist-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/usr/lib/python3/dist-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

### Version information:

```Shell
>>> import skimage                                                                             
>>> print(skimage.__version__) 
0.18.0
>>> import numpy
>>> print(numpy.__version__) 
1.18.5
>>> import torch
1.8.1+cu111
python3.8.16
```

**Comment by stefanv** [comment]
The easiest workaround to your problem may be to replace arraycrop.py with the current version, found at:

https://github.com/scikit-image/scikit-image/blob/main/skimage/util/arraycrop.py

We typically only set minimum dependencies, so you can always try installing older versions of skimage and see whether it works. But if NumPy was updated, some package in your list set that as a requirement.
