### ISSUE TITLE
Error when using pip to install version 0.17.2

### ISSUE THREAD

**Issue by xdTAGCLAN** [scikit-image/scikit-image#7062]
### Description:

I'm trying to install scikit-image==0.17.2 using pip, but doing so results in an error.

### Way to reproduce:

Running the command: "pip install scikit-image==0.17.2" results in this:

```
Collecting scikit-image==0.17.2
  Using cached scikit-image-0.17.2.tar.gz (29.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\....\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\....\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\....\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\....\AppData\Local\Temp\pip-build-env-hgr10cdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\....\AppData\Local\Temp\pip-build-env-hgr10cdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\....\AppData\Local\Temp\pip-build-env-hgr10cdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\....\AppData\Local\Temp\pip-build-env-hgr10cdb\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 234, in <module>
        File "<string>", line 58, in openmp_build_ext
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Version information:

```Shell
3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: Not installed
numpy version: 1.24.3
python version: Python 3.10.1
```

**Comment by stefanv** [comment]
Are you sure numpy is available in that environment? The error message is in conflict with the versions you report. `python -m pip list` should be accurate.

**Comment by xdTAGCLAN** [comment]
> Are you sure numpy is available in that environment? The error message is in conflict with the versions you report. `python -m pip list` should be accurate.

Checking that is says "numpy                  1.24.3"

**Comment by nathan-g1** [comment]
Same thing happening

**Version information:**
MacOs-13.0 (M1)
scikit-image version: 0.23.2
numpy version: 1.24.3
python version: Python 3.9

**Comment by nathan-g1** [comment]
> Same thing happening
> 
> **Version information:** MacOs-13.0 (M1) scikit-image version: 0.23.2 numpy version: 1.24.3 python version: Python 3.9

Resolved after using `pip3` over `pip`

**Comment by stefanv** [comment]
Sounds like different Python versions. The best way to ensure that you're running the version of Python you think you are is to use `python -m pip`.

@xdTAGCLAN I'm sorry we couldn't resolve your issue directly, and at this point I don't know how to debug it further. If you are still experiencing the same problem, please let us know so we can re-open this issue and investigate.
