### ISSUE TITLE
`morphology.flood` fails for boolean image type if tolerance is set

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7301]
### Description:

This is because neither `numpy.finfo` nor `numpy.iinfo` work for a boolean dtype in

https://github.com/scikit-image/scikit-image/blob/f4c1b34ac968d9fda332d7d9a63c83499aaac1f6/skimage/morphology/_flood_fill.py#L275-L280

### Way to reproduce:

```python
import numpy as np
import skimage as ski

image = np.empty([10, 10], dtype=bool)
ski.morphology.flood(image, (1, 1), tolerance=2)
```

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/home/lg/Res/scikit-image/skimage/morphology/_flood_fill.py", line 276, in flood
    max_value = np.finfo(working_image.dtype).max
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lg/.local/lib/micromamba/envs/skimage2numpy2/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 519, in __new__
    raise ValueError("data type %r not inexact" % (dtype))
ValueError: data type <class 'numpy.bool'> not inexact
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/lg/.local/lib/micromamba/envs/skimage2numpy2/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-2c35428dde4a>", line 5, in <module>
    ski.morphology.flood(image, (1, 1), tolerance=2)
  File "/home/lg/Res/scikit-image/skimage/morphology/_flood_fill.py", line 279, in flood
    max_value = np.iinfo(working_image.dtype).max
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lg/.local/lib/micromamba/envs/skimage2numpy2/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 697, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'b'.
```

</p>
</details> 

### Version information:

```Shell
3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]
Linux-6.7.0-arch3-1-x86_64-with-glibc2.38
scikit-image version: 0.23.0rc0.dev0+git20240118.4f65ab74a
numpy version: 2.0.0.dev0+git20240113.d2f60ff
```

**Comment by decorouz** [comment]
Would converting the image to `int` type if input image is boolean type be a good work around.?

**Comment by michaelbratsch** [comment]
The issue has been fixed with: https://github.com/scikit-image/scikit-image/commit/5ccee45db9f9556297f083bb2f174fecceb4d756

**Comment by lagru** [comment]
Oh, thank you @michaelbratsch! That seems correct. I'm curious, how did you come across this and did you find the commit by simply searching? :)

**Comment by michaelbratsch** [comment]
> Oh, thank you @michaelbratsch! That seems correct. I'm curious, how did you come across this and did you find the commit by simply searching? :)

I was looking at the issues of scikit-image and checking whether I could participate by fixing something. Tried to reproduce the current issue and found your commit via git blame. But apparently the things I am investigating are already solved (same as https://github.com/scikit-image/scikit-image/pull/7490) ;)

I will have a look at https://github.com/scikit-image/scikit-image/issues/7420. Not fully sure I can contribute there though. If you have other suggestions, please let me know. You can also write to me directly via email.
