### ISSUE TITLE
`test_ellipse_model_estimate_failers` fails on master for Mac M1 (arm64)

### ISSUE THREAD

**Issue by michaelbratsch** [scikit-image/scikit-image#7497]
### Description:

`assert not model.estimate(np.array([[50, 80], [51, 81], [52, 80]]))` is failing. This means it was able to compute an estimate for the EllipseModel even though it should not.

Generally, it is quite unstable for three coordinates though (probably because it is underdetermined to specify an ellipse). Slightly modifying the points `assert not model.estimate(np.array([[50, 80], [51, 81], [52.2, 80]]))`  is passing (meaning it was not able to compute an estimate).

I guess slightly modifying the example on a different platform also leads to passing/failing results and it is hard to get a combination that is working for all platforms.

### Way to reproduce:

The model estimation gives a roughly reasonable output for the model estimation in the unit test which is supposed to be failing:
```
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
from skimage.measure import EllipseModel

model = EllipseModel()

points = np.array([[50, 80], [51, 81], [52, 80]])
success = model.estimate(points)
assert success == True

xc, yc, a, b, theta = model.params
ellipse = Ellipse((xc, yc), 2*a, 2*b, angle=theta, edgecolor='r', fc='None', lw=2)

ax = plt.gca()
ax.add_patch(ellipse)
ax.scatter(points[:,0], points[:,1])
plt.show()
```

![ellipse_fit](https://github.com/user-attachments/assets/c4a2f687-de9c-407a-a3a2-6da2b2ec68cd)

### Version information:

```Shell
3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)]
macOS-14.5-arm64-arm-64bit
scikit-image version: 0.24.0
numpy version: 2.0.1
```

**Comment by michaelbratsch** [comment]
The unit test is currently known to be failing for 32-bit environment:
```
@xfail(
    condition=arch32,
    reason=(
        'Known test failure on 32-bit platforms. See links for '
        'details: '
        'https://github.com/scikit-image/scikit-image/issues/3091 '
        'https://github.com/scikit-image/scikit-image/issues/2670'
    ),
)
```

**Comment by michaelbratsch** [comment]
Unrelated to the above, the `estimate` of `EllipseModel` is also unstable in the sense that I can provoke with the input points `[[0, 0], [2, 3], [4, 6]]` the following error :
```
    phi %= np.pi
TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
```

This is because of rounding errors the matrix `M` is not symmetric anymore and one gets complex eigenvalues for: https://github.com/scikit-image/scikit-image/blob/a160f384523ac70173d069954b7084bee79fb68e/skimage/measure/fit.py#L486

For this particular combination it passed the condition:
https://github.com/scikit-image/scikit-image/blob/a160f384523ac70173d069954b7084bee79fb68e/skimage/measure/fit.py#L488
so the computation continues even with complex values.

I think there should be a check for complex eigenvalues and a `return False` in the estimation code because it is a clear indication that the computation went wrong.

**Comment by stefanv** [comment]
Should we be using `eigh` instead of `eig`? I'm a bit nervous about checking for *any* complex component present; not sure how sensitive that would be.

I also notice `inv` calls in that function, which are seldom a good idea (should be `linalg.solve` calls instead, unless those matrices are small and well behaved).

**Comment by michaelbratsch** [comment]
> Should we be using `eigh` instead of `eig`? I'm a bit nervous about checking for _any_ complex component present; not sure how sensitive that would be.

I wrote in https://github.com/scikit-image/scikit-image/issues/7497#issuecomment-2291755686 that `M` is symmetric but that is a mistake from my side. Realised it when testing your suggestion and replacing `eig` by `sigh`. The `inv(C1)` of `M = inv(C1) @ (S1 - S2 @ inv(S3) @ S2.T)` makes it non-symmetric so that we can not use `eigh` but I think the algorithm still relies on real valued eigenvectors. I will update the note https://github.com/scikit-image/scikit-image/issues/7497#issuecomment-2291755686.

> I also notice `inv` calls in that function, which are seldom a good idea (should be `linalg.solve` calls instead, unless those matrices are small and well behaved).

Had the same thought, maybe this gives an improvement.

**Comment by michaelbratsch** [comment]
If I switch from numpy 2.0.1 (using accelerate) to numpy (using openblas64), the `test_ellipse_model_estimate_failers` is pass but `test_ellipse_parameter_stability` is failing with

>          phi = 0.5 * np.arctan((2.0 * b) / (a - c))
>          RuntimeWarning: divide by zero encountered in scalar divide
>          skimage/measure/fit.py:522: RuntimeWarning

To me it seems that at least for arm64, the unit test for the `EllipseModel` are not very robust. I am just surprised that the pipelines on x64 are passing.

**Comment by jakublipinski** [comment]
> Unrelated to the above, the `estimate` of `EllipseModel` is also unstable in the sense that I can provoke with the input points `[[0, 0], [2, 3], [4, 6]]` the following error :
> 
> ```
>     phi %= np.pi
> TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
> ```
> 
> This is because of rounding errors the matrix `M` one gets complex eigenvectors for:
> 
> https://github.com/scikit-image/scikit-image/blob/a160f384523ac70173d069954b7084bee79fb68e/skimage/measure/fit.py#L486
> 
> For this particular combination it passed the condition:
> 
> https://github.com/scikit-image/scikit-image/blob/a160f384523ac70173d069954b7084bee79fb68e/skimage/measure/fit.py#L488
> 
> 
> so the computation continues even with complex values.
> I think there should be a check for complex eigenvectors and a `return False` in the estimation code because it is a clear indication that the computation went wrong. If wanted, I can open a pull request for that.

I am having the same issue when estimating an ellipse. It happens during the `measure.ransac` algorithm so that whole estimation fails. A fix would be much appreciated.

**Comment by lagru** [comment]
I'm neither on arm64 nor on a Mac, so it's difficult for me to reproduce or debug this locally. 

>> I also notice inv calls in that function, which are seldom a good idea (should be linalg.solve calls instead, unless those matrices are small and well behaved).
>
> Had the same thought, maybe this gives an improvement.

@michaelbratsch, since you are on a Mac, would you be interested in making a PR that switches to `linalg.solve`? :pray: 

What do you think about the idea to fail on larger `scale` in https://github.com/scikit-image/scikit-image/blob/efe339b09ee7d9d8eb163d6750005ab0bef703b8/skimage/measure/fit.py#L451-L452

If scale is near `np.finfo(float_type).tiny`, it seems unsurprising that the rest of the algorithm struggles with numerical precision errors. Increasing the failure range by a factor like 10 or higher,
```python
if scale < np.finfo(float_type).tiny * 10:
```
might weed out more unstable scenarios?

**Comment by michaelbratsch** [comment]
@jakublipinski I think in your case, increasing `min_samples` of `ransac` to 5 (or more) should help to avoid the instability because the ellipse estimation is not underdetermined anymore. If the problem still persists, please share a small reproducer.

I think we should just return `False` for the ellipse estimation in case we have less than 5 data points because otherwise the estimation is underdetermined. To address this, I opened the pull request https://github.com/scikit-image/scikit-image/pull/7648. This will fix the unstable unit test in the description of the issue.

@lagru I had a look at switching to `linalg.solve` but this does not give an advantage at least for the small example in the description. Could still give it a try in another pull-request because it might be beneficial for many datapoints.

@lagru The `scale` is for the example in the description around 0.66 so it does not seem sufficient to handle the unstable scenario.

**Comment by jakublipinski** [comment]
> @jakublipinski I think in your case, increasing `min_samples` of `ransac` to 5 (or more) should help to avoid the instability because the ellipse estimation is not underdetermined anymore. If the problem still persists, please share a small reproducer.
> 
> I think we should just return `False` for the ellipse estimation in case we have less than 5 data points because otherwise the estimation is underdetermined. To address this, I opened the pull request #7648. This will fix the unstable unit test in the description of the issue.
> 

@michaelbratsch thanks for taking look at it. In my case I'm using `min_samples = 8`. Still, the following random set of points chosen by `ransac` causes the `EllipseModel.estimate()` to throw `TypeError`. Below, please find the exact selection of points causing the issue. They lie on same line and that is a root of the problem but they are just random selection from a larger set and it may happen during `ransac`.

```python
import skimage, numpy

print("Numpy version:", numpy.__version__)
print("Skimage version:", skimage.__version__)

data = numpy.array([
       [166. , 171.5],
       [167. , 170.5],
       [102. , 179.5],
       [ 94. , 180.5],
       [134. , 175.5],
       [151. , 172.5],
       [ 95. , 179.5],
       [118. , 177.5]], dtype=numpy.float64)

em = skimage.measure.EllipseModel()
em.estimate(data)
```
```console
Numpy version: 2.0.2
Skimage version: 0.25.0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
    phi += np.pi / 2

TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
```

**Comment by lagru** [comment]
> @lagru I had a look at switching to `linalg.solve` but this does not give an advantage, at least for the small example in the description. Could still give it a try in another pull-request because it might be beneficial for many datapoints.

Thanks, it's worth a try. Might be useful to switch anyway even if it doesn't improve the particular example, just to increase robustness in general.

> @lagru The scale is for the example in the description around 0.66 so it does not seem sufficient to handle the unstable scenario of the description.

Oh, I should have been clearer, that this is just a general improvement I'm suggesting. Not necessarily one, that addresses the issue here. I just noticed that the check described in https://github.com/scikit-image/scikit-image/issues/7497#issuecomment-2571614757 seems very restrictive. It's basically a convoluted way of checking if `data.std()` is zero. Because zero is the only result that can be smaller than the smallest number we can resolve (for float anyway). I was suggesting that we improve this check because the algorithm might still struggle for `data.std()` that is still magnitudes larger.

But that could be its own PR combined with the above optimization of using `linalg.solve`. :+1:

**Comment by michaelbratsch** [comment]
@jakublipinski Thank you for the example. It seems that the datapoints form a quite elongated ellipse:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/6fef637d-3484-4876-a90f-87d0215547f1" />

In my case it does not crash but the fit is obviously wrong.

Skimage uses the algorithm proposed in

> Halir, R.; Flusser, J. "Numerically stable direct least squares fitting of ellipses"

https://arxiv.org/pdf/2210.12915 states about it the following
> ..., more computationally efficient methods based on the least squares (LS) approach were proposed [6]–[14]. These methods typically work well for clean or simple instances. However, the performance of the LS based methods can degrade a lot in the presence of outliers, which deviate significantly from the underlying ellipse, and appear very often in the extracted data points.

So I have the feeling that this stability problem can't be solved easily with the current algorithm. Additionally, there seems to be no obvious candidate algorithm that has no draw-backs. So it is hard to say how to proceed from here.

@jakublipinski If you really need to get `ransac` to work with your dataset maybe this will help
```python
class NonCrashingEllipseModel(EllipseModel):
    def estimate(self, data) -> bool:
        try:
            return super().estimate(data)()
        except:
            return False
```
because the crashing ones will be discarded and for the ones with a bad fit, the residuals will be above `residual_threshold` and being discarded, too. So the hope is that the fit will work by chance for at least some examples. But this is obviously not a proper approach but rather a hack for the desperate.

Side note: I also tried to use `np.linalg.solve` for this example but it does not give an improvement.

**Comment by lagru** [comment]
Just a note, for the example in https://github.com/scikit-image/scikit-image/issues/7497#issuecomment-2575022895 I get what seems like a sensible fit. 

<details><summary>Details</summary>
<p>

![image](https://github.com/user-attachments/assets/b3a639f9-2c3a-4515-bf8a-98ab4e036b98)

</p>
</details>

**Comment by jakublipinski** [comment]
> @jakublipinski If you really need to get `ransac` to work with your dataset maybe this will help
> 
> ```python
> class NonCrashingEllipseModel(EllipseModel):
>     def estimate(self, data) -> bool:
>         try:
>             return super().estimate(data)
>         except:
>             return False
> ```
> 
> because the crashing ones will be discarded and for the ones with a bad fit, the residuals will be above `residual_threshold` and being discarded, too. So the hope is that the fit will work by chance for at least some examples. This is obviously not a proper approach but rather a hack for the desperate.

Thanks @michaelbratsch - I'm desperate enough to use this approach. Thanks for the hint.

**Comment by michaelbratsch** [comment]
@lagru You are absolutely right, the rotation just does not fit. I forgot to convert the angle to degrees as it is needed for the `Ellipse` of matplotlib

```python
xc, yc, a, b, theta = em.params
from matplotlib.patches import Ellipse
ellipse = Ellipse((xc, yc), 2*a, 2*b, angle=np.degrees(theta), edgecolor='r', fc='None', lw=2, label='ellipse fit')
```
After the fix, it matches as in your case.

So it is strange that I can't reproduce the instability on my macOS-15.2-arm64-arm-64bit even using `numpy==2.0.2`.

@jakublipinski I just realised you never explicitly mentioned the platform you are working on. Is it arm64 or something else? Basically the output of `import platform; print(platform.platform())`.

@jakublipinski Since we can't reproduce the instability, is it possible for you to share a small reproducer for `ransac` using the whole dataset. Maybe that way it will crash on our computers for one of the cases.

**Comment by jakublipinski** [comment]
> @jakublipinski I just realised you never explicitly mentioned the platform you are working on. I somehow assumed it is arm64 due to the title of the issue. Please post the output of `import platform; print(platform.platform())`.

I am still able to reproduce with the following code:
```python
import skimage, numpy, platform

print("Platform: ", platform.platform())
print("Numpy version:", numpy.__version__)
print("Skimage version:", skimage.__version__)

data = numpy.array([
       [166. , 171.5],
       [167. , 170.5],
       [102. , 179.5],
       [ 94. , 180.5],
       [134. , 175.5],
       [151. , 172.5],
       [ 95. , 179.5],
       [118. , 177.5]], dtype=numpy.float64)

em = skimage.measure.EllipseModel()
em.estimate(data)
```
I get the output:
```console
Platform:  macOS-10.16-x86_64-i386-64bit
Numpy version: 2.0.2
Skimage version: 0.25.0
Traceback (most recent call last):
  File "/Users/jakublipinski/SourceCode/fet_front_camera_analytics/ellipse_instability.py", line 18, in <module>
    em.estimate(data)
  File "/Users/jakublipinski/miniconda3/envs/fet/lib/python3.11/site-packages/skimage/measure/fit.py", line 533, in estimate
    phi %= np.pi
TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
```

I can also reproduce it on `Skimage version: 0.26.0rc0.dev0`.
So I believe exception occurs on `macOS-10.16-x86_64-i386-64bit` platform.

**Comment by dagewa** [comment]
Note I also see the failure with @jakublipinski's test in https://github.com/scikit-image/scikit-image/issues/7497#issuecomment-2579823946 on Linux:
```console
Platform:  Linux-6.8.0-136-generic-x86_64-with-glibc2.39
Numpy version: 2.5.1
Skimage version: 0.26.0
<python-input-0>:17: FutureWarning: Calling ``EllipseModel()`` (without arguments) has been deprecated since version 0.26 and will be removed in version 2.2; see help for ``EllipseModel``.
<python-input-0>:18: FutureWarning: `estimate` is deprecated since version 0.26 and will be removed in version 2.2. Please use `EllipseModel.from_estimate` class constructor instead.
Traceback (most recent call last):
  File "<python-input-0>", line 18, in <module>
    em.estimate(data)
    ~~~~~~~~~~~^^^^^^
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/_shared/utils.py", line 690, in wrapped
    return func(*args, **kwargs)
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/measure/fit.py", line 1089, in estimate
    return self._estimate(data) is None
           ~~~~~~~~~~~~~~^^^^^^
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/measure/fit.py", line 952, in _estimate
    phi %= np.pi
TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
```

**Comment by stefanv** [comment]
Will have to dig a bit deeper; I can't reproduce this on `main` on Linux; but if this is indeed a sensitivity issue, as suggested in some of the other comments, I suppose that's not surprising.

**Comment by dagewa** [comment]
Ok I think something else is going on for me because I get that error even trying to reproduce one of the examples from https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.EllipseModel

```python
>>> from skimage.measure import EllipseModel
>>> import numpy as np
>>> em = EllipseModel((10, 15), (8, 4), np.deg2rad(30))
... xy = em.predict_xy(np.linspace(0, 2 * np.pi, 25))
... ellipse = EllipseModel.from_estimate(xy)
... ellipse.center
... 
Traceback (most recent call last):
  File "<python-input-2>", line 3, in <module>
    ellipse = EllipseModel.from_estimate(xy)
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/measure/fit.py", line 851, in from_estimate
    return super().from_estimate(data)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/measure/fit.py", line 79, in from_estimate
    msg = tf._estimate(data, warn_only=False)
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.13/site-packages/skimage/measure/fit.py", line 952, in _estimate
    phi %= np.pi
TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
```
This did not used to happen, so it seems like something to do with updates to either numpy or skimage versions (which we take from conda)

Edit: works with numpy 2.4.6, but not 2.5.0

**Comment by dagewa** [comment]
Ah, pretty sure this is why https://github.com/numpy/numpy/pull/30411. And sorry, I'm just catching up. I see this is fixed by https://github.com/scikit-image/scikit-image/commit/b9b377cb403284954533b4cc2e61543a79e2d04c, but not in a release yet.

**Comment by stefanv** [comment]
Thanks for investigating! That would make sense.

We should get a new release out; we're just on the back of a pretty significant internal refactor, and we want the dust to settle a bit before doing that.
